Mnemonas'semiware: random::Density Class Reference
random::Density Class Reference
Defines a 1D real probabilty density.
#include <random.hpp>
Public Member Functions
virtual double p (double x) const
Returns the probability for the given value.
Detailed Description
Defines a 1D real probabilty density.
Definition at line 16 of file random.hpp.
Member Function Documentation
p()
double random::Density::p (double x) const virtual
Returns the probability for the given value.
Parameters
x The input value.
Returns
A value in [0,1].
Reimplemented in Histogram.
Definition at line 9 of file random.cpp.
References assume().
Referenced by random::gamma(), and Histogram::getDivergence().
The documentation for this class was generated from the following files:
src/util/random.hpp
src/util/random.cpp
mnemosyne brainybot (version of 2018-01-23 at 17:20:17)