Mnemonas'semiware: network::KernelExperimentalEstimator Class Reference
network::KernelExperimentalEstimator Class Reference
Defines a discrete-time recurrent kernel transform experimental estimator.
#include <KernelExperimentalEstimator.hpp>
Public Member Functions
KernelExperimentalEstimator (KernelTransform &transform, TransformCriterion &criterion)
Resets the estimator for a given kernel transform.
double run (double criterion_epsilon=1e-6, double weights_epsilon=1e-4, unsigned int maxIterations=100, String dumpDirectory="", String dumpHeader="{}")
Runs the estimation.
Public Member Functions inherited from network::KernelEstimator
KernelEstimator (KernelTransform &transform, TransformCriterion &criterion)
Resets the estimator for a given kernel transform.
double run ()
Runs one step of estimation.
double getCost () const
Gets the last estimated cost.
double getValue (unsigned int n, double t) const
Gets the last estimated state value.
double getError (unsigned int n, double t) const
Gets the last estimated backward error.
const double * getWeights () const
Gets the last estimated weights.
double updateReadout (unsigned int N0=0)
Updates the weights given a readout estimation.
const CurveFit & getFit (String what="cost") const
Gets some fits of the estimation runs.
Additional Inherited Members
Protected Attributes inherited from network::KernelEstimator
KernelTransform & transform
The tranform to estimate.
unsigned int N
The transform related parameters.
unsigned int T
unsigned int R
TransformCriterion & criterion
The criterion to apply.
CurveFit costs
The cost and errors traces.
CurveFit output_errors
CurveFit backward_errors
CurveFit ratio_negligible
CurveFit ratio_saturated
CurveFit simulation_time
CurveFit tuning_time
CurveFit iteration_time
double cost
double * weights0
double * values0
double * errors
double drho_mean
bool once
std::vector< connection > * connections
unsigned int k_negligible
Number of negligible or saturated values during a backward tuning, over the N T values.
unsigned int k_saturated
Detailed Description
Defines a discrete-time recurrent kernel transform experimental estimator.
This estimator experiments several possible criterion decrement as discussed in the corresponding publication.
Definition at line 5 of file KernelExperimentalEstimator.hpp.
Constructor & Destructor Documentation
KernelExperimentalEstimator()
network::KernelExperimentalEstimator::KernelExperimentalEstimator (KernelTransform & transform, TransformCriterion & criterion)
Resets the estimator for a given kernel transform.
Parameters
transform The kernel transform to estimate.
The recurrent transform is fully buffered fo the estimation purpose.
criterion The criterion to use for the estimation.
Definition at line 3 of file KernelExperimentalEstimator.cpp.
References Histogram::add(), CurveFit::asString(), Histogram::asString(), network::KernelEstimator::costs, network::KernelEstimator::criterion, network::KernelEstimator::errors, network::KernelTransform::getKernelDimension(), network::KernelTransform::getKernelValue(), network::KernelEstimator::getValue(), network::KernelTransform::getWeightCount(), network::KernelEstimator::k_negligible, network::KernelEstimator::k_saturated, solver::linsolve(), solver::minimize(), network::KernelEstimator::N, network::TransformCriterion::rho(), network::KernelEstimator::run(), s_printf(), network::KernelTransform::setWeight(), network::KernelEstimator::T, network::KernelEstimator::transform, network::TransformCriterion::update(), and network::KernelEstimator::weights0.
Member Function Documentation
run()
double network::KernelExperimentalEstimator::run (double criterion_epsilon = 1e-6, double weights_epsilon = 1e-4, unsigned int maxIterations = 100, String dumpDirectory = "", String dumpHeader = "{}")
Runs the estimation.
Parameters
criterion_epsilon Relative precision on the state values, with respect to the initial cost.
The iteration stops if the criterion decrease is lower than this value.
weights_epsilon Precision on the weight values.
maxIterations The maximal number of iteration.
dumpDirectory A string with the directory name of the estimation dump.
If "stdout" printf on stdout.
An empty string means no dump.
dumpHeader A JSON string with a description of estimation run parameters.
Returns
The normalized minimal cost .
Definition at line 188 of file KernelExperimentalEstimator.cpp.
References CurveFit::add(), CurveFit::asString(), CurveFit::clear(), network::KernelEstimator::costs, s_printf(), s_save(), network::BufferedInput::save(), CurveFit::show(), and network::KernelEstimator::transform.
The documentation for this class was generated from the following files:
src/network/KernelExperimentalEstimator.hpp
src/network/KernelExperimentalEstimator.cpp
mnemosyne brainybot (version of 2018-01-23 at 16:26:18)