Mnemonas'semiware: src/util/now.h File Reference
now.h File Reference
Functions
double now (bool daytime=false, bool relative=false)
Gets the cpu or real time from program start.
Function Documentation
now()
double now (bool daytime = false, bool relative = false)
Gets the cpu or real time from program start.
Parameters
daytime If true considers day time, if false consider cpu time.
relative If true returns the relative time between two calls of now(), else returns the time from program start.
Returns
The time in seconds with maximal precision of micro-second.
Definition at line 8 of file now.c.
References assume().
Referenced by ParameterOptimizer::add(), ParameterOptimizer::clear(), network::KernelEstimator::run(), and random::setSeed().
mnemosyne brainybot (version of 2018-01-23 at 17:20:17)