BrainyBot'semiware: src/inc/assume.c File Reference
assume.c File Reference
Functions
void assume (bool condition, String thrown, const char *message,...)
Checks a condition at run-time a throw a fatal exception if not verified.
Function Documentation
assume()
void assume (bool condition, String thrown, const char * message, ...)
Checks a condition at run-time a throw a fatal exception if not verified.
Parameters
condition The condition that must be true.
thrown The name of the thrown exception if the assume fails. Typical exception are:
illegal-argument : when a method or function receives an argument with a spurious value.
illegal-state : when detecting an unexpected condition (a bug) at some point in the code.
numerical-error : when detecting an unexpected condition (a bug) at some point in the code.
IO-exception : when an input/output operation fails.
message The error message, a string format à-la printf with more parameters if used.
Exceptions
The exception to be thrown if the assume fails.
Definition at line 6 of file assume.c.
Referenced by Histogram::add(), BufferedInput::add(), random::booleans(), BufferedInput::BufferedInput(), Struct::clean(), Histogram::draw(), KernelEstimator::drho(), Input::get(), RecurrentTransform::get(), BufferedInput::get(), Histogram::get(), Histogram::getDensityModel(), Histogram::getDivergence(), LinearTransform::getKernelDerivative(), KernelTransform::getKernelDerivative(), KernelTransform::getKernelDimension(), LinearTransform::getKernelValue(), KernelTransform::getKernelValue(), RecurrentTransform::getValue(), RecurrentTransform::getValueDerivative(), Histogram::Histogram(), LinearNonLinearTransform::LinearNonLinearTransform(), Struct::load(), solver::minimize(), network_test(), now(), random::Density::p(), Histogram::plot(), random_test(), reverse_engineering(), KernelEstimator::rho(), s_printf(), s_regex_match(), s_regex_replace(), s_regex_test(), s_save(), BufferedInput::save(), Struct::save(), KernelTransform::setWeight(), solver_test(), and Struct_test().
mnemosyne brainybot (version of 2017-06-05 at 15:36:53)