Mnemonas'semiware: src/util/assume.h File Reference
assume.h File Reference
Functions
void assume (bool condition, String thrown, String message,...)
Checks a condition at run-time and throws a fatal error exception and/or dumps a warning if not verified.
Function Documentation
assume()
void assume (bool condition, String thrown, String message, ...)
Checks a condition at run-time and throws a fatal error exception and/or dumps a warning if not verified.
Parameters
condition The condition that must be true.
thrown The name of the thrown exception if the assume fails. Typical exception are:
illegal-argument : when a method or function receives an argument with a spurious value.
illegal-state : when detecting an unexpected condition (a bug) at some point in the code.
numerical-error : when detecting an unexpected condition (a bug) at some point in the code.
IO-exception : when an input/output operation fails. The exception is a fatal error unless its names starts with a space (e.g., " numerical-error"), in that case a simple warning is printed on stderr.
message The error message, a string format à-la printf with more parameters if used.
Exceptions
The exception to be thrown if the assume fails.
Definition at line 7 of file assume.c.
Referenced by Histogram::add(), network::BufferedInput::add(), Struct::asString(), Density::booleans(), network::BufferedInput::BufferedInput(), network::Observable::doValue(), network::Observable::doValueDerivative(), Histogram::draw(), network::TransformCriterion::drho(), network::Input::get(), network::RecurrentTransform::get(), Histogram::get(), network::BufferedInput::get(), Histogram::getDensityModel(), Histogram::getDivergence(), network::LinearTransform::getKernelDerivative(), network::KernelTransform::getKernelDerivative(), network::KernelTransform::getKernelDimension(), network::LinearTransform::getKernelValue(), network::KernelTransform::getKernelValue(), network::RecurrentTransform::getLyapunovExponent(), network::ObservableCriterion::getObservable(), network::ObservableCriterion::getObservableExpectedValue(), network::ObservableCriterion::getObservables(), network::Observable::getValue(), network::RecurrentTransform::getValue(), network::Observable::getValueDerivative(), network::RecurrentTransform::getValueDerivative(), network::RecurrentTransform::getValueDerivativeApproximation(), Histogram::Histogram(), network::RecurrentTransform::isConnected(), network::LinearNonLinearTransform::LinearNonLinearTransform(), solver::minimize(), network::KernelTransform::newKernelTransform(), now(), Density::p(), Histogram::plot(), network::RecurrentTransform::reset(), network::TransformCriterion::rho(), network::KernelDistributedEstimator::run(), s_load(), s_printf(), s_regex_match(), s_regex_replace(), s_save(), network::BufferedInput::save(), network::RecurrentTransform::set(), network::SparseNonLinearTransform::setConnections(), network::SparseNonLinearTransform::setLeak(), network::KernelTransform::setWeight(), network::LinearTransform::setWeights(), network::SoftMaxTransform::setWeights(), network::SparseNonLinearTransform::setWeights(), network::LinearNonLinearTransform::setWeights(), network::IntegrateAndFireTransform::setWeights(), network::KernelTransform::setWeights(), network::SupervisedCriterion::SupervisedCriterion(), Struct::toDouble(), and network::KernelEstimator::updateReadout().
mnemosyne brainybot (version of 2018-03-27 at 07:27:18)