BrainyBot'semiware: RecurrentTransform Class Reference
RecurrentTransform Class Reference
Defines a discrete-time recurrent input/output transform.
#include <RecurrentTransform.hpp>
Public Member Functions
RecurrentTransform (const RecurrentTransform &transform)
RecurrentTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
virtual ~RecurrentTransform ()
RecurrentTransform & reset (bool buffered=false)
Resets the transform buffering.
unsigned int getR () const
Gets the maximal recuurent range.
double get (unsigned int n, double t) const
Returns the input value.
virtual double getValue (unsigned int n, double t) const
Implements the discrete-time recurrent equation.
virtual double getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const
Implements the discrete-time recurrent equation derivative.
Public Member Functions inherited from Transform
Transform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
const Input & getInput ()
Gets the transform input.
Public Member Functions inherited from Input
Input (unsigned int N, double T)
Resets the input dimensions.
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
Protected Attributes
unsigned int R
unsigned int L
Protected Attributes inherited from Transform
const Input & input
Protected Attributes inherited from Input
unsigned int N
double T
Detailed Description
Defines a discrete-time recurrent input/output transform.
Definition at line 2 of file RecurrentTransform.hpp.
Constructor & Destructor Documentation
RecurrentTransform() [1/2]
RecurrentTransform::RecurrentTransform (const RecurrentTransform & transform)
Definition at line 3 of file RecurrentTransform.cpp.
RecurrentTransform() [2/2]
RecurrentTransform::RecurrentTransform (unsigned int N, unsigned int R, const Input & input)
Resets the transform for the given parameters.
Parameters
N The number of output units, defined unit indexes stand in {0, N{.
R The maximal recurrent time range, at a current time t, defined times stand in [t+0, t+R[.
input The transform input.
Definition at line 4 of file RecurrentTransform.cpp.
References reset().
~RecurrentTransform()
RecurrentTransform::~RecurrentTransform () virtual
Definition at line 8 of file RecurrentTransform.cpp.
Member Function Documentation
reset()
network::RecurrentTransform & RecurrentTransform::reset (bool buffered = false)
Resets the transform buffering.
The current time is reset to 0.
Parameters
buffered If true all input.getT() are buffered, else only R+1 are buffered.
Returns
this.
Definition at line 12 of file RecurrentTransform.cpp.
References Input::getT(), Transform::input, L, Input::N, and R.
Referenced by RecurrentTransform(), and KernelEstimator::~KernelEstimator().
getR()
unsigned int RecurrentTransform::getR () const
Gets the maximal recuurent range.
Definition at line 25 of file RecurrentTransform.hpp.
References R.
get()
double RecurrentTransform::get (unsigned int n, double t) const virtual
Returns the input value.
The method is to be overwritten to implement a given input.
Parameters
n The input unit index.
t The value time.
Returns
The input value if defined, else raises a fatal error.
Reimplemented from Input.
Definition at line 23 of file RecurrentTransform.cpp.
References assume(), getValue(), L, and Input::N.
Referenced by KernelEstimator::~KernelEstimator().
getValue()
virtual double RecurrentTransform::getValue (unsigned int n, double t) const virtual
Implements the discrete-time recurrent equation.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Returns
The input value if defined, else raises a fatal error.
It calculates ,
Reimplemented in KernelTransform.
Definition at line 40 of file RecurrentTransform.hpp.
References assume().
Referenced by get().
getValueDerivative()
virtual double RecurrentTransform::getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const virtual
Implements the discrete-time recurrent equation derivative.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Parameters
n_ The input unit index denominator.
t_ The value time denominator.
Returns
The input value derivate if defined, 0 in the abscence of dependence, else raises a fatal error.
If the recurrent equation writes , this method returns: ,
Reimplemented in KernelTransform.
Definition at line 58 of file RecurrentTransform.hpp.
References assume().
Member Data Documentation
R
unsigned int RecurrentTransform::R protected
Definition at line 6 of file RecurrentTransform.hpp.
Referenced by getR(), and reset().
L
unsigned int RecurrentTransform::L protected
Definition at line 6 of file RecurrentTransform.hpp.
Referenced by get(), and reset().
mnemosyne brainybot (version of 2017-06-05 at 15:48:38)