Mnemonas'semiware: network::Input Class Reference
network::Input Class Reference
Defines the input of a calculation network.
#include <Input.hpp>
Public Member Functions
Input (unsigned int N, double T)
Resets the input dimensions.
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
virtual double get (unsigned int n, double t) const
Returns the input value.
Protected Attributes
unsigned int N
double T
Detailed Description
Defines the input of a calculation network.
Definition at line 3 of file Input.hpp.
Constructor & Destructor Documentation
Input()
network::Input::Input (unsigned int N, double T)
Resets the input dimensions.
Parameters
N The number of input units, defined unit indexes stand in {0, N{.
T The maximal time range, defined times stand in [0, T[.
Definition at line 3 of file Input.cpp.
Member Function Documentation
getN()
unsigned int network::Input::getN () const
Gets the number of input units.
Definition at line 17 of file Input.hpp.
References N.
Referenced by network::RecurrentTransform::asString(), network::SupervisedCriterion::drho(), network::SupervisedCriterion::get(), network::TransformCriterion::get(), network::ObservableCriterion::get(), network::LinearTransform::getKernelDerivative(), network::LinearTransform::getKernelDimension(), network::SoftMaxTransform::getKernelDimension(), network::LinearNonLinearTransform::getKernelDimension(), network::IntegrateAndFireTransform::getKernelDimension(), network::LinearTransform::getKernelValue(), network::SoftMaxTransform::getKernelValue(), network::LinearNonLinearTransform::getKernelValue(), network::IntegrateAndFireTransform::getKernelValue(), network::SupervisedCriterion::getN0(), network::TransformCriterion::getN0(), network::TransformCriterion::rho(), network::SupervisedCriterion::rho(), network::ObservableCriterion::rho(), network::LinearTransform::setWeights(), network::SoftMaxTransform::setWeights(), network::LinearNonLinearTransform::setWeights(), network::IntegrateAndFireTransform::setWeights(), network::TransformCriterion::update(), and network::ObservableCriterion::update().
getT()
double network::Input::getT () const
Gets the maximal time range.
Definition at line 22 of file Input.hpp.
References T.
Referenced by network::RecurrentTransform::asString(), network::ObservableCriterion::ObservableCriterion(), network::RecurrentTransform::reset(), network::TransformCriterion::rho(), network::ObservableCriterion::rho(), network::TransformCriterion::update(), and network::ObservableCriterion::update().
get()
double network::Input::get (unsigned int n, double t) const virtual
Returns the input value.
The method is to be overwritten to implement a given input.
Parameters
n The input unit index.
t The value time.
Returns
The input value if defined, else raises a fatal error.
Reimplemented in network::BufferedInput, and network::RecurrentTransform.
Definition at line 4 of file Input.cpp.
References assume().
Referenced by network::BufferedInput::BufferedInput(), network::SupervisedCriterion::drho(), network::SupervisedCriterion::get(), network::LinearTransform::getKernelValue(), network::SoftMaxTransform::getKernelValue(), network::LinearNonLinearTransform::getKernelValue(), network::IntegrateAndFireTransform::getKernelValue(), and network::SupervisedCriterion::rho().
Member Data Documentation
N
unsigned int network::Input::N protected
Definition at line 5 of file Input.hpp.
Referenced by network::BufferedInput::add(), network::RecurrentTransform::asString(), network::KernelTransform::asString(), network::BufferedInput::BufferedInput(), network::RecurrentTransform::get(), network::BufferedInput::get(), network::BufferedInput::getHistogram(), network::LinearTransform::getKernelDerivative(), network::LinearTransform::getKernelValue(), network::RecurrentTransform::getLyapunovExponent(), getN(), network::RecurrentTransform::getValueDerivativeApproximation(), network::RecurrentTransform::reset(), network::KernelTransform::resetWeights(), network::BufferedInput::save(), network::RecurrentTransform::set(), network::LinearTransform::setOffset(), network::KernelTransform::setWeight(), and network::KernelTransform::setWeightsRandom().
T
double network::Input::T protected
Definition at line 6 of file Input.hpp.
Referenced by network::BufferedInput::add(), network::BufferedInput::BufferedInput(), network::BufferedInput::get(), network::BufferedInput::getHistogram(), network::RecurrentTransform::getLyapunovExponent(), getT(), and network::BufferedInput::save().
The documentation for this class was generated from the following files:
src/network/Input.hpp
src/network/Input.cpp
mnemosyne brainybot (version of 2018-01-23 at 18:51:12)