Mnemonas'semiware: Experimentation::ResultTable Class Reference
Experimentation::ResultTable Class Reference
Encapsulates an exponential decay fit latex result table construction.
#include <Experimentation.h>
Public Member Functions
ResultTable (String param, String param2, String what, String name, bool with_decay_and_bias=true)
Constructs the result table.
void add (String v, const ExponentialDecayFit &fit)
Adds a value.
void add (double v, const ExponentialDecayFit &fit)
void add2 (double v1, double v2, const ExponentialDecayFit &fit)
Adds two values.
void add (double v)
Adds an empty value.
void save (String filename) const
Saves the table in a latex file.
Detailed Description
Encapsulates an exponential decay fit latex result table construction.
Definition at line 53 of file Experimentation.h.
Constructor & Destructor Documentation
ResultTable()
Experimentation::ResultTable::ResultTable (String param, String param2, String what, String name, bool with_decay_and_bias = true)
Constructs the result table.
Parameters
param The variable parameter name, e.g., "Number of units".
param2 A 2nd optional variable parameter name, e.g., "Number of units".
what The table title parameter name, e.g., "Node type".
name The table title parameter name, e.g., "LinearTransform".
with_decay_and_bias Whether exponential fit decay and bias is to be shown or not.
Definition at line 65 of file Experimentation.h.
Member Function Documentation
add() [1/3]
void Experimentation::ResultTable::add (String v, const ExponentialDecayFit & fit)
Adds a value.
Parameters
v The variable parameter corresponding value.
fit The related exponential decy fit.
Definition at line 71 of file Experimentation.h.
References ExponentialDecayFit::getBias(), ExponentialDecayFit::getCount(), ExponentialDecayFit::getDecay(), ExponentialDecayFit::getMinimalValue(), and s_printf().
Referenced by add(), add2(), Experimentation::run_reverse_engineering(), Experimentation::run_reverse_engineering_variability(), Experimentation::run_robust_criterion(), and Experimentation::run_sequence_generation().
add() [2/3]
void Experimentation::ResultTable::add (double v, const ExponentialDecayFit & fit)
Definition at line 81 of file Experimentation.h.
References add(), and s_printf().
add2()
void Experimentation::ResultTable::add2 (double v1, double v2, const ExponentialDecayFit & fit)
Adds two values.
Parameters
v1 The 1st variable parameter corresponding value.
v2 The 2nd variable parameter corresponding value.
fit The related exponential decy fit.
Definition at line 90 of file Experimentation.h.
References add(), and s_printf().
Referenced by Experimentation::run_sequence_generation().
add() [3/3]
void Experimentation::ResultTable::add (double v)
Adds an empty value.
Parameters
v The variable parameter corresponding value.
Definition at line 98 of file Experimentation.h.
References s_printf().
save()
void Experimentation::ResultTable::save (String filename) const
Saves the table in a latex file.
Parameters
filename The latex file name.
Definition at line 107 of file Experimentation.h.
References s_printf(), and s_save().
Referenced by Experimentation::run_reverse_engineering(), Experimentation::run_reverse_engineering_variability(), Experimentation::run_robust_criterion(), and Experimentation::run_sequence_generation().
mnemosyne brainybot (version of 2017-10-15 at 10:00:56)