Mnemonas'semiware: Experimentation Class Reference
Experimentation Class Reference
#include <Experimentation.h>
Classes
class ResultTable
Encapsulates an exponential decay fit latex result table construction.
Public Member Functions
Experimentation ()
~Experimentation ()
bool file_tobedone (String filename)
Checks if the file already exists.
network::KernelTransform * newKernelTransform (String test, String type, unsigned int N, const network::Input &input, bool root=false)
Returns a new kernel transform adapated to the given test.
void set_reverse_engineering_inoutput (String type, unsigned int N, unsigned int seed=0)
Generates a reverse engineering input/output sequence.
void set_noisy_inoutput (unsigned int N, double noiseProbability, double noiseStandardDeviation)
Generates a noisy LinearNonLinearTransform reverse engineering input/output sequence.
void set_sequence_inoutput (String name, String type, unsigned int N, unsigned int T)
Generates an output sequence, without input.
void do_supervised_estimation (String test, String type, char criterion, unsigned int N, String mode="reproducible", double criterion_epsilon=1e-6, unsigned int maxIterations=100, bool reinject=true)
Performs a supervised estimation, if the related file does not exist.
void initReuse ()
Resets before weights reuse.
void run_reverse_engineering (String type="")
Runs the {reverse-engineering} experiments.
void run_reverse_engineering_variability ()
Runs the {reverse-engineering-variability} experiment.
void run_robust_criterion (String what="")
Runs the {robust-criterion} experiment.
unsigned int run_sequence_generation (String name, String type, char criterion, unsigned int N, unsigned int T)
Runs a sequence generation experiment.
void run_sequence_generation (String name, String type, char criterion)
Runs a sequence generation experiment.
void run_sequence_generation ()
Runs the {sequence-generation} experiment.
void run (Struct what="{}")
Runs all experiments.
Detailed Description
Definition at line 2 of file Experimentation.h.
Constructor & Destructor Documentation
Experimentation()
Experimentation::Experimentation ()
Definition at line 10 of file Experimentation.h.
~Experimentation()
Experimentation::~Experimentation ()
Definition at line 11 of file Experimentation.h.
Member Function Documentation
file_tobedone()
bool Experimentation::file_tobedone (String filename)
Checks if the file already exists.
Parameters
filename The file name.
Definition at line 20 of file Experimentation.h.
Referenced by run_reverse_engineering(), run_reverse_engineering_variability(), run_robust_criterion(), and run_sequence_generation().
newKernelTransform()
network::KernelTransform* Experimentation::newKernelTransform (String test, String type, unsigned int N, const network::Input & input, bool root = false)
Returns a new kernel transform adapated to the given test.
Parameters
test The test to perform: "reverse_engineering", "sequence_generation".
type The nodes type: "LinearTransform", "LinearNonLinearTransform", "SparseNonLinearTransform", "SoftMaxTransform", "IntegrateAndFireTransform"
N The number of state units.
input The transform input.
root If true generates a reverse_engineering root network.
Definition at line 31 of file Experimentation.h.
Referenced by do_supervised_estimation(), set_noisy_inoutput(), and set_reverse_engineering_inoutput().
set_reverse_engineering_inoutput()
void Experimentation::set_reverse_engineering_inoutput (String type, unsigned int N, unsigned int seed = 0)
Generates a reverse engineering input/output sequence.
Parameters
type The nodes type.
N The number of state units.
seed Specifies if the pseudo-random sequence is reproducible (using same value at each call) or not.
Definition at line 129 of file Experimentation.h.
References newKernelTransform(), and s_printf().
Referenced by run_reverse_engineering(), and run_reverse_engineering_variability().
set_noisy_inoutput()
void Experimentation::set_noisy_inoutput (unsigned int N, double noiseProbability, double noiseStandardDeviation)
Generates a noisy LinearNonLinearTransform reverse engineering input/output sequence.
Parameters
N The number of state units.
noiseProbability The probability to add noise to a given value.
noiseStandardDeviation The standard deviation of the normal added noise.
Definition at line 145 of file Experimentation.h.
References newKernelTransform(), and s_printf().
Referenced by run_robust_criterion().
set_sequence_inoutput()
void Experimentation::set_sequence_inoutput (String name, String type, unsigned int N, unsigned int T)
Generates an output sequence, without input.
Parameters
name The related sequence name.
type The related nodes type.
N The number of state units.
T The number of samples.
Definition at line 163 of file Experimentation.h.
References s_printf().
Referenced by run_sequence_generation().
do_supervised_estimation()
void Experimentation::do_supervised_estimation (String test, String type, char criterion, unsigned int N, String mode = "reproducible", double criterion_epsilon = 1e-6, unsigned int maxIterations = 100, bool reinject = true)
Performs a supervised estimation, if the related file does not exist.
Parameters
test The test to perform: "reverse_engineering", "sequence_generation".
type The nodes type: "LinearTransform", "LinearNonLinearTransform", "SparseNonLinearTransform", "SoftMaxTransform", "IntegrateAndFireTransform"
criterion The used criterion : '2', '1', '0', 'a', 'b', 'h'.
N The number of state units.
mode The input generation mode : "reuse" of previous estimation weights, "reproducible", or not.
criterion_epsilon The precision on the state values.
maxIterations The maximal number of iteration.
reinject If true, uses the desired value in the 2nd order criterion estimation.
Definition at line 181 of file Experimentation.h.
References newKernelTransform(), and s_printf().
Referenced by run_reverse_engineering(), run_reverse_engineering_variability(), run_robust_criterion(), and run_sequence_generation().
initReuse()
void Experimentation::initReuse ()
Resets before weights reuse.
Definition at line 198 of file Experimentation.h.
Referenced by run_sequence_generation().
run_reverse_engineering()
void Experimentation::run_reverse_engineering (String type = "")
Runs the {reverse-engineering} experiments.
Parameters
type The related node type.
Definition at line 206 of file Experimentation.h.
References Experimentation::ResultTable::add(), do_supervised_estimation(), file_tobedone(), s_printf(), Experimentation::ResultTable::save(), and set_reverse_engineering_inoutput().
Referenced by run().
run_reverse_engineering_variability()
void Experimentation::run_reverse_engineering_variability ()
Runs the {reverse-engineering-variability} experiment.
Definition at line 227 of file Experimentation.h.
References Experimentation::ResultTable::add(), do_supervised_estimation(), file_tobedone(), s_printf(), Experimentation::ResultTable::save(), and set_reverse_engineering_inoutput().
Referenced by run().
run_robust_criterion()
void Experimentation::run_robust_criterion (String what = "")
Runs the {robust-criterion} experiment.
Parameters
what The experiment name : "noise" or "outiers" or both.
Definition at line 243 of file Experimentation.h.
References Experimentation::ResultTable::add(), do_supervised_estimation(), file_tobedone(), s_printf(), Experimentation::ResultTable::save(), and set_noisy_inoutput().
Referenced by run().
run_sequence_generation() [1/3]
unsigned int Experimentation::run_sequence_generation (String name, String type, char criterion, unsigned int N, unsigned int T)
Runs a sequence generation experiment.
Definition at line 275 of file Experimentation.h.
References do_supervised_estimation(), s_printf(), s_save(), and set_sequence_inoutput().
run_sequence_generation() [2/3]
void Experimentation::run_sequence_generation (String name, String type, char criterion)
Runs a sequence generation experiment.
Definition at line 304 of file Experimentation.h.
References Experimentation::ResultTable::add(), Experimentation::ResultTable::add2(), file_tobedone(), initReuse(), run_sequence_generation(), s_printf(), and Experimentation::ResultTable::save().
run_sequence_generation() [3/3]
void Experimentation::run_sequence_generation ()
Runs the {sequence-generation} experiment.
Definition at line 329 of file Experimentation.h.
Referenced by run(), and run_sequence_generation().
run()
void Experimentation::run (Struct what = "{}")
Runs all experiments.
Definition at line 340 of file Experimentation.h.
References assume(), Struct::get(), Struct::getLength(), Struct::INT_NAN, Struct::reset(), run_reverse_engineering(), run_reverse_engineering_variability(), run_robust_criterion(), and run_sequence_generation().
Referenced by main().
mnemosyne brainybot (version of 2017-10-15 at 10:00:56)