Mnemonas'semiware: CurveFit Class Reference
CurveFit Class Reference
Fits an on-the-fly model on a time series.
#include <CurveFit.hpp>
Public Member Functions
void clear ()
Clears the estimation.
void add (double c)
Adds a value in sequence.
unsigned int getCount () const
Gets the number of samples.
double getDecay () const
Gets the exponential decay or NAN if undefined.
double getGain () const
Gets the best model gain or 0 NAN in undefined.
double getBias () const
Gets the best model bias .
double getError () const
Gets the best model average L1 error.
double getGamma () const
Gets the best model gamma filtering.
char getMode () const
Gets the best model mode.
std::string asString () const
Returns the parameters as a JSON string.
void show (String file, bool show=false) const
Plots the observed and modeled curve in a file.
const Histogram getHistogram () const
Returns the value statistics.
Detailed Description
Fits an on-the-fly model on a time series.
The present implementation considers a constant, affine or exponential model triplet of the a time series writing : on a sliding exponential window of width where is the fraction of data average within this window, which is automatically adjusted.
Definition at line 14 of file CurveFit.hpp.
Member Function Documentation
clear()
void CurveFit::clear ()
Clears the estimation.
Definition at line 28 of file CurveFit.cpp.
Referenced by network::KernelExperimentalEstimator::run().
add()
void CurveFit::add (double c)
Adds a value in sequence.
Parameters
c The value to add in sequence, i.e., at time 0, 1, 2, ...
Definition at line 41 of file CurveFit.cpp.
References solver::minimize().
Referenced by network::KernelDistributedEstimator::run(), network::KernelExperimentalEstimator::run(), and network::KernelEstimator::run().
getCount()
unsigned int CurveFit::getCount () const
Gets the number of samples.
Definition at line 40 of file CurveFit.hpp.
Referenced by asString().
getDecay()
double CurveFit::getDecay () const
Gets the exponential decay or NAN if undefined.
Definition at line 45 of file CurveFit.hpp.
Referenced by asString(), and show().
getGain()
double CurveFit::getGain () const
Gets the best model gain or 0 NAN in undefined.
Definition at line 50 of file CurveFit.hpp.
Referenced by asString(), and show().
getBias()
double CurveFit::getBias () const
Gets the best model bias .
Definition at line 55 of file CurveFit.hpp.
Referenced by asString(), and show().
getError()
double CurveFit::getError () const
Gets the best model average L1 error.
Definition at line 60 of file CurveFit.hpp.
Referenced by asString().
getGamma()
double CurveFit::getGamma () const
Gets the best model gamma filtering.
Definition at line 65 of file CurveFit.hpp.
Referenced by asString().
getMode()
char CurveFit::getMode () const
Gets the best model mode.
Returns 'c' for constant model, 'a' for an affine model and 'e' for an exponential model.
Definition at line 72 of file CurveFit.hpp.
References asString(), getHistogram(), and show().
Referenced by asString().
asString()
std::string CurveFit::asString () const
Returns the parameters as a JSON string.
Definition at line 131 of file CurveFit.cpp.
References getBias(), getCount(), getDecay(), getError(), getGain(), getGamma(), getMode(), and s_printf().
Referenced by getMode(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), and network::KernelExperimentalEstimator::run().
show()
void CurveFit::show (String file, bool show = false) const
Plots the observed and modeled curve in a file.
Parameters
file The file name, a gnuplot display data, script and image files are generated, with extensions .dat, .gnuplot.sh and .png.
show If true performs on the fly display.
Definition at line 142 of file CurveFit.cpp.
References getBias(), getDecay(), getGain(), gnuplot(), s_printf(), and s_save().
Referenced by getMode(), and network::KernelExperimentalEstimator::run().
getHistogram()
const Histogram CurveFit::getHistogram () const
Returns the value statistics.
Definition at line 161 of file CurveFit.cpp.
References Histogram::add().
Referenced by getMode().
The documentation for this class was generated from the following files:
src/util/CurveFit.hpp
src/util/CurveFit.cpp
mnemosyne brainybot (version of 2018-06-18 at 08:27:55)