Mnemonas'semiware: network::TransformCriterion Class Reference
network::TransformCriterion Class Reference
Defines a transform critrion.
#include <TransformCriterion.hpp>
Public Member Functions
TransformCriterion (RecurrentTransform &transform)
Resets the estimator for a given kernel transform.
virtual double rho () const
Defines the estimator criterion.
virtual double rho (unsigned int n, double t) const
Defines the estimator criterion.
virtual double drho (unsigned int n, double t) const
Defines the estimator criterion derivative.
virtual void update ()
Updates the best previous estimated value.
virtual double get (unsigned int n, double t) const
Gets the best previous estimated value.
virtual unsigned int getN0 () const
Gets the best previous estimated value number of units.
Protected Attributes
RecurrentTransform & transform
Detailed Description
Defines a transform critrion.
Definition at line 3 of file TransformCriterion.hpp.
Constructor & Destructor Documentation
TransformCriterion()
network::TransformCriterion::TransformCriterion (RecurrentTransform & transform)
Resets the estimator for a given kernel transform.
Parameters
transform The kernel transform to estimate.
The recurrent transform is fully buffered fo the estimation purpose.
Definition at line 3 of file TransformCriterion.cpp.
Member Function Documentation
rho() [1/2]
double network::TransformCriterion::rho () const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a global estimator.
The default implementation simply returns , running:
double r = 0;
transform.reset(true);
for(unsigned int t = 0; t < transform.T; t++)
  for(int n =  transform.N - 1; 0 <= n; n--)
     r += rho(n, t, transform.get(n, t));
return r / (transform.N *  transform.T);
Returns
The criterion value to mnimize.
Reimplemented in network::ObservableCriterion.
Definition at line 12 of file TransformCriterion.cpp.
References assume(), network::Input::N, network::RecurrentTransform::reset(), network::Input::T, and transform.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), network::KernelEstimator::run(), and network::KernelEstimator::updateReadout().
rho() [2/2]
double network::TransformCriterion::rho (unsigned int n, double t) const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a local estimator.
A typical implementation is of the form:
double network::MyCriterion::rho(unsigned int n, double t) const {
 double value = transform.get(n, t);
 ../..
Parameters
n The input unit index.
t The value time.
Returns
The related positive value to minimize.
Reimplemented in network::SupervisedCriterion.
Definition at line 25 of file TransformCriterion.cpp.
References assume().
drho()
double network::TransformCriterion::drho (unsigned int n, double t) const virtual
Defines the estimator criterion derivative.
The method is to be overwritten to implement a given estimator.
Parameters
n The input unit index.
t The value time.
Returns
The value derivative .
Reimplemented in network::ObservableCriterion, and network::SupervisedCriterion.
Definition at line 30 of file TransformCriterion.cpp.
References assume().
Referenced by network::KernelEstimator::run().
update()
void network::TransformCriterion::update () virtual
Updates the best previous estimated value.
This routine is called after backward tuning, and weight adjustment.
Reimplemented in network::ObservableCriterion, and network::SupervisedCriterion.
Definition at line 43 of file TransformCriterion.cpp.
References network::RecurrentTransform::get(), getN0(), network::RecurrentTransform::getR(), network::RecurrentTransform::getValueDerivative(), network::Input::N, network::RecurrentTransform::reset(), network::RecurrentTransform::set(), network::Input::T, and transform.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), network::SupervisedCriterion::update(), and network::ObservableCriterion::update().
get()
double network::TransformCriterion::get (unsigned int n, double t) const virtual
Gets the best previous estimated value.
The method is to be overwritten if output values can be provided.
Parameters
n The input unit index in {0,N{.
t The value time.
Returns
The best previous estimated value or NAN if undefined.
Reimplemented in network::ObservableCriterion, and network::SupervisedCriterion.
Definition at line 35 of file TransformCriterion.cpp.
References network::Input::N, and transform.
Referenced by network::SupervisedCriterion::get(), network::KernelEstimator::getValue(), and network::KernelEstimator::updateReadout().
getN0()
unsigned int network::TransformCriterion::getN0 () const virtual
Gets the best previous estimated value number of units.
Returns
The number of units for which a best previous estimated value is defined.
Reimplemented in network::ObservableCriterion, and network::SupervisedCriterion.
Definition at line 39 of file TransformCriterion.cpp.
References network::Input::N, and transform.
Referenced by network::SupervisedCriterion::getN0(), network::KernelEstimator::getValue(), update(), and network::KernelEstimator::updateReadout().
Member Data Documentation
transform
RecurrentTransform& network::TransformCriterion::transform protected
Definition at line 5 of file TransformCriterion.hpp.
Referenced by network::SupervisedCriterion::drho(), network::ObservableCriterion::get(), get(), getN0(), rho(), network::SupervisedCriterion::rho(), network::ObservableCriterion::rho(), network::ObservableCriterion::update(), and update().
The documentation for this class was generated from the following files:
src/network/TransformCriterion.hpp
src/network/TransformCriterion.cpp
mnemosyne brainybot (version of 2018-02-25 at 13:17:37)