Mnemonas'semiware: Struct Class Reference
Struct Class Reference
Implements a generic minimal iterative structure.
#include <Struct.hpp>
Scalar value implementation
static const Struct EMPTY
Defines a empty struct, for initialization.
bool isAtomic () const
Returns true if this corresponds to a scalar (boolean, numeric, string) value and false otherwise.
bool isEmpty () const
Returns true if this corresponds to an empty scalar value corresponding to the empty string and false otherwise.
void nop () const
A no operation method, just used to avoid compilation warning in empty callbacks.
Scalar value casting
static const int INT_NAN = INT_MIN
The 0x10000000 (INT_MIN) undefined int value.
operator String () const
Returns this value as a string or the empty string if undefined.
Struct (String value)
Struct (const char *value)
Struct (char value)
operator char () const
Returns the the 1st string char, as data or '\0' is the string is empty.
operator bool () const
Returns true if the value is "true", false otherwise.
Struct (bool value)
operator double () const
Returns the data as a floating point number or NAN if undefined.
Struct (double value)
operator int () const
Returns the data as an int or 0x10000000 (INT_NAN) if undefined.
operator unsigned int () const
Struct (int value)
Struct (unsigned int value)
static double toDouble (String value)
Converts a string to a numeric value.
Container value read
Struct & get (String name, Struct value)
Returns the reference to a named or indexed value.
Struct & get (String name) const
Struct & get (int index) const
Struct & get (int index, Struct value)
Struct & operator[] (String name) const
Struct & operator[] (const char *name) const
Struct & operator[] (int index) const
bool isEmpty (String name) const
Returns true the related value is undefined or corresponds to the empty string and false otherwise.
bool isEmpty (int index) const
const std::vector< std::string > & getNames ()
Returns the field names, in order to define an iterator over the struct.
int getLength () const
Returns the maximal indexed value in the structure.
int getCount () const
Returns the number of named value in the structure.
Container value write
Struct & set (String name, const Struct &value)
Sets a named or indexed value.
Struct & set (int index, const Struct &value)
Struct & set (String name)
Struct & set (int index)
Struct & add (const Struct &value)
Appends an indexed value.
Struct & unset (String name)
Erases a named or indexed value.
Struct & unset (int index)
Copy and equality operator
Struct (const Struct &value)
Copies a data structure.
Struct & operator= (const Struct &value)
bool equals (const Struct &value) const
Returns true if this structure equals the comparing one.
bool operator== (const Struct &value) const
bool operator!= (const Struct &value) const
String input/output interface
void save (String location, String format="raw") const
Saves the data structure as a JSON string, in a file.
std::string asString (String format="raw", unsigned int depth=0) const
Returns the data structure as a a JSON string.
void reset (const char *value,...)
Resets the data structure from a JSON weak-syntax string.
void reset (String value="")
Struct (int argc, const char *argv[])
Resets the data structure from the main() program interface.
void load (String location)
Resets the data structure from a JSON weak-syntax string stored in a file.
Detailed Description
Implements a generic minimal iterative structure.
Such a value corresponds to:
scalar values: boolean, number, or string;
value list, indexed from 0, written [value, ...];
parameter set, written {name = value, ...}. Key properties of such data structure:
They corresponds to JSON structures (i.e. correspond to a data object model).
By construction (value copy when set), they can neither be cyclic (i.e. and infinite tree with a leaf linked to an ancestor), nor have common branches (i.e. two Struct instance sharing the same value in memory).
When a named parameter is set, the previous scalar value if any is erased, while the previous ordered list of value is now considered as value indexed by number converted as name.
Definition at line 30 of file Struct.hpp.
Constructor & Destructor Documentation
Struct() [1/9]
Struct::Struct (String value)
Definition at line 32 of file Struct.cpp.
Referenced by reset(), and unset().
Struct() [2/9]
Struct::Struct (const char * value)
Definition at line 37 of file Struct.cpp.
Struct() [3/9]
Struct::Struct (char value)
Definition at line 42 of file Struct.cpp.
Struct() [4/9]
Struct::Struct (bool value)
Definition at line 72 of file Struct.cpp.
Struct() [5/9]
Struct::Struct (double value)
Definition at line 81 of file Struct.cpp.
Struct() [6/9]
Struct::Struct (int value)
Definition at line 96 of file Struct.cpp.
Struct() [7/9]
Struct::Struct (unsigned int value)
Definition at line 101 of file Struct.cpp.
References INT_NAN.
Struct() [8/9]
Struct::Struct (const Struct & value)
Copies a data structure.
Definition at line 22 of file Struct.cpp.
Struct() [9/9]
Struct::Struct (int argc, const char * argv[])
Resets the data structure from the main() program interface.
Application parameters are defined viawith a syntax of the form:
program [-name [[-] ? value ..]*]*
where name is the parameters name with zero or more values the - allowing to escape values starting with the - char.
It is used in a construct of the form:
int main(int argc, const char* argv[]) {
  Struct args(argc, argv);
  . . / . .
  return EXIT_SUCCESS;
}
Parameters
argc The number of arguments.
argv The arguments.
Definition at line 532 of file Struct.cpp.
References reset().
Member Function Documentation
isAtomic()
bool Struct::isAtomic () const
Returns true if this corresponds to a scalar (boolean, numeric, string) value and false otherwise.
Definition at line 40 of file Struct.hpp.
Referenced by asString(), and equals().
isEmpty() [1/3]
bool Struct::isEmpty () const
Returns true if this corresponds to an empty scalar value corresponding to the empty string and false otherwise.
Definition at line 45 of file Struct.hpp.
Referenced by asString(), get(), isEmpty(), and toDouble().
nop()
void Struct::nop () const
A no operation method, just used to avoid compilation warning in empty callbacks.
Definition at line 50 of file Struct.hpp.
operator String()
Struct::operator String () const
Returns this value as a string or the empty string if undefined.
Returns
Either
The string representation of the value if the data is atomic (i.e. corresponds to a boolean, number, or string), or
The strict JSON syntax representation of this data-structure.
Definition at line 26 of file Struct.cpp.
References asString().
operator char()
Struct::operator char () const
Returns the the 1st string char, as data or '\0' is the string is empty.
Definition at line 47 of file Struct.cpp.
operator bool()
Struct::operator bool () const
Returns true if the value is "true", false otherwise.
A numerical value of 0 stands for false and a non-zero numerical value stands for true.
Returns
The boolean true value if the value is neither empty nor the string "false", "False" or "FALSE".
Definition at line 52 of file Struct.cpp.
References toDouble().
operator double()
Struct::operator double () const
Returns the data as a floating point number or NAN if undefined.
Definition at line 77 of file Struct.cpp.
References toDouble().
toDouble()
double Struct::toDouble (String value) static
Converts a string to a numeric value.
This also allows to detect via the std::isnan(Struct::toDouble(value)) constuct if a value is convertible to a numeric value.
Parameters
value The value to convert.
Returns
The value as a double, or NAN if not parsable.
Definition at line 112 of file Struct.cpp.
References assume(), EMPTY, INT_NAN, and isEmpty().
Referenced by operator bool(), operator double(), operator int(), and operator unsigned int().
operator int()
Struct::operator int () const
Returns the data as an int or 0x10000000 (INT_NAN) if undefined.
Definition at line 86 of file Struct.cpp.
References INT_NAN, and toDouble().
operator unsigned int()
Struct::operator unsigned int () const
Definition at line 91 of file Struct.cpp.
References INT_NAN, and toDouble().
get() [1/4]
Struct & Struct::get (String name, Struct value)
Returns the reference to a named or indexed value.
Also available though the struct[name] subscript operator.
Parameters
name The name or the index of the value.
value The default value, if the field is empty. The value is set in the data structure.
Returns
A reference to the value, creating this entry if not yet defined.
Definition at line 226 of file Struct.cpp.
References isEmpty().
Referenced by asString().
get() [2/4]
Struct & Struct::get (String name) const
Definition at line 232 of file Struct.cpp.
get() [3/4]
Struct& Struct::get (int index) const
Definition at line 144 of file Struct.hpp.
get() [4/4]
Struct& Struct::get (int index, Struct value)
Definition at line 148 of file Struct.hpp.
operator[]() [1/3]
Struct& Struct::operator[] (String name) const
Definition at line 153 of file Struct.hpp.
operator[]() [2/3]
Struct& Struct::operator[] (const char * name) const
Definition at line 156 of file Struct.hpp.
operator[]() [3/3]
Struct& Struct::operator[] (int index) const
Definition at line 159 of file Struct.hpp.
isEmpty() [2/3]
bool Struct::isEmpty (String name) const
Returns true the related value is undefined or corresponds to the empty string and false otherwise.
Parameters
name The name or the index of the value.
Definition at line 167 of file Struct.hpp.
References isEmpty().
isEmpty() [3/3]
bool Struct::isEmpty (int index) const
Definition at line 171 of file Struct.hpp.
References isEmpty().
getNames()
const std::vector< std::string >& Struct::getNames ()
Returns the field names, in order to define an iterator over the struct.
It is used in a construct of the form:
for(std::vector < std::string >::const_iterator i = struct.getNames().begin(); i != struct.getNames().end(); i++) {
  String name = *i;
  ../..
}
or:
const std::vector < std::string >& names = struct.getNames();
for(unsigned int i = 0; i < names.size(); i++) {
  String name = names[i];
  ../..
}
It does not iterate over the indexed struct elements, which is realized with getLength().
Definition at line 191 of file Struct.hpp.
getLength()
int Struct::getLength () const
Returns the maximal indexed value in the structure.
It is used in a construct of the form:
for(int i = 0; i < value.getLength(); i++) {
  Struct &value = value.get(i); ../..
}
Definition at line 202 of file Struct.hpp.
Referenced by add(), asString(), and reset().
getCount()
int Struct::getCount () const
Returns the number of named value in the structure.
Definition at line 207 of file Struct.hpp.
Referenced by asString().
set() [1/4]
Struct & Struct::set (String name, const Struct & value)
Sets a named or indexed value.
Also available though the struct[name] = value assignment/subscript operators.
Parameters
name The name or the index of the value.
value The value to set.
Definition at line 238 of file Struct.cpp.
Referenced by reset().
set() [2/4]
Struct& Struct::set (int index, const Struct & value)
Definition at line 221 of file Struct.hpp.
set() [3/4]
Struct& Struct::set (String name)
Definition at line 225 of file Struct.hpp.
set() [4/4]
Struct& Struct::set (int index)
Definition at line 229 of file Struct.hpp.
add()
Struct& Struct::add (const Struct & value)
Appends an indexed value.
Definition at line 234 of file Struct.hpp.
References getLength().
Referenced by reset().
unset() [1/2]
Struct& Struct::unset (String name)
Erases a named or indexed value.
Definition at line 239 of file Struct.hpp.
Referenced by unset().
unset() [2/2]
Struct& Struct::unset (int index)
Definition at line 244 of file Struct.hpp.
References Struct(), and unset().
operator=()
Struct& Struct::operator= (const Struct & value)
Definition at line 256 of file Struct.hpp.
References equals().
equals()
bool Struct::equals (const Struct & value) const
Returns true if this structure equals the comparing one.
Also available via the == and != operators.
Definition at line 244 of file Struct.cpp.
References equals(), and isAtomic().
Referenced by equals(), operator!=(), operator=(), and operator==().
operator==()
bool Struct::operator== (const Struct & value) const
Definition at line 267 of file Struct.hpp.
References equals().
operator!=()
bool Struct::operator!= (const Struct & value) const
Definition at line 270 of file Struct.hpp.
References asString(), equals(), reset(), and save().
save()
void Struct::save (String location, String format = "raw") const
Saves the data structure as a JSON string, in a file.
Parameters
location The file path.
If "stdout" / "stderr", prints the data in the console as stdout or stderr stream.
format The output format:
"raw" : 1D raw compact JSON format with minimal space.
"plain" : 2D human editable JSON format with tabulation.
"html" : HTML human readable JSON format.
"jplain" : human readable J= format.
"jhtml" : HTML human readable J= format.
Definition at line 765 of file Struct.cpp.
References asString(), and s_save().
Referenced by operator!=().
asString()
std::string Struct::asString (String format = "raw", unsigned int depth = 0) const
Returns the data structure as a a JSON string.
Parameters
format The output format:
"raw" : 1D raw compact format with minimal space.
"plain" : 2D human editable format with tabulation.
"html" : HTML 2D human readable format.
"jplain" : human readable J= format.
"jhtml" : HTML human readable J= format.
depth If this data structure is a sub-structure, indicates the absolute depth for 2D format.
Definition at line 564 of file Struct.cpp.
References assume(), get(), getCount(), getLength(), isAtomic(), and isEmpty().
Referenced by operator String(), operator!=(), and save().
reset() [1/2]
void Struct::reset (const char * value, ...)
Resets the data structure from a JSON weak-syntax string.
Parameters
value The value given as a string, using weak JSON syntax.
By default resets to an empty data structure.
Value is either a string or a "format" a-la printf with the subsequent arguments.
The weak-syntax, with respect to the strict JSON-syntaxallows to:
use either ':' or '=' between name and value
use either ',' or ';' as item separator
use either '"' or "'" as quote
avoid quotes for strings without space or any meta-char ':=,;]}'
accept string with '\n' line separators (replaced by the "\\n" sequence), also manage \b, \r, \t, \f
set the value 'true' for name without explicit value
However: '\uXXXX' unicode string sequences and the '\/' solidus escaped sequence are not managed (i.e., but simply mirrored in the string value)
In other words the input syntax accepts (i) implicit quote " when string reduces to one word, (ii) flexible use of comma , when optional, (iii) string on several lines, (iv) considering true as implicit value, (v) appending as a raw string trailer chars if any.
One consequence is that there is no ``syntax error'' all strings map on a JSON structure (i.e., the exact or closest correct JSON structure, the implicit metric being defined by the parsing algorithm). On the reverse the string output is a human readable indented strict JSON syntax allowing to verify that the input was well-formed.
Definition at line 275 of file Struct.cpp.
References add(), getLength(), and set().
Referenced by load(), operator!=(), reset(), and Struct().
reset() [2/2]
void Struct::reset (String value = "")
Definition at line 320 of file Struct.hpp.
References load(), reset(), and Struct().
load()
void Struct::load (String location)
Resets the data structure from a JSON weak-syntax string stored in a file.
Parameters
location The file path.
Definition at line 761 of file Struct.cpp.
References reset(), and s_load().
Referenced by reset().
Member Data Documentation
EMPTY
const Struct Struct::EMPTY static
Defines a empty struct, for initialization.
Definition at line 53 of file Struct.hpp.
Referenced by toDouble().
INT_NAN
const int Struct::INT_NAN = INT_MIN static
The 0x10000000 (INT_MIN) undefined int value.
Definition at line 106 of file Struct.hpp.
Referenced by operator int(), operator unsigned int(), Struct(), and toDouble().
The documentation for this class was generated from the following files:
src/util/Struct.hpp
src/util/Struct.cpp
mnemosyne brainybot (version of 2018-03-31 at 20:43:00)