Mnemonas'semiware: network::KernelObservableEstimator Class Reference
network::KernelObservableEstimator Class Reference
Defines a discrete-time recurrent input/output kernel transform estimator.
#include <KernelObservableEstimator.hpp>
Classes
class Observable
Defines an observable over an input.
Public Member Functions
KernelObservableEstimator (KernelTransform &transform, const Input &input, std::vector< Observable * > observables, const double *lambdas=NULL)
Resets the estimator for a given statistics.
KernelObservableEstimator (KernelTransform &transform, std::vector< Observable * > observables, const double *values, const double *lambdas=NULL)
Resets the estimator for a given statistics.
double rho () const
Defines the estimator criterion.
double drho (unsigned int n, double t) const
Defines the estimator criterion derivative.
double getObservableExpectedValue (unsigned int k) const
Gets an observable expected value.
Public Member Functions inherited from network::KernelEstimator
KernelEstimator (KernelTransform &transform)
Resets the estimator for a given kernel transform.
double run (double criterion_epsilon=1e-6, double weights_epsilon=1e-4, unsigned int maxIterations=100, String dumpDirectory="", String dumpHeader="{}")
Runs the estimation.
const ExponentialDecayFit & getFit () const
Gets the cost decay fit of the last estimation run.
virtual double rho (unsigned int n, double t) const
Defines the estimator criterion.
virtual void update ()
Updates the best previous estimated value.
virtual double get (unsigned int n, double t) const
Gets the best previous estimated value.
Static Public Member Functions
static Observable * getObservable (String name,...)
Gets a predefined observable.
static std::vector< Observable *> getObservables (String name,...)
Gets a predefined observable array.
static void deleteObservables (std::vector< Observable * > &observables)
Deletes a predefined observable array.
Additional Inherited Members
Protected Attributes inherited from network::KernelEstimator
KernelTransform & transform
double * values0
double * w0
Detailed Description
Defines a discrete-time recurrent input/output kernel transform estimator.
Definition at line 3 of file KernelObservableEstimator.hpp.
Constructor & Destructor Documentation
KernelObservableEstimator() [1/2]
network::KernelObservableEstimator::KernelObservableEstimator (KernelTransform & transform, const Input & input, std::vector< Observable * > observables, const double * lambdas = NULL)
Resets the estimator for a given statistics.
Parameters
transform The kernel transform to estimate.
input The input to consider as a reference.
observables The observables to take into account. They must be deleted after the KernelObservableEstimator use.
lambdas The observables weighted parameters, if any.
Definition at line 61 of file KernelObservableEstimator.cpp.
References network::KernelObservableEstimator::Observable::getValue().
KernelObservableEstimator() [2/2]
network::KernelObservableEstimator::KernelObservableEstimator (KernelTransform & transform, std::vector< Observable * > observables, const double * values, const double * lambdas = NULL)
Resets the estimator for a given statistics.
Parameters
transform The kernel transform to estimate.
observables The observables to take into account. They must be deleted after the KernelObservableEstimator use.
values The observables values.
lambdas The observables weighted parameters, if any.
Definition at line 38 of file KernelObservableEstimator.cpp.
References network::Input::getT().
Member Function Documentation
rho()
double network::KernelObservableEstimator::rho () const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a global estimator.
The default implementation simply returns , running:
double r = 0;
transform.reset(true);
for(unsigned int t = 0; t < transform.getT(); t++)
  for(int n =  transform.getN() - 1; 0 <= n; n--)
     r += rho(n, t, transform.get(n, t));
return r / (transform.getN() *  transform.getT());
Returns
The criterion value to mnimize.
Reimplemented from network::KernelEstimator.
Definition at line 74 of file KernelObservableEstimator.cpp.
References network::RecurrentTransform::get(), network::Input::getN(), network::Input::getT(), network::KernelObservableEstimator::Observable::getValue(), network::RecurrentTransform::reset(), and network::KernelEstimator::transform.
drho()
double network::KernelObservableEstimator::drho (unsigned int n, double t) const virtual
Defines the estimator criterion derivative.
The method is to be overwritten to implement a given estimator.
Parameters
n The input unit index.
t The value time.
Returns
The value derivative .
Reimplemented from network::KernelEstimator.
Definition at line 91 of file KernelObservableEstimator.cpp.
References network::KernelObservableEstimator::Observable::getValue().
getObservableExpectedValue()
double network::KernelObservableEstimator::getObservableExpectedValue (unsigned int k) const
Gets an observable expected value.
Parameters
k The observable index.
Definition at line 100 of file KernelObservableEstimator.cpp.
References assume().
getObservable()
network::KernelObservableEstimator::Observable * network::KernelObservableEstimator::getObservable (String name, ...) static
Gets a predefined observable.
Parameters
name : The predefined observable name.
mean : The input mean of a given channel .
Parameter: The unit index n.
icorr : The input inter-correlation between two channels .
Parameters: The unit index n and the unit index m.
acorr : The input auto-correlation of a given channel .
Parameters: The unit index n and the delay tau (as unsigned int), with tau = 0, simply returns the 2nd order momentum, tau values above 16 are numericaly unrealistic.
Returns
The corresponding observable, to be deleted after use.
Definition at line 105 of file KernelObservableEstimator.cpp.
References assume(), and s_printf().
Referenced by getObservables().
getObservables()
std::vector< network::KernelObservableEstimator::Observable *> network::KernelObservableEstimator::getObservables (String name, ...) static
Gets a predefined observable array.
Parameters
name : The predefined observable name.
mean : The mean for each channel .
Parameter: The number of channels N, values above 32 are numericaly unrealistic.
icorr : The mean and inter-correlation between two channels .
Parameter: The number of channels N, values above 8 are numericaly unrealistic.
acorr : The mean and auto-correlation for each channel .
Parameter: The number of channels N, and the maximal delay tau (as unsigned int), with tau = 0, simply implements 1st and 2nd order momenta, N * tau values above 32 are numericaly unrealistic..
Returns
The corresponding observables array, each observable are to be deleted with deleteObservables().
Definition at line 191 of file KernelObservableEstimator.cpp.
References assume(), and getObservable().
deleteObservables()
void network::KernelObservableEstimator::deleteObservables (std::vector< Observable * > & observables) static
Deletes a predefined observable array.
Parameters
observables The observable array to delete.
Definition at line 232 of file KernelObservableEstimator.cpp.
The documentation for this class was generated from the following files:
src/network/KernelObservableEstimator.hpp
src/network/KernelObservableEstimator.cpp
mnemosyne brainybot (version of 2017-11-12 at 17:57:54)