Mnemonas'semiware: network::BufferedInput Class Reference
network::BufferedInput Class Reference
Defines a static buffered input of a calculation network.
#include <BufferedInput.hpp>
Buffer construction by copy
BufferedInput (const Input &input, unsigned int N0=0, unsigned int n0=0, unsigned int T0=0, unsigned int t0=0)
Resets the input from another input with a predefined function.
BufferedInput (const double *values, unsigned int N, unsigned int T)
Resets the input with static values.
BufferedInput (String file, String format="binary-unit-time")
Resets the input with values loaded from a file.
Buffer construction by calculation
BufferedInput (String name, unsigned int N, unsigned int T,...)
Resets the input with predefined values.
BufferedInput (const Input &input, String name,...)
Resets the input applying a predefined transformation on another input.
Variable length buffer interface
BufferedInput (unsigned int N)
Resets the input with static variable time length values.
void add (const double *value)
Adds a value if (and only if) this is a variable time length buffer.
Buffered input read
double get (unsigned int n, double t) const
Returns the input value.
void save (String file, String format="binary-unit-time", bool show=false) const
Saves the recorded values.
const Histogram getHistogram (String what="") const
Returns some value statistics.
Additional Inherited Members
Public Member Functions inherited from network::Input
Input (unsigned int N, double T)
Resets the input dimensions.
Public Attributes inherited from network::Input
const unsigned int N
Gets the number of input units.
const double T
Gets the maximal time range.
Protected Member Functions inherited from network::Input
virtual void setN (unsigned int N)
Sets the number of input units.
virtual void setT (double T)
Sets the maximal time range.
Detailed Description
Defines a static buffered input of a calculation network.
Definition at line 6 of file BufferedInput.hpp.
Constructor & Destructor Documentation
BufferedInput() [1/6]
network::BufferedInput::BufferedInput (const Input & input, unsigned int N0 = 0, unsigned int n0 = 0, unsigned int T0 = 0, unsigned int t0 = 0)
Resets the input from another input with a predefined function.
All input values are called once in sequence during object construction.
Parameters
input The input to buffer.
N0 If 0 < N0 considers only N0 units.
n0 If 0 < n0 considers only units starting at the n0 index.
T0 If 0 < T0 considers only T0 time-steps.
t0 If 0 < t0 considers only time-steps starting at the t0 index.
Definition at line 22 of file BufferedInput.cpp.
References network::Input::get(), network::Input::N, and network::Input::T.
BufferedInput() [2/6]
network::BufferedInput::BufferedInput (const double * values, unsigned int N, unsigned int T)
Resets the input with static values.
Parameters
values A double[T][N] buffer with the input values, stored a T sequences of N values.
The values are not copied, the buffer must thus be available during the whole object life.
N The number of input units.
T The maximal input time.
Definition at line 29 of file BufferedInput.cpp.
BufferedInput() [3/6]
network::BufferedInput::BufferedInput (String file, String format = "binary-unit-time")
Resets the input with values loaded from a file.
Parameters
file The file name, an extension is added to this name.
format
"binary-unit-time" : ascii integer value header, then unit's value at a given time in sequence, as 64-bits double floating point values:
N T\nget(0, 0) get(1, 0) get(N-1, 0) get(0, 1) get(1, 1) .. get(N-1, 1)
The .dat extension is added to the file-name.
"csv" : each line stores unit's value at a given time, in sequence, in ascii:
get(0, 0),get(1, 0), .. get(N-1, 0)\nget(0, 1),get(1, 1), .. get(N-1, 1)
The .csv extension is added to the file-name.
Definition at line 31 of file BufferedInput.cpp.
References assume(), network::Input::N, network::Input::setN(), network::Input::setT(), and network::Input::T.
BufferedInput() [4/6]
network::BufferedInput::BufferedInput (String name, unsigned int N, unsigned int T, ...)
Resets the input with predefined values.
Parameters
name The sequence name.
"normal: A 0 mean and 1 standard-deviation pseudo-random normal value sequence.
Parameter: A seed::unsigned int specifying if the sequence is reproducible (using same seed value at each call) or not.
"sierpinski": The Sierpinski sequence, i.e. the lower bits binary decomposition (with values) of the Pascal triangle read from left to right and form top to down in sequence.
Parameter: None.
"zerone": Generates a random binary sequence of a given period.
Parameter: The binary sequence period.
"ramp": Generates ramps of period T/(n+1), i.e., .
Parameter: None.
"mean" : A reproducible pseudo-random normal value sequence, with a given mean.
Parameter: A mean::double value. The standard-deviation is mean / 10.
"icorr": A reproducible pseudo-random normal value sequence, with inter-correlation between each pair of unit.
Parameter: A icorr::double inter-correlation value.
"acorr": A reproducible pseudo-random normal value sequence, with auto-correlation for each unit.
Parameter: A acorr::double auto-correlation value.
N The number of input units.
T The maximal input time.
Definition at line 69 of file BufferedInput.cpp.
References assume(), Density::gaussian(), network::Input::N, Density::setSeed(), network::Input::T, and Density::uniform().
BufferedInput() [5/6]
network::BufferedInput::BufferedInput (const Input & input, String name, ...)
Resets the input applying a predefined transformation on another input.
Parameters
input The input to buffer.
name The tranformation name.
"affine: Performs an affine transform output(n, t) = offset + gain * input(n, t).
Parameters: The offset::double and the gain::double
"noise": Adds some noise to the input drawn from a normal distribution.
Parameters: The probability to add noise to a given value noiseProbability::double and the standard deviation of the normal added noise noiseStandardDeviation::double
Definition at line 142 of file BufferedInput.cpp.
References assume(), Density::gaussian(), network::Input::get(), network::Input::N, network::Input::T, and Density::uniform().
BufferedInput() [6/6]
network::BufferedInput::BufferedInput (unsigned int N)
Resets the input with static variable time length values.
Values are added in sequence using the add() method.
Parameters
N The number of input units.
Definition at line 30 of file BufferedInput.cpp.
Member Function Documentation
add()
void network::BufferedInput::add (const double * value)
Adds a value if (and only if) this is a variable time length buffer.
The time-length is incremented at each step.
Parameters
value A double[N] array with the current time value.
Definition at line 185 of file BufferedInput.cpp.
References assume(), network::Input::N, and network::Input::setT().
get()
double network::BufferedInput::get (unsigned int n, double t) const virtual
Returns the input value.
The method is to be overwritten to implement a given input.
Parameters
n The input unit index.
t The value time.
Returns
The input value if defined, else raises a fatal error.
Reimplemented from network::Input.
Definition at line 173 of file BufferedInput.cpp.
References assume().
Referenced by network::RecurrentTransform::getLyapunovExponent().
save()
void network::BufferedInput::save (String file, String format = "binary-unit-time", bool show = false) const
Saves the recorded values.
Parameters
file The data file name, an extension is added to this name: .csv if using the "csv" format, .dat otherwise.
"stdout" : printf the result, in "ascii-unit-time"
format
"binary-unit-time" : as defined for BufferedInput::load()
"csv" : as defined for BufferedInput::load()
"ascii-unit-time" : each line stores unit's value at a given time, in sequence, in ascii:
get(0, 0) get(1, 0) .. get(N-1, 0)\nget(0, 1) get(1, 1) .. get(N-1, 1)
"gnuplot" : each line stores a value with indexes, in ascii,
n t get(n, t)
"gnuimg" : stores the data as a float image, each line stores the n-th unt time sequence
get(n, 0) get(n, 1) .. get(n, T-1)
For "gnuplot" and "gnuimg" a gnuplot display script and image is generated, with extensions .gnuplot.sh and .png.
Parameters
show When considering the "gnuplot" or "gnuimg" format, if true, performs on the fly display.
Definition at line 192 of file BufferedInput.cpp.
References assume(), gnuplot(), network::Input::N, s_printf(), and s_save_mkdir().
Referenced by network::KernelExperimentalEstimator::run().
getHistogram()
const Histogram network::BufferedInput::getHistogram (String what = "") const
Returns some value statistics.
Parameters
what The list of unit index to consider, by default all values are taken into account.
Returns
The given statistics.
Definition at line 248 of file BufferedInput.cpp.
References Histogram::add(), network::Input::N, and s_printf().
The documentation for this class was generated from the following files:
src/network/BufferedInput.hpp
src/network/BufferedInput.cpp
mnemosyne brainybot (version of 2018-03-27 at 07:27:18)