Mnemonas'semiware: network::KernelTransform Class Reference
network::KernelTransform Class Reference
Defines a discrete-time recurrent input/output kernel transform.
#include <KernelTransform.hpp>
Public Member Functions
KernelTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
void resetWeights ()
Inits the weights.
virtual unsigned int getKernelDimension (unsigned int n) const
Returns the recurrent kernel dimension.
virtual double getKernelValue (unsigned int n, unsigned int d, double t) const
Returns the recurrent kernel value.
virtual double getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const
Returns the recurrent kernel derivative with respect to a recurrent state value.
unsigned int getWeightCount () const
Returns the total number of weights.
double getWeight (unsigned int n, unsigned int d) const
Gets one weight .
virtual bool setWeight (unsigned int n, unsigned int d, double w)
Sets one weight value.
virtual KernelTransform & setWeights (const KernelTransform &network)
Sets weights from another network of the same type.
KernelTransform & setWeightsRandom (double mean=0.0, double sigma=0.0, bool add=false, String mode="normal", int seed=-1)
Sets random or constant weights values.
double getValue (unsigned int n, double t) const
Implements the discrete-time recurrent equation.
double getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const
Implements the discrete-time recurrent equation derivative.
std::string asString () const
Returns the weight values as a JSON string.
Public Member Functions inherited from network::RecurrentTransform
RecurrentTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
RecurrentTransform & reset (bool buffered=false, double upsilon=0)
Resets the transform buffering.
unsigned int getR () const
Gets the maximal recurrent range.
double get (unsigned int n, double t) const
Returns the input value.
void set (unsigned int n, double t, double value)
Sets an input value of the recurrent equation.
virtual bool isConnected (unsigned int n, double t, unsigned int n_, double t_) const
Checks if two units are connected.
double getValueDerivativeApproximation (unsigned int n, double t, unsigned int n_, double t_, double epsilon=1e-3) const
Calculates the numerical approximate value derivative.
double getLyapunovExponent (unsigned int W=10, unsigned int M=10, double d0=1e-6)
Estimates the Lyapunov exponent.
std::string asString () const
Returns the transform parameters as a JSON string.
Public Member Functions inherited from network::Transform
Transform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
const Input & getInput () const
Gets the transform input.
Public Member Functions inherited from network::Input
Input (unsigned int N, double T)
Resets the input dimensions.
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
Static Public Member Functions
static KernelTransform * newKernelTransform (String type, unsigned int N, const network::Input &input)
Constructs a new KernelTransform of a given implemented type.
Additional Inherited Members
Protected Attributes inherited from network::RecurrentTransform
unsigned int R
unsigned int L
Protected Attributes inherited from network::Transform
const Input & input
Protected Attributes inherited from network::Input
unsigned int N
double T
Detailed Description
Defines a discrete-time recurrent input/output kernel transform.
A recurrent transform of the form for and : with:
nodes of value indexed by ,
with a maximal state recurrent range of , (i.e., taking into account recurrent value up to time-steps in the past),
and initial condition ;
of these nodes are output;
input indexed by ,
with a maximal input recurrent range of , ,
and initial condition ;
The node structure is defined by predefined kernels for each node;
The node parameters are static adjustable weights .
Definition at line 16 of file KernelTransform.hpp.
Constructor & Destructor Documentation
KernelTransform()
network::KernelTransform::KernelTransform (unsigned int N, unsigned int R, const Input & input)
Resets the transform for the given parameters.
Parameters
N The number of input units, defined unit indexes stand in {0, N{.
R The maximal recurrent time range, at a current time t, defined times stand in [t+0, t+R[.
input The transform input.
Definition at line 3 of file KernelTransform.cpp.
Referenced by resetWeights().
Member Function Documentation
resetWeights()
void network::KernelTransform::resetWeights ()
Inits the weights.
This is to be called if the network architecture or connections changes (no need to call it at initiailization).
Definition at line 4 of file KernelTransform.cpp.
References getKernelDimension(), network::Transform::input, KernelTransform(), network::Input::N, and network::RecurrentTransform::R.
getKernelDimension()
unsigned int network::KernelTransform::getKernelDimension (unsigned int n) const virtual
Returns the recurrent kernel dimension.
The method is to be overwritten to implement a given transform.
Parameters
n The state unit index in {0, N{.
Returns
the state unit recurrent kernel dimension.
Reimplemented in network::IntegrateAndFireTransform, network::LinearNonLinearTransform, network::SparseNonLinearTransform, network::SoftMaxTransform, and network::LinearTransform.
Definition at line 29 of file KernelTransform.cpp.
References assume().
Referenced by asString(), getValue(), getValueDerivative(), network::RecurrentTransform::getValueDerivativeApproximation(), getWeight(), network::KernelDistributedEstimator::KernelDistributedEstimator(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), resetWeights(), network::KernelDistributedEstimator::run(), network::KernelEstimator::run(), setWeight(), setWeightsRandom(), and network::KernelEstimator::updateReadout().
getKernelValue()
double network::KernelTransform::getKernelValue (unsigned int n, unsigned int d, double t) const virtual
Returns the recurrent kernel value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The time index in {0, T{.
Returns
The corresponding kernel value .
Reimplemented in network::IntegrateAndFireTransform, network::LinearNonLinearTransform, network::SparseNonLinearTransform, network::SoftMaxTransform, and network::LinearTransform.
Definition at line 34 of file KernelTransform.cpp.
References assume().
Referenced by getValue(), network::RecurrentTransform::getValueDerivativeApproximation(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), and network::KernelEstimator::updateReadout().
getKernelDerivative()
double network::KernelTransform::getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const virtual
Returns the recurrent kernel derivative with respect to a recurrent state value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The state time index in {0, T{.
n_ The recurrent unit index in {0, N{.
t_ The recurrent time index in {t-R, t{.
Returns
Returns 0.0 if does not depend on , else .
Reimplemented in network::IntegrateAndFireTransform, network::LinearNonLinearTransform, network::SparseNonLinearTransform, network::SoftMaxTransform, and network::LinearTransform.
Definition at line 39 of file KernelTransform.cpp.
References assume().
Referenced by getValueDerivative(), and network::RecurrentTransform::getValueDerivativeApproximation().
getWeightCount()
unsigned int network::KernelTransform::getWeightCount () const
Returns the total number of weights.
Returns
>_n getKernelDimension(n)
Definition at line 77 of file KernelTransform.hpp.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), and network::KernelEstimator::updateReadout().
getWeight()
double network::KernelTransform::getWeight (unsigned int n, unsigned int d) const
Gets one weight .
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {1, getKernelDimension()}.
Returns
The weight value.
Definition at line 86 of file KernelTransform.hpp.
References getKernelDimension(), getValue(), setWeight(), setWeights(), and setWeightsRandom().
Referenced by asString(), getValue(), getValueDerivative(), network::KernelDistributedEstimator::run(), network::KernelEstimator::run(), network::LinearTransform::setWeights(), network::SoftMaxTransform::setWeights(), network::SparseNonLinearTransform::setWeights(), network::LinearNonLinearTransform::setWeights(), network::IntegrateAndFireTransform::setWeights(), setWeightsRandom(), and network::KernelEstimator::updateReadout().
setWeight()
bool network::KernelTransform::setWeight (unsigned int n, unsigned int d, double w) virtual
Sets one weight value.
This routine is to be overriden if the weights are bounded (e.g. if positive). A typical implementation writes, e.g.:
 bool setWeight(unsigned int n, unsigned int d, double w) {
   // Constraint the weight of idex 0 to be positive
   if (d == 0 && w < 0) {
     setWeight(n, d, 0);
     return false;
   } else
     return setWeight(n, d, d);
 }
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {1, getKernelDimension()}.
w The weight value.
Returns
True if the value is inside the bounds, false if the value has been bounded, i.e. is equal to the bound or outside the bound.
Reimplemented in network::IntegrateAndFireTransform, network::LinearNonLinearTransform, network::SoftMaxTransform, and network::LinearTransform.
Definition at line 51 of file KernelTransform.cpp.
References assume(), getKernelDimension(), and network::Input::N.
Referenced by getWeight(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), network::LinearTransform::setWeight(), network::SoftMaxTransform::setWeight(), network::LinearNonLinearTransform::setWeight(), network::IntegrateAndFireTransform::setWeight(), setWeightsRandom(), and network::KernelEstimator::updateReadout().
setWeights()
network::KernelTransform & network::KernelTransform::setWeights (const KernelTransform & network) virtual
Sets weights from another network of the same type.
By contract weights are copied considering the 1st units, if both network do not have the same number of units.
By contract weights are copied if and only if both network are of the same type and each KerneTransform must implement this method and test the type dynamically via construct of the form:
assume(dynamic_cast<$transform-type *>(&network) != NULL, "illegal-argument", "in network::$transform-type::setWeights wrong network type");
.
Parameters
network The weights source network.
Reimplemented in network::IntegrateAndFireTransform, network::LinearNonLinearTransform, network::SparseNonLinearTransform, network::SoftMaxTransform, and network::LinearTransform.
Definition at line 58 of file KernelTransform.cpp.
References assume().
Referenced by getWeight().
setWeightsRandom()
network::KernelTransform & network::KernelTransform::setWeightsRandom (double mean = 0.0, double sigma = 0.0, bool add = false, String mode = "normal", int seed = -1)
Sets random or constant weights values.
Weights are drawn from either a uniform or a normal distribution.
If sigma = 0, it sets or adds to the weights a fixed value.
The uniform distribution stands in the interval.
Parameters
mean The distribution mean.
sigma The distribution standard-deviation.
add If true adds the random noise to existing values, else replaces values by the noise.
mode Either "uniform" or "normal" distribution.
seed If seed == -1 changes randomly the seed, taking the system time. The initial seed is 0, at the beginning of the program.
Returns
this.
Definition at line 63 of file KernelTransform.cpp.
References random::gaussian(), getKernelDimension(), getWeight(), network::Input::N, random::setSeed(), setWeight(), and random::uniform().
Referenced by getWeight().
getValue()
double network::KernelTransform::getValue (unsigned int n, double t) const virtual
Implements the discrete-time recurrent equation.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Returns
The input value if defined, else raises a fatal error.
It calculates ,
Reimplemented from network::RecurrentTransform.
Definition at line 86 of file KernelTransform.cpp.
References getKernelDimension(), getKernelValue(), and getWeight().
Referenced by network::RecurrentTransform::getValueDerivativeApproximation(), and getWeight().
getValueDerivative()
double network::KernelTransform::getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const virtual
Implements the discrete-time recurrent equation derivative.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Parameters
n_ The afferent input unit index denominator.
t_ The value time denominator.
Returns
The input value derivate if defined, 0 in the abscence of dependence, else raises a fatal error.
If the recurrent equation writes , this method returns: ,
Reimplemented from network::RecurrentTransform.
Definition at line 128 of file KernelTransform.hpp.
References asString(), getKernelDerivative(), getKernelDimension(), getWeight(), and newKernelTransform().
Referenced by network::KernelEstimator::run().
asString()
std::string network::KernelTransform::asString () const
Returns the weight values as a JSON string.
Definition at line 75 of file KernelTransform.cpp.
References network::RecurrentTransform::asString(), getKernelDimension(), getWeight(), network::Input::N, and s_printf().
Referenced by getValueDerivative().
newKernelTransform()
network::KernelTransform * network::KernelTransform::newKernelTransform (String type, unsigned int N, const network::Input & input) static
Constructs a new KernelTransform of a given implemented type.
Parameters
type The network type, here "LinearTransform" "LinearNonLinearTransform" "SparseNonLinearTransform" "SoftMaxTransform" "IntegrateAndFireTransform"
N The number of input units, defined unit indexes stand in {0, N{.
input The transform input.
Returns
The corresponding KernelTransform, to be deleted after use.
Definition at line 102 of file KernelTransform.cpp.
References assume().
Referenced by getValueDerivative().
The documentation for this class was generated from the following files:
src/network/KernelTransform.hpp
src/network/KernelTransform.cpp
mnemosyne brainybot (version of 2018-01-24 at 11:20:50)