Mnemonas'semiware: network::Observable Class Reference
network::Observable Class Reference
Defines an observable over an input.
#include <Observable.hpp>
Public Member Functions
Observable (String name)
Constructs an observable of the given name.
std::string asString () const
Gets the observable name and value.
Observable & reset (const Input &input)
Resets the observable for a given input.
double getValue () const
Gets the observable value expectation, given the measures.
double getValueDerivative (unsigned int n, double t) const
Gets the local observable derivative.
Protected Member Functions
virtual double doValue ()
Calculates and returns the observable value expectation, given the measures.
virtual double doValueDerivative (unsigned int n, double t)
Calculates and returns the observable derivative.
Protected Attributes
const Input * input
This is used to implement the getValueDerivative().
Detailed Description
Defines an observable over an input.
An Observable maps an Input onto a global (usually statistical) value.
By contract:
Observable must implement an implicit or explicit copy constructor.
The doValue() and doValueDerivative() methods implements a particular observable.
Definition at line 8 of file Observable.hpp.
Constructor & Destructor Documentation
Observable()
network::Observable::Observable (String name)
Constructs an observable of the given name.
Definition at line 3 of file Observable.cpp.
Member Function Documentation
asString()
std::string network::Observable::asString () const
Gets the observable name and value.
Definition at line 13 of file Observable.cpp.
References s_printf().
reset()
network::Observable & network::Observable::reset (const Input & input)
Resets the observable for a given input.
This reset() method must be called prior to the getValue() or getValueDerivative() method.
Parameters
input The input to observe in the input temporal range.
Returns
this;
Definition at line 7 of file Observable.cpp.
References doValue(), and input.
Referenced by network::ObservableCriterion::update().
getValue()
double network::Observable::getValue () const
Gets the observable value expectation, given the measures.
Definition at line 17 of file Observable.cpp.
References assume(), and input.
Referenced by network::ObservableCriterion::drho(), network::ObservableCriterion::ObservableCriterion(), network::ObservableCriterion::rho(), and network::ObservableCriterion::update().
getValueDerivative()
double network::Observable::getValueDerivative (unsigned int n, double t) const
Gets the local observable derivative.
Parameters
n The unit index.
t The time index.
Definition at line 22 of file Observable.cpp.
References assume(), doValueDerivative(), and input.
Referenced by network::ObservableCriterion::update().
doValue()
double network::Observable::doValue () protected virtual
Calculates and returns the observable value expectation, given the measures.
Typical implementation writes :
  reset_the_calculation();
 for(unsigned int t = 0; t < input->T; t++)
   add_new_values(t);
 return finalize_the_calculation();
Definition at line 27 of file Observable.cpp.
References assume().
Referenced by reset().
doValueDerivative()
double network::Observable::doValueDerivative (unsigned int n, double t) protected virtual
Calculates and returns the observable derivative.
Typical implementation uses input->get(n, t) to calculate the local observable derivative.
Parameters
n The unit index.
t The time index.
Definition at line 32 of file Observable.cpp.
References assume().
Referenced by getValueDerivative().
Member Data Documentation
input
const Input* network::Observable::input protected
This is used to implement the getValueDerivative().
Definition at line 13 of file Observable.hpp.
Referenced by getValue(), getValueDerivative(), and reset().
The documentation for this class was generated from the following files:
src/network/Observable.hpp
src/network/Observable.cpp
mnemosyne brainybot (version of 2018-02-25 at 12:57:17)