Mnemonas'semiware: network::LinearNonLinearTransform Class Reference
network::LinearNonLinearTransform Class Reference
Defines a recurrent network as a non-linear affine combination of input and recurrent values.
#include <LinearNonLinearTransform.hpp>
Public Member Functions
LinearNonLinearTransform (unsigned int N, const Input &input, double min=0, double max=1)
Resets the transform for the given parameters.
LinearNonLinearTransform & setLeak (double value=0)
Sets a fixed common leak for this network.
LinearNonLinearTransform & setOffset (double value=0)
Sets a fixed common offset for this network.
bool setWeight (unsigned int n, unsigned int d, double w)
Sets one weight value.
KernelTransform & setWeights (const KernelTransform &network)
Sets weights from another network of the same type.
unsigned int getKernelDimension (unsigned int n) const
Returns the recurrent kernel dimension.
double getKernelValue (unsigned int n, unsigned int d, double t) const
Returns the recurrent kernel value.
double getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const
Returns the recurrent kernel derivative with respect to a recurrent state value.
bool isConnected (unsigned int n, double t, unsigned int n_, double t_) const
Checks if two units are connected.
Public Member Functions inherited from network::KernelTransform
KernelTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
void resetWeights ()
Inits the weights.
unsigned int getWeightCount () const
Returns the total number of weights.
double getWeight (unsigned int n, unsigned int d) const
Gets one weight .
KernelTransform & setWeightsRandom (double mean=0.0, double sigma=0.0, bool add=false, String mode="normal", int seed=-1)
Sets random or constant weights values.
double getValue (unsigned int n, double t) const
Implements the discrete-time recurrent equation.
double getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const
Implements the discrete-time recurrent equation derivative.
std::string asString () const
Returns the weight values as a JSON string.
Public Member Functions inherited from network::RecurrentTransform
RecurrentTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
RecurrentTransform & reset (bool buffered=false, double upsilon=0)
Resets the transform buffering.
unsigned int getR () const
Gets the maximal recurrent range.
double get (unsigned int n, double t) const
Returns the input value.
void set (unsigned int n, double t, double value)
Sets an input value of the recurrent equation.
double getValueDerivativeApproximation (unsigned int n, double t, unsigned int n_, double t_, double epsilon=1e-3) const
Calculates the numerical approximate value derivative.
Histogram getLyapunovExponent (unsigned int W=10, unsigned int K=10, double d0=1e-6)
Estimates the Lyapunov exponent.
std::string asString () const
Returns the transform parameters as a JSON string.
Public Member Functions inherited from network::Transform
Transform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
const Input & getInput () const
Gets the transform input.
Public Member Functions inherited from network::Input
Input (unsigned int N, double T)
Resets the input dimensions.
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
Additional Inherited Members
Static Public Member Functions inherited from network::KernelTransform
static KernelTransform * newKernelTransform (String type, unsigned int N, const network::Input &input)
Constructs a new KernelTransform of a given implemented type.
Protected Attributes inherited from network::RecurrentTransform
unsigned int R
unsigned int L
Protected Attributes inherited from network::Transform
const Input & input
Protected Attributes inherited from network::Input
unsigned int N
double T
Detailed Description
Defines a recurrent network as a non-linear affine combination of input and recurrent values.
Such recurrent network writes: Weight organization:
Unit leak
Unit offset
Recurrent weights
Input weights
with .
In order to avoid unbounded values, when using a ReLU profile, a saturation at is introduced.
Definition at line 19 of file LinearNonLinearTransform.hpp.
Constructor & Destructor Documentation
LinearNonLinearTransform()
network::LinearNonLinearTransform::LinearNonLinearTransform (unsigned int N, const Input & input, double min = 0, double max = 1)
Resets the transform for the given parameters.
Parameters
N The number of input units, defined unit indexes stand in {0, N{.
The network has 3\,N nodes.
input The transform input.
min The minimal value of the sigmoid non-linearity.
max The maximal value of the sigmoid non-linearity. If max == INFINITY defines a ReLU, i.e. a rectification, i.e. .
Definition at line 18 of file LinearNonLinearTransform.cpp.
References assume(), setLeak(), and setOffset().
Member Function Documentation
setLeak()
network::LinearNonLinearTransform & network::LinearNonLinearTransform::setLeak (double value = 0)
Sets a fixed common leak for this network.
Parameters
value The leak value of all , NAN to unconstrain the value.
Returns
this.
Definition at line 25 of file LinearNonLinearTransform.cpp.
References setWeight().
Referenced by LinearNonLinearTransform().
setOffset()
network::LinearNonLinearTransform & network::LinearNonLinearTransform::setOffset (double value = 0)
Sets a fixed common offset for this network.
Parameters
value The offset value of all , NAN to unconstrain the value.
Returns
this.
Definition at line 35 of file LinearNonLinearTransform.cpp.
References setWeight().
Referenced by LinearNonLinearTransform().
setWeight()
bool network::LinearNonLinearTransform::setWeight (unsigned int n, unsigned int d, double w) virtual
Sets one weight value.
This routine is to be overriden if the weights are bounded (e.g. if positive). A typical implementation writes, e.g.:
 bool setWeight(unsigned int n, unsigned int d, double w) {
   // Constraint the weight of idex 0 to be positive
   if (d == 0 && w < 0) {
     setWeight(n, d, 0);
     return false;
   } else
     return setWeight(n, d, d);
 }
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {1, getKernelDimension()}.
w The weight value.
Returns
True if the value is inside the bounds, false if the value has been bounded, i.e. is equal to the bound or outside the bound.
Reimplemented from network::KernelTransform.
Definition at line 45 of file LinearNonLinearTransform.cpp.
References network::KernelTransform::setWeight().
Referenced by setLeak(), setOffset(), and setWeights().
setWeights()
network::KernelTransform & network::LinearNonLinearTransform::setWeights (const KernelTransform & network) virtual
Sets weights from another network of the same type.
By contract weights are copied considering the 1st units, if both network do not have the same number of units.
By contract weights are copied if and only if both network are of the same type and each KerneTransform must implement this method and test the type dynamically via construct of the form:
assume(dynamic_cast<$transform-type *>(&network) != NULL, "illegal-argument", "in network::$transform-type::setWeights wrong network type");
.
Parameters
network The weights source network.
Reimplemented from network::KernelTransform.
Definition at line 55 of file LinearNonLinearTransform.cpp.
References assume(), getKernelDimension(), network::Input::getN(), network::KernelTransform::getWeight(), and setWeight().
getKernelDimension()
unsigned int network::LinearNonLinearTransform::getKernelDimension (unsigned int n) const virtual
Returns the recurrent kernel dimension.
The method is to be overwritten to implement a given transform.
Parameters
n The state unit index in {0, N{.
Returns
the state unit recurrent kernel dimension.
Reimplemented from network::KernelTransform.
Definition at line 65 of file LinearNonLinearTransform.cpp.
References network::Input::getN(), and network::Transform::input.
Referenced by setWeights().
getKernelValue()
double network::LinearNonLinearTransform::getKernelValue (unsigned int n, unsigned int d, double t) const virtual
Returns the recurrent kernel value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The time index in {0, T{.
Returns
The corresponding kernel value .
Reimplemented from network::KernelTransform.
Definition at line 69 of file LinearNonLinearTransform.cpp.
References network::Input::get(), network::Input::getN(), and network::Transform::input.
getKernelDerivative()
double network::LinearNonLinearTransform::getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const virtual
Returns the recurrent kernel derivative with respect to a recurrent state value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The state time index in {0, T{.
n_ The recurrent unit index in {0, N{.
t_ The recurrent time index in {t-R, t{.
Returns
Returns 0.0 if does not depend on , else .
Reimplemented from network::KernelTransform.
Definition at line 89 of file LinearNonLinearTransform.cpp.
isConnected()
bool network::LinearNonLinearTransform::isConnected (unsigned int n, double t, unsigned int n_, double t_) const virtual
Checks if two units are connected.
The method is to be overwritten to implement sparse connected networks.
Parameters
n The efferent input unit index.
t The efferent input unit current time.
n_ The afferent input unit index denominator.
t_ The afferent input unit current time.
Returns
False if the unit of index n_ never connects to the unit of index n, for the given times, true if the connection is to be checked via getValueDerivative()
Reimplemented from network::RecurrentTransform.
Definition at line 97 of file LinearNonLinearTransform.cpp.
The documentation for this class was generated from the following files:
src/network/LinearNonLinearTransform.hpp
src/network/LinearNonLinearTransform.cpp
mnemosyne brainybot (version of 2018-02-02 at 08:26:13)