Mnemonas'semiware: network::KernelEstimator Class Reference
network::KernelEstimator Class Reference
Defines basic mechanisms for kernel weights backward tuning estimation.
#include <KernelEstimator.hpp>
Classes
class connection
Public Member Functions
KernelEstimator (KernelTransform &transform, TransformCriterion &criterion)
Resets the estimator for a given kernel transform.
double run ()
Runs one step of estimation.
double getCost () const
Gets the last estimated cost.
double getValue (unsigned int n, double t) const
Gets the last estimated state value.
double getError (unsigned int n, double t) const
Gets the last estimated backward error.
const double * getWeights () const
Gets the last estimated weights.
double updateReadout (unsigned int N0=0)
Updates the weights given a readout estimation.
const CurveFit & getFit (String what="cost") const
Gets some fits of the estimation runs.
Protected Attributes
KernelTransform & transform
The tranform to estimate.
unsigned int N
The transform related parameters.
unsigned int T
unsigned int R
TransformCriterion & criterion
The criterion to apply.
CurveFit costs
The cost and errors traces.
CurveFit output_errors
CurveFit backward_errors
CurveFit ratio_negligible
CurveFit ratio_saturated
CurveFit simulation_time
CurveFit tuning_time
CurveFit iteration_time
double cost
double * weights0
double * values0
double * errors
double drho_mean
bool once
std::vector< connection > * connections
unsigned int k_negligible
Number of negligible or saturated values during a backward tuning, over the N T values.
unsigned int k_saturated
Detailed Description
Defines basic mechanisms for kernel weights backward tuning estimation.
Definition at line 5 of file KernelEstimator.hpp.
Constructor & Destructor Documentation
KernelEstimator()
network::KernelEstimator::KernelEstimator (KernelTransform & transform, TransformCriterion & criterion)
Resets the estimator for a given kernel transform.
Parameters
transform The kernel transform to estimate.
The recurrent transform is fully buffered fo the estimation purpose.
criterion The criterion to use for the estimation.
Definition at line 4 of file KernelEstimator.cpp.
References connections, errors, values0, and weights0.
Member Function Documentation
run()
double network::KernelEstimator::run ()
Runs one step of estimation.
It saves previous weights and values, runs a simulation getting the cost, estimates the backward-tuning errors.
Returns
The last estimated cost.
Definition at line 18 of file KernelEstimator.cpp.
References CurveFit::add(), backward_errors, connections, cost, costs, criterion, network::TransformCriterion::drho(), drho_mean, errors, network::RecurrentTransform::get(), network::KernelTransform::getKernelDimension(), network::KernelTransform::getValueDerivative(), network::KernelTransform::getWeight(), network::RecurrentTransform::isConnected(), iteration_time, k_negligible, k_saturated, N, network::KernelEstimator::connection::n, now(), once, output_errors, R, ratio_negligible, ratio_saturated, network::TransformCriterion::rho(), simulation_time, T, transform, tuning_time, values0, and weights0.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), and network::KernelDistributedEstimator::run().
getCost()
double network::KernelEstimator::getCost () const
Gets the last estimated cost.
Definition at line 49 of file KernelEstimator.hpp.
References cost, getValue(), and network::KernelEstimator::connection::n.
getValue()
double network::KernelEstimator::getValue (unsigned int n, double t) const
Gets the last estimated state value.
If the criterion is able to estimate the best estimated value, it is returned, otherwise the last simulation value is used.
Parameters
n The input unit index.
t The value time.
Definition at line 113 of file KernelEstimator.cpp.
References criterion, network::TransformCriterion::get(), network::TransformCriterion::getN0(), N, and values0.
Referenced by getCost(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), and updateReadout().
getError()
double network::KernelEstimator::getError (unsigned int n, double t) const
Gets the last estimated backward error.
Parameters
n The input unit index.
t The value time.
Definition at line 64 of file KernelEstimator.hpp.
Referenced by network::KernelDistributedEstimator::run().
getWeights()
const double* network::KernelEstimator::getWeights () const
Gets the last estimated weights.
Definition at line 69 of file KernelEstimator.hpp.
References getFit(), updateReadout(), and weights0.
updateReadout()
double network::KernelEstimator::updateReadout (unsigned int N0 = 0)
Updates the weights given a readout estimation.
The readout is adjusted on the N0 desired values defined by the criterion.
Parameters
N0 Defines the number of units to take into account, 0 means using criterion.getN0().
Returns
The obtained criterion cost.
Definition at line 127 of file KernelEstimator.cpp.
References assume(), criterion, network::TransformCriterion::get(), network::KernelTransform::getKernelDimension(), network::KernelTransform::getKernelValue(), network::TransformCriterion::getN0(), getValue(), network::KernelTransform::getWeight(), network::KernelTransform::getWeightCount(), solver::linsolve(), solver::minimize(), N, network::KernelEstimator::connection::n, network::TransformCriterion::rho(), network::RecurrentTransform::set(), network::KernelTransform::setWeight(), T, transform, and values0.
Referenced by getWeights().
getFit()
const CurveFit & network::KernelEstimator::getFit (String what = "cost") const
Gets some fits of the estimation runs.
Parameters
what :
"cost" : returns the cost decay fit.
"output-error" : returns the output error decay fit.
"backward-error" : returns the backward error decay fit.
"ratio-negligible" : returns the ratio of negligible backward errors.
"ratio-saturated" : returns the ratio of saturated backward errors.
"simulation-time" : returns the simulation cpu time.
"tuning-time" : returns the backward tuning cpu time.
"iteration-time" : returns the iteration duration cpu time.
Definition at line 122 of file KernelEstimator.cpp.
References backward_errors, costs, output_errors, ratio_negligible, and ratio_saturated.
Referenced by network::KernelDistributedEstimator::getFit(), and getWeights().
Member Data Documentation
transform
KernelTransform& network::KernelEstimator::transform protected
The tranform to estimate.
Definition at line 8 of file KernelEstimator.hpp.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), network::KernelExperimentalEstimator::run(), run(), and updateReadout().
N
unsigned int network::KernelEstimator::N protected
The transform related parameters.
Definition at line 10 of file KernelEstimator.hpp.
Referenced by getValue(), network::KernelDistributedEstimator::KernelDistributedEstimator(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), run(), and updateReadout().
T
unsigned int network::KernelEstimator::T protected
Definition at line 10 of file KernelEstimator.hpp.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), run(), and updateReadout().
R
unsigned int network::KernelEstimator::R protected
Definition at line 10 of file KernelEstimator.hpp.
Referenced by run().
criterion
TransformCriterion& network::KernelEstimator::criterion protected
The criterion to apply.
Definition at line 12 of file KernelEstimator.hpp.
Referenced by getValue(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), run(), and updateReadout().
costs
CurveFit network::KernelEstimator::costs protected
The cost and errors traces.
Definition at line 14 of file KernelEstimator.hpp.
Referenced by getFit(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelExperimentalEstimator::run(), and run().
output_errors
CurveFit network::KernelEstimator::output_errors protected
Definition at line 14 of file KernelEstimator.hpp.
Referenced by getFit(), and run().
backward_errors
CurveFit network::KernelEstimator::backward_errors protected
Definition at line 14 of file KernelEstimator.hpp.
Referenced by getFit(), and run().
ratio_negligible
CurveFit network::KernelEstimator::ratio_negligible protected
Definition at line 14 of file KernelEstimator.hpp.
Referenced by getFit(), and run().
ratio_saturated
CurveFit network::KernelEstimator::ratio_saturated protected
Definition at line 14 of file KernelEstimator.hpp.
Referenced by getFit(), and run().
simulation_time
CurveFit network::KernelEstimator::simulation_time protected
Definition at line 14 of file KernelEstimator.hpp.
Referenced by run().
tuning_time
CurveFit network::KernelEstimator::tuning_time protected
Definition at line 14 of file KernelEstimator.hpp.
Referenced by run().
iteration_time
CurveFit network::KernelEstimator::iteration_time protected
Definition at line 14 of file KernelEstimator.hpp.
Referenced by run().
cost
double network::KernelEstimator::cost protected
Definition at line 16 of file KernelEstimator.hpp.
Referenced by getCost(), network::KernelDistributedEstimator::run(), and run().
weights0
double * network::KernelEstimator::weights0 protected
Definition at line 16 of file KernelEstimator.hpp.
Referenced by getWeights(), KernelEstimator(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), and run().
values0
double * network::KernelEstimator::values0 protected
Definition at line 16 of file KernelEstimator.hpp.
Referenced by getValue(), KernelEstimator(), run(), and updateReadout().
errors
double * network::KernelEstimator::errors protected
Definition at line 16 of file KernelEstimator.hpp.
Referenced by KernelEstimator(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), and run().
drho_mean
double network::KernelEstimator::drho_mean protected
Definition at line 18 of file KernelEstimator.hpp.
Referenced by run().
once
bool network::KernelEstimator::once protected
Definition at line 20 of file KernelEstimator.hpp.
Referenced by run().
connections
std::vector< connection >* network::KernelEstimator::connections protected
Definition at line 28 of file KernelEstimator.hpp.
Referenced by KernelEstimator(), and run().
k_negligible
unsigned int network::KernelEstimator::k_negligible protected
Number of negligible or saturated values during a backward tuning, over the N T values.
Definition at line 31 of file KernelEstimator.hpp.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), and run().
k_saturated
unsigned int network::KernelEstimator::k_saturated protected
Definition at line 31 of file KernelEstimator.hpp.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), and run().
The documentation for this class was generated from the following files:
src/network/KernelEstimator.hpp
src/network/KernelEstimator.cpp
mnemosyne brainybot (version of 2018-01-24 at 11:20:50)