Mnemonas'semiware: network::KernelSupervisedEstimator Class Reference
network::KernelSupervisedEstimator Class Reference
Defines a discrete-time recurrent input/output kernel transform estimator.
#include <KernelSupervisedEstimator.hpp>
Public Member Functions
KernelSupervisedEstimator (KernelTransform &transform, Input &values, char criterion='2', double nu=1e-3, bool reinject=true)
Resets the estimator for a given kernel transform.
virtual double rho (unsigned int n, double t) const
Defines the estimator criterion.
virtual double drho (unsigned int n, double t) const
Defines the estimator criterion derivative.
virtual double get (unsigned int n, double t) const
Gets the best previous estimated value.
virtual void update ()
Updates the best previous estimated value.
Public Member Functions inherited from network::KernelEstimator
KernelEstimator (KernelTransform &transform)
Resets the estimator for a given kernel transform.
double run (double criterion_epsilon=1e-6, double weights_epsilon=1e-4, unsigned int maxIterations=100, String dumpDirectory="", String dumpHeader="{}")
Runs the estimation.
const ExponentialDecayFit & getFit () const
Gets the cost decay fit of the last estimation run.
virtual double rho () const
Defines the estimator criterion.
Additional Inherited Members
Protected Attributes inherited from network::KernelEstimator
KernelTransform & transform
double * values0
double * w0
Detailed Description
Defines a discrete-time recurrent input/output kernel transform estimator.
Definition at line 3 of file KernelSupervisedEstimator.hpp.
Constructor & Destructor Documentation
KernelSupervisedEstimator()
network::KernelSupervisedEstimator::KernelSupervisedEstimator (network::KernelTransform & transform, Input & values, char criterion = '2', double nu = 1e-3, bool reinject = true)
Resets the estimator for a given kernel transform.
Parameters
transform The kernel transform to estimate.
values The output desired values.
By contract output units correspond to the values.getN() lower indexed units and hidden units to the remainder indexes.
criterion The criterion index:
2 The L2 criterion .
1 The reweighted L1 criterion .
0 The reweighted L0 criterion .
a A L1 related unbounded criterion .
If simply considers the absolute value of the error.
b A L0 related biweight bounded criterion .
If simply counts the number of non-zero values.
h The L2 boolean criterion .
If simply counts the number of wrong boolean values (not used as criterion but a posteriori precision).
nu The criterion margin parameter.
reinject If true, uses the desired value in the 2nd order criterion estimation.
Definition at line 3 of file KernelSupervisedEstimator.cpp.
References assume().
Member Function Documentation
rho()
double network::KernelSupervisedEstimator::rho (unsigned int n, double t) const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a local estimator.
A typical implementation is of the form:
double network::KernelSupervisedEstimator::rho(unsigned int n, double t) const {
 double value = transform.get(n, t);
 ../..
Parameters
n The input unit index.
t The value time.
Returns
The related positive value to minimize.
Reimplemented from network::KernelEstimator.
Definition at line 14 of file KernelSupervisedEstimator.cpp.
References network::Input::get(), network::RecurrentTransform::get(), network::Input::getN(), and network::KernelEstimator::transform.
drho()
double network::KernelSupervisedEstimator::drho (unsigned int n, double t) const virtual
Defines the estimator criterion derivative.
The method is to be overwritten to implement a given estimator.
Parameters
n The input unit index.
t The value time.
Returns
The value derivative .
Reimplemented from network::KernelEstimator.
Definition at line 60 of file KernelSupervisedEstimator.cpp.
References network::Input::get(), network::RecurrentTransform::get(), network::Input::getN(), and network::KernelEstimator::transform.
get()
double network::KernelSupervisedEstimator::get (unsigned int n, double t) const virtual
Gets the best previous estimated value.
The method is to be overwritten if output values can be provided.
Parameters
n The input unit index.
t The value time.
Reimplemented from network::KernelEstimator.
Definition at line 103 of file KernelSupervisedEstimator.cpp.
References network::Input::get(), network::KernelEstimator::get(), network::Input::getN(), and network::KernelEstimator::transform.
update()
void network::KernelSupervisedEstimator::update () virtual
Updates the best previous estimated value.
This routine is called after a forward simulation and a backward tuning, and before 1st and 2nd order weight adjustment.
Reimplemented from network::KernelEstimator.
Definition at line 113 of file KernelSupervisedEstimator.cpp.
References network::Input::get(), network::RecurrentTransform::get(), network::Input::getN(), network::RecurrentTransform::getR(), network::Input::getT(), network::KernelTransform::getValueDerivative(), network::RecurrentTransform::reset(), network::KernelEstimator::rho(), network::RecurrentTransform::set(), and network::KernelEstimator::transform.
The documentation for this class was generated from the following files:
src/network/KernelSupervisedEstimator.hpp
src/network/KernelSupervisedEstimator.cpp
mnemosyne brainybot (version of 2017-11-12 at 17:57:54)