Mnemonas'semiware: Density Class Reference
Density Class Reference
Defines a 1D real probabilty density.
#include <Density.hpp>
Public Member Functions
virtual double p (double x) const
Returns the probability for the given value.
Static Public Member Functions
static void setSeed (int seed=-1)
Generates the seed of the pseudo random generator.
static double uniform (double min=0, double max=1)
Generates a uniform random or pseudo random value.
static int uniform (int min, int max)
Generates an integer uniform random or pseudo random value.
static double gaussian (double mean=0, double stdev=1)
Gets a Gaussian random value.
static double getGaussianBias (double bias, double stdev=1)
Gets the Gaussian mean correspondign to a given bias.
static double gamma (unsigned int degree=1, double rate=1)
Gets a Gamma distribution random value.
static bool * booleans (unsigned int size, unsigned int count)
Gets an array of random true values, adjusting the random draw to get an exact number of true value.
Detailed Description
Defines a 1D real probabilty density.
This factory encapsulates random number generators.
All routines depends on setSeed. If setSeed(-1) -> it is a non-reproducible pseudo-random generator, else it generates always the same pseudo-random numbers.
Definition at line 11 of file Density.hpp.
Member Function Documentation
p()
double Density::p (double x) const virtual
Returns the probability for the given value.
Parameters
x The input value.
Returns
A value in [0,1].
Reimplemented in Histogram.
Definition at line 9 of file Density.cpp.
References assume().
Referenced by gamma(), and Histogram::getDivergence().
setSeed()
void Density::setSeed (int seed = -1) static
Generates the seed of the pseudo random generator.
Parameters
seed If seed == -1 changes randomly the seed, else generates a reproducible pseudo random sequence.
Definition at line 18 of file Density.cpp.
References now().
Referenced by network::BufferedInput::BufferedInput(), network::SparseNonLinearTransform::setConnections(), and network::KernelTransform::setWeightsRandom().
uniform() [1/2]
double Density::uniform (double min = 0, double max = 1) static
Generates a uniform random or pseudo random value.
Samples a distribution of mean and standard deviation , i.e., in the interval
Parameters
min Minimal value.
max Maximal value.
Returns
A pseudo random value drawn uniformly between min and max.
Definition at line 29 of file Density.cpp.
Referenced by network::BufferedInput::BufferedInput(), Histogram::draw(), gamma(), gaussian(), Histogram::get(), network::RecurrentTransform::getLyapunovExponent(), network::KernelDistributedEstimator::run(), network::KernelTransform::setWeightsRandom(), and uniform().
uniform() [2/2]
int Density::uniform (int min, int max) static
Generates an integer uniform random or pseudo random value.
Parameters
min Minimal value.
max Maximal value.
Returns
A pseudo random value drawn uniformly in {min, max{, i.e. between min and max excluded.
Definition at line 23 of file Density.cpp.
References uniform().
gaussian()
double Density::gaussian (double mean = 0, double stdev = 1) static
Gets a Gaussian random value.
Parameters
mean The mean value.
stdev The standard-deviation value.
Returns
A random Gaussian variable.
Definition at line 34 of file Density.cpp.
References uniform().
Referenced by network::BufferedInput::BufferedInput(), Histogram::get(), and network::KernelTransform::setWeightsRandom().
getGaussianBias()
double Density::getGaussianBias (double bias, double stdev = 1) static
Gets the Gaussian mean correspondign to a given bias.
Parameters
bias The bias, i.e., the proportion of positive value, between 0 .. 1.
stdev The standard-deviation value.
Returns
The Gaussian mean corresponding to this bias.
Definition at line 39 of file Density.cpp.
gamma()
double Density::gamma (unsigned int degree = 1, double rate = 1) static
Gets a Gamma distribution random value.
Parameters
degree Gamma degree (1 for Poisson).
rate Gamma rate 1 / tau > 0.
Returns
The inter-event interval d, such that t^n+1 = t^n + d
Definition at line 48 of file Density.cpp.
References p(), and uniform().
Referenced by Histogram::get().
booleans()
bool * Density::booleans (unsigned int size, unsigned int count) static
Gets an array of random true values, adjusting the random draw to get an exact number of true value.
Parameters
size Array size.
count Number of true values.
Returns
The bool[size] buffer. To be deleted after use.
Definition at line 62 of file Density.cpp.
References assume().
Referenced by network::SparseNonLinearTransform::setConnections().
The documentation for this class was generated from the following files:
src/util/Density.hpp
src/util/Density.cpp
mnemosyne brainybot (version of 2018-02-25 at 12:12:24)