Mnemonas'semiware: KernelEstimator Class Reference
KernelEstimator Class Reference
Defines a discrete-time recurrent kernel transform estimator.
#include <KernelEstimator.hpp>
Public Member Functions
KernelEstimator (KernelTransform &transform)
Resets the estimator for a given kernel transform.
virtual ~KernelEstimator ()
double run (double criterion_epsilon=1e-6, double weights_epsilon=1e-4, unsigned int maxIterations=100, String dumpDirectory="", String dumpHeader="{}")
Runs the estimation.
const ExponentialDecayFit & getFit () const
Gets the cost decay fit of the last estimation run.
virtual double rho () const
Defines the estimator criterion.
virtual double rho (unsigned int n, double t) const
Defines the estimator criterion.
virtual double drho (unsigned int n, double t) const
Defines the estimator criterion derivative.
virtual void update ()
Updates the best previous estimated value.
virtual double get (unsigned int n, double t) const
Gets the best previous estimated value.
Protected Attributes
KernelTransform & transform
double * values0
double * w0
Detailed Description
Defines a discrete-time recurrent kernel transform estimator.
Definition at line 2 of file KernelEstimator.hpp.
Constructor & Destructor Documentation
KernelEstimator()
KernelEstimator::KernelEstimator (KernelTransform & transform)
Resets the estimator for a given kernel transform.
Parameters
transform The kernel transform to estimate.
The recurrent transform is fully buffered fo the estimation purpose.
Definition at line 3 of file KernelEstimator.cpp.
References KernelTransform::getKernelDimension(), and KernelTransform::getWeightCount().
~KernelEstimator()
KernelEstimator::~KernelEstimator () virtual
Definition at line 21 of file KernelEstimator.cpp.
References RecurrentTransform::get(), KernelTransform::getKernelDimension(), KernelTransform::getWeight(), transform, values0, and w0.
Member Function Documentation
run()
double KernelEstimator::run (double criterion_epsilon = 1e-6, double weights_epsilon = 1e-4, unsigned int maxIterations = 100, String dumpDirectory = "", String dumpHeader = "{}")
Runs the estimation.
Parameters
criterion_epsilon Relative precision on the state values, with respect to the initial cost.
The iteration stops if the criterion decrease is lower than this value.
weights_epsilon Precision on the weight values.
maxIterations The maximal number of iteration.
dumpDirectory A string with the directory name of the estimation dump.
If "stdout" printf on stdout.
An empty string means no dump.
dumpHeader A JSON string with a description of estimation run parameters.
Returns
The normalized minimal cost .
Definition at line 238 of file KernelEstimator.cpp.
References ExponentialDecayFit::add(), ExponentialDecayFit::asString(), ExponentialDecayFit::clear(), now(), s_printf(), s_save(), BufferedInput::save(), ExponentialDecayFit::show(), and transform.
getFit()
const ExponentialDecayFit& KernelEstimator::getFit () const
Gets the cost decay fit of the last estimation run.
Definition at line 52 of file KernelEstimator.hpp.
References drho(), and rho().
rho() [1/2]
double KernelEstimator::rho () const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a global estimator.
The default implementation simply returns , running:
double r = 0;
transform.reset(true);
for(unsigned int t = 0; t < transform.getT(); t++)
  for(int n =  transform.getN() - 1; 0 <= n; n--)
     r += rho(n, t, transform.get(n, t));
return r / (transform.getN() *  transform.getT());
Returns
The criterion value to mnimize.
Reimplemented in KernelObservableEstimator.
Definition at line 62 of file KernelEstimator.cpp.
References Histogram::add(), ExponentialDecayFit::asString(), Histogram::asString(), assume(), drho(), KernelTransform::getKernelDimension(), KernelTransform::getKernelValue(), KernelTransform::getValueDerivative(), KernelTransform::getWeightCount(), solver::linsolve(), solver::minimize(), RecurrentTransform::reset(), s_printf(), KernelTransform::setWeight(), transform, update(), and w0.
Referenced by getFit().
rho() [2/2]
double KernelEstimator::rho (unsigned int n, double t) const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a local estimator.
A typical implementation is of the form:
double network::KernelSupervisedEstimator::rho(unsigned int n, double t) const {
 double value = transform.get(n, t);
 ../..
Parameters
n The input unit index.
t The value time.
Returns
The related positive value to minimize.
Reimplemented in KernelSupervisedEstimator.
Definition at line 288 of file KernelEstimator.cpp.
References assume().
drho()
double KernelEstimator::drho (unsigned int n, double t) const virtual
Defines the estimator criterion derivative.
The method is to be overwritten to implement a given estimator.
Parameters
n The input unit index.
t The value time.
Returns
The value derivative .
Reimplemented in KernelObservableEstimator, and KernelSupervisedEstimator.
Definition at line 293 of file KernelEstimator.cpp.
References assume().
Referenced by getFit(), and rho().
update()
virtual void KernelEstimator::update () virtual
Updates the best previous estimated value.
This routine is called after a forward simulation and a backward tuning, and before 1st and 2nd order weight adjustment.
Reimplemented in KernelSupervisedEstimator.
Definition at line 92 of file KernelEstimator.hpp.
Referenced by rho().
get()
double KernelEstimator::get (unsigned int n, double t) const virtual
Gets the best previous estimated value.
The method is to be overwritten if output values can be provided.
Parameters
n The input unit index.
t The value time.
Reimplemented in KernelSupervisedEstimator.
Definition at line 298 of file KernelEstimator.cpp.
References assume(), and values0.
Member Data Documentation
transform
KernelTransform& KernelEstimator::transform protected
Definition at line 4 of file KernelEstimator.hpp.
Referenced by KernelSupervisedEstimator::drho(), KernelSupervisedEstimator::get(), KernelSupervisedEstimator::rho(), rho(), KernelObservableEstimator::rho(), run(), KernelSupervisedEstimator::update(), and ~KernelEstimator().
values0
double* KernelEstimator::values0 protected
Definition at line 15 of file KernelEstimator.hpp.
Referenced by get(), and ~KernelEstimator().
w0
double * KernelEstimator::w0 protected
Definition at line 15 of file KernelEstimator.hpp.
Referenced by rho(), and ~KernelEstimator().
mnemosyne brainybot (version of 2017-10-15 at 10:00:56)