Mnemonas'semiware: KernelSupervisedEstimator Class Reference
KernelSupervisedEstimator Class Reference
Defines a discrete-time recurrent input/output kernel transform estimator.
#include <KernelSupervisedEstimator.hpp>
Public Member Functions
KernelSupervisedEstimator (KernelTransform &transform, Input &values, char criterion='2', double nu=1e-3, bool reinject=true)
Resets the estimator for a given kernel transform.
virtual ~KernelSupervisedEstimator ()
virtual double rho (unsigned int n, double t) const
Defines the estimator criterion.
virtual double drho (unsigned int n, double t) const
Defines the estimator criterion derivative.
virtual double get (unsigned int n, double t) const
Gets the best previous estimated value.
virtual void update ()
Updates the best previous estimated value.
Public Member Functions inherited from KernelEstimator
KernelEstimator (KernelTransform &transform)
Resets the estimator for a given kernel transform.
virtual ~KernelEstimator ()
double run (double criterion_epsilon=1e-6, double weights_epsilon=1e-4, unsigned int maxIterations=100, String dumpDirectory="", String dumpHeader="{}")
Runs the estimation.
const ExponentialDecayFit & getFit () const
Gets the cost decay fit of the last estimation run.
virtual double rho () const
Defines the estimator criterion.
Additional Inherited Members
Protected Attributes inherited from KernelEstimator
KernelTransform & transform
double * values0
double * w0
Detailed Description
Defines a discrete-time recurrent input/output kernel transform estimator.
Definition at line 2 of file KernelSupervisedEstimator.hpp.
Constructor & Destructor Documentation
KernelSupervisedEstimator()
KernelSupervisedEstimator::KernelSupervisedEstimator (KernelTransform & transform, Input & values, char criterion = '2', double nu = 1e-3, bool reinject = true)
Resets the estimator for a given kernel transform.
Parameters
transform The kernel transform to estimate.
values The output desired values.
By contract output units correspond to the values.getN() lower indexed units and hidden units to the remainder indexes.
criterion The criterion index:
2 The L2 criterion .
1 The reweighted L1 criterion .
0 The reweighted L0 criterion .
a A L1 related unbounded criterion .
If simply considers the absolute value of the error.
b A L0 related biweight bounded criterion .
If simply counts the number of non-zero values.
h The L2 boolean criterion .
If simply counts the number of wrong boolean values (not used as criterion but a posteriori precision).
nu The criterion margin parameter.
reinject If true, uses the desired value in the 2nd order criterion estimation.
Definition at line 3 of file KernelSupervisedEstimator.cpp.
References assume().
~KernelSupervisedEstimator()
KernelSupervisedEstimator::~KernelSupervisedEstimator () virtual
Definition at line 7 of file KernelSupervisedEstimator.cpp.
Member Function Documentation
rho()
double KernelSupervisedEstimator::rho (unsigned int n, double t) const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a local estimator.
A typical implementation is of the form:
double network::KernelSupervisedEstimator::rho(unsigned int n, double t) const {
 double value = transform.get(n, t);
 ../..
Parameters
n The input unit index.
t The value time.
Returns
The related positive value to minimize.
Reimplemented from KernelEstimator.
Definition at line 12 of file KernelSupervisedEstimator.cpp.
References Input::get(), RecurrentTransform::get(), Input::getN(), and KernelEstimator::transform.
drho()
double KernelSupervisedEstimator::drho (unsigned int n, double t) const virtual
Defines the estimator criterion derivative.
The method is to be overwritten to implement a given estimator.
Parameters
n The input unit index.
t The value time.
Returns
The value derivative .
Reimplemented from KernelEstimator.
Definition at line 58 of file KernelSupervisedEstimator.cpp.
References Input::get(), RecurrentTransform::get(), Input::getN(), and KernelEstimator::transform.
get()
double KernelSupervisedEstimator::get (unsigned int n, double t) const virtual
Gets the best previous estimated value.
The method is to be overwritten if output values can be provided.
Parameters
n The input unit index.
t The value time.
Reimplemented from KernelEstimator.
Definition at line 101 of file KernelSupervisedEstimator.cpp.
References Input::get(), Input::getN(), and KernelEstimator::transform.
update()
void KernelSupervisedEstimator::update () virtual
Updates the best previous estimated value.
This routine is called after a forward simulation and a backward tuning, and before 1st and 2nd order weight adjustment.
Reimplemented from KernelEstimator.
Definition at line 111 of file KernelSupervisedEstimator.cpp.
References Input::get(), RecurrentTransform::get(), Input::getN(), RecurrentTransform::getR(), Input::getT(), KernelTransform::getValueDerivative(), RecurrentTransform::reset(), RecurrentTransform::set(), and KernelEstimator::transform.
mnemosyne brainybot (version of 2017-10-15 at 10:00:56)