Mnemonas'semiware: network::SupervisedCriterion Class Reference
network::SupervisedCriterion Class Reference
Defines a discrete-time recurrent input/output suprvised transform criterion.
#include <SupervisedCriterion.hpp>
Public Member Functions
SupervisedCriterion (KernelTransform &transform, Input &values, char criterion='2', double nu=1e-3, char reinject='b')
Resets the criterion for a given transform.
virtual double rho (unsigned int n, double t) const
Defines the estimator criterion.
virtual double drho (unsigned int n, double t) const
Defines the estimator criterion derivative.
virtual double get (unsigned int n, double t) const
Gets the best previous estimated value.
virtual unsigned int getN0 () const
Gets the best previous estimated value number of units.
virtual void update ()
Updates the best previous estimated value.
Public Member Functions inherited from network::TransformCriterion
TransformCriterion (RecurrentTransform &transform)
Resets the estimator for a given kernel transform.
virtual double rho () const
Defines the estimator criterion.
Additional Inherited Members
Protected Attributes inherited from network::TransformCriterion
RecurrentTransform & transform
Detailed Description
Defines a discrete-time recurrent input/output suprvised transform criterion.
Definition at line 3 of file SupervisedCriterion.hpp.
Constructor & Destructor Documentation
SupervisedCriterion()
network::SupervisedCriterion::SupervisedCriterion (network::KernelTransform & transform, Input & values, char criterion = '2', double nu = 1e-3, char reinject = 'b')
Resets the criterion for a given transform.
Parameters
transform The transform to estimate.
values The output desired values.
By contract output units correspond to the values.N lower indexed units and hidden units to the remainder indexes.
criterion The criterion index:
2 The L2 criterion .
1 The reweighted L1 criterion .
0 The reweighted L0 criterion .
a A L1 related unbounded criterion .
If simply considers the absolute value of the error.
b A L0 related biweight bounded criterion .
If simply counts the number of non-zero values.
h The L2 boolean criterion .
If simply counts the number of wrong boolean values (not used as criterion but a posteriori precision).
nu The criterion margin parameter.
reinject Defined how desired values are defined:
'n' : output values are not reinjected as desired values.
'o : output values are reinjected as desired values, other values are not used.
'b' : output values are reinjected and backpropagated on hidden values in order to match the output values.
Definition at line 3 of file SupervisedCriterion.cpp.
References assume().
Member Function Documentation
rho()
double network::SupervisedCriterion::rho (unsigned int n, double t) const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a local estimator.
A typical implementation is of the form:
double network::MyCriterion::rho(unsigned int n, double t) const {
 double value = transform.get(n, t);
 ../..
Parameters
n The input unit index.
t The value time.
Returns
The related positive value to minimize.
Reimplemented from network::TransformCriterion.
Definition at line 8 of file SupervisedCriterion.cpp.
References network::RecurrentTransform::get(), network::Input::get(), network::Input::N, and network::TransformCriterion::transform.
drho()
double network::SupervisedCriterion::drho (unsigned int n, double t) const virtual
Defines the estimator criterion derivative.
The method is to be overwritten to implement a given estimator.
Parameters
n The input unit index.
t The value time.
Returns
The value derivative .
Reimplemented from network::TransformCriterion.
Definition at line 54 of file SupervisedCriterion.cpp.
References network::RecurrentTransform::get(), network::Input::get(), network::Input::N, and network::TransformCriterion::transform.
get()
double network::SupervisedCriterion::get (unsigned int n, double t) const virtual
Gets the best previous estimated value.
The method is to be overwritten if output values can be provided.
Parameters
n The input unit index in {0,N{.
t The value time.
Returns
The best previous estimated value or NAN if undefined.
Reimplemented from network::TransformCriterion.
Definition at line 97 of file SupervisedCriterion.cpp.
References network::Input::get(), network::TransformCriterion::get(), and network::Input::N.
getN0()
unsigned int network::SupervisedCriterion::getN0 () const virtual
Gets the best previous estimated value number of units.
Returns
The number of units for which a best previous estimated value is defined.
Reimplemented from network::TransformCriterion.
Definition at line 107 of file SupervisedCriterion.cpp.
References network::TransformCriterion::getN0(), and network::Input::N.
update()
void network::SupervisedCriterion::update () virtual
Updates the best previous estimated value.
This routine is called after backward tuning, and weight adjustment.
Reimplemented from network::TransformCriterion.
Definition at line 111 of file SupervisedCriterion.cpp.
References network::TransformCriterion::update().
The documentation for this class was generated from the following files:
src/network/SupervisedCriterion.hpp
src/network/SupervisedCriterion.cpp
mnemosyne brainybot (version of 2018-02-26 at 23:51:29)