Mnemonas'semiware: SparseNonLinearTransform Class Reference
SparseNonLinearTransform Class Reference
Defines a recurrent network as a fixed leak sparse rectified linear combination of input and recurrent values.
#include <SparseNonLinearTransform.hpp>
Public Member Functions
SparseNonLinearTransform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
SparseNonLinearTransform & setLeak (double value=0)
Sets a fixed common leak for this network.
SparseNonLinearTransform & setConnections (unsigned int D=0, int seed=-1)
Randomly draws the sparse connections.
~SparseNonLinearTransform ()
KernelTransform & setWeights (KernelTransform &network)
Sets weights from another network of the same type.
unsigned int getKernelDimension (unsigned int n) const
Returns the recurrent kernel dimension.
double getKernelValue (unsigned int n, unsigned int d, double t) const
Returns the recurrent kernel value.
double getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const
Returns the recurrent kernel derivative with respect to a recurrent state value.
Public Member Functions inherited from KernelTransform
KernelTransform (const KernelTransform &transform)
KernelTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
virtual ~KernelTransform ()
void resetWeights ()
Inits the weights.
unsigned int getWeightCount () const
Returns the total number of weights.
double getWeight (unsigned int n, unsigned int d) const
Gets one weight .
virtual bool setWeight (unsigned int n, unsigned int d, double w)
Sets one weight value.
KernelTransform & setWeightsRandom (double mean=0.0, double sigma=0.0, bool add=false, String mode="normal", int seed=-1)
Sets random or constant weights values.
double getValue (unsigned int n, double t) const
Implements the discrete-time recurrent equation.
double getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const
Implements the discrete-time recurrent equation derivative.
std::string asString () const
Returns the weight values as a JSON string.
Public Member Functions inherited from RecurrentTransform
RecurrentTransform (const RecurrentTransform &transform)
RecurrentTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
virtual ~RecurrentTransform ()
RecurrentTransform & reset (bool buffered=false)
Resets the transform buffering.
unsigned int getR () const
Gets the maximal recuurent range.
double get (unsigned int n, double t) const
Returns the input value.
void set (unsigned int n, double t, double value)
Sets an input value of the recurrent equation.
double getValueDerivativeApproximation (unsigned int n, double t, unsigned int n_, double t_, double epsilon=1e-3) const
Calculates the numerical approximate value derivative.
Public Member Functions inherited from Transform
Transform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
const Input & getInput () const
Gets the transform input.
Public Member Functions inherited from Input
Input (unsigned int N, double T)
Resets the input dimensions.
virtual ~Input ()
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
Additional Inherited Members
Static Public Member Functions inherited from KernelTransform
static KernelTransform * newKernelTransform (String type, unsigned int N, const network::Input &input)
Constructs a new KernelTransform of a given implemented type.
Protected Attributes inherited from RecurrentTransform
unsigned int R
unsigned int L
Protected Attributes inherited from Transform
const Input & input
Protected Attributes inherited from Input
unsigned int N
double T
Detailed Description
Defines a recurrent network as a fixed leak sparse rectified linear combination of input and recurrent values.
Such recurrent network writes: Weight organization:
Recurrent weights
Input weights
with .
In order to avoid unbounded values, since using a ReLU profile, a saturation at is introduced.
Definition at line 15 of file SparseNonLinearTransform.hpp.
Constructor & Destructor Documentation
SparseNonLinearTransform()
SparseNonLinearTransform::SparseNonLinearTransform (unsigned int N, const Input & input)
Resets the transform for the given parameters.
Parameters
N The number of input units, defined unit indexes stand in {0, N{.
The network has 2\,N nodes.
input The transform input.
Definition at line 3 of file SparseNonLinearTransform.cpp.
References setConnections(), and setLeak().
~SparseNonLinearTransform()
SparseNonLinearTransform::~SparseNonLinearTransform ()
Definition at line 43 of file SparseNonLinearTransform.cpp.
Member Function Documentation
setLeak()
network::SparseNonLinearTransform & SparseNonLinearTransform::setLeak (double value = 0)
Sets a fixed common leak for this network.
Parameters
value The leak value for all units.
Returns
this.
Definition at line 8 of file SparseNonLinearTransform.cpp.
References assume().
Referenced by SparseNonLinearTransform().
setConnections()
network::SparseNonLinearTransform & SparseNonLinearTransform::setConnections (unsigned int D = 0, int seed = -1)
Randomly draws the sparse connections.
Parameters
D The number of random connections by unit. The 0 default value corresponds to connections.
seed If seed == -1 changes randomly the seed, taking the system time. The initial seed is 0, at the beginning of the program.
Returns
this.
Definition at line 14 of file SparseNonLinearTransform.cpp.
References assume(), random::booleans(), KernelTransform::resetWeights(), and random::setSeed().
Referenced by SparseNonLinearTransform().
setWeights()
network::KernelTransform & SparseNonLinearTransform::setWeights (KernelTransform & network) virtual
Sets weights from another network of the same type.
By contract weights are copied considering the 1st units, if both network do not have the same number of units.
By contract weights are copied if and only if both network are of the same type and each KerneTransform must implement this method and test the type dynamically via construct of the form:
assume(dynamic_cast<$transform-type *>(&network) != NULL, "illegal-argument", "in network::$transform-type::setWeights wrong network type");
.
Parameters
network The weights source network.
Reimplemented from KernelTransform.
Definition at line 47 of file SparseNonLinearTransform.cpp.
References assume().
getKernelDimension()
unsigned int SparseNonLinearTransform::getKernelDimension (unsigned int n) const virtual
Returns the recurrent kernel dimension.
The method is to be overwritten to implement a given transform.
Parameters
n The state unit index in {0, N{.
Returns
the state unit recurrent kernel dimension.
Reimplemented from KernelTransform.
Definition at line 52 of file SparseNonLinearTransform.cpp.
References Input::getN(), and Transform::input.
getKernelValue()
double SparseNonLinearTransform::getKernelValue (unsigned int n, unsigned int d, double t) const virtual
Returns the recurrent kernel value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The time index in {0, T{.
Returns
The corresponding kernel value .
Reimplemented from KernelTransform.
Definition at line 56 of file SparseNonLinearTransform.cpp.
References Input::get(), Input::getN(), and Transform::input.
getKernelDerivative()
double SparseNonLinearTransform::getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const virtual
Returns the recurrent kernel derivative with respect to a recurrent state value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The state time index in {0, T{.
n_ The recurrent unit index in {0, N{.
t_ The recurrent time index in {t-R, t{.
Returns
Returns 0.0 if does not depend on , else .
Reimplemented from KernelTransform.
Definition at line 70 of file SparseNonLinearTransform.cpp.
mnemosyne brainybot (version of 2017-10-15 at 10:00:56)