BrainyBot'semiware: IntegrateAndFireTransform Class Reference
IntegrateAndFireTransform Class Reference
Defines a recurrent network as an approximate integrate and fire transform.
#include <IntegrateAndFireTransform.hpp>
Public Member Functions
IntegrateAndFireTransform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
IntegrateAndFireTransform & setLeak (double value=0)
Sets a fixed common leak for this network.
IntegrateAndFireTransform & setSharpness (double value=1)
Sets a fixed common sharpness for this network.
bool setWeight (unsigned int n, unsigned int d, double w)
Sets one weight value.
unsigned int getKernelDimension (unsigned int n) const
Returns the recurrent kernel dimension.
double getKernelValue (unsigned int n, unsigned int d, double t) const
Returns the recurrent kernel value.
double getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const
Returns the recurrent kernel derivative with respect to a recurrent state value.
Public Member Functions inherited from KernelTransform
KernelTransform (const KernelTransform &transform)
KernelTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
virtual ~KernelTransform ()
unsigned int getWeightCount () const
Returns the total number of weights.
double getWeight (unsigned int n, unsigned int d) const
Gets one weight .
KernelTransform & setWeightsRandom (double mean=0.0, double sigma=0.0, bool add=false, String mode="normal", int seed=-1)
Sets random or constant weights values.
double getValue (unsigned int n, double t) const
Implements the discrete-time recurrent equation.
double getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const
Implements the discrete-time recurrent equation derivative.
std::string asString () const
Returns the weight values as a JSON string.
Public Member Functions inherited from RecurrentTransform
RecurrentTransform (const RecurrentTransform &transform)
RecurrentTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
virtual ~RecurrentTransform ()
RecurrentTransform & reset (bool buffered=false)
Resets the transform buffering.
unsigned int getR () const
Gets the maximal recuurent range.
double get (unsigned int n, double t) const
Returns the input value.
Public Member Functions inherited from Transform
Transform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
const Input & getInput ()
Gets the transform input.
Public Member Functions inherited from Input
Input (unsigned int N, double T)
Resets the input dimensions.
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
Additional Inherited Members
Protected Attributes inherited from RecurrentTransform
unsigned int R
unsigned int L
Protected Attributes inherited from Transform
const Input & input
Protected Attributes inherited from Input
unsigned int N
double T
Detailed Description
Defines a recurrent network as an approximate integrate and fire transform.
Such recurrent network writes: Weight organization:
Unit leak
Recurrent weights
Input weights
Unit sharpness
with .
Definition at line 18 of file IntegrateAndFireTransform.hpp.
Constructor & Destructor Documentation
IntegrateAndFireTransform()
IntegrateAndFireTransform::IntegrateAndFireTransform (unsigned int N, const Input & input)
Resets the transform for the given parameters.
Parameters
N The number of input units, defined unit indexes stand in {0, N{.
The network has 3 N nodes.
input The transform input.
Definition at line 41 of file IntegrateAndFireTransform.hpp.
References setSharpness().
Member Function Documentation
setLeak()
IntegrateAndFireTransform& IntegrateAndFireTransform::setLeak (double value = 0)
Sets a fixed common leak for this network.
Parameters
value The leak value of all , NAN to unconstrain the value, 0 to impose a Heaviside profile.
Returns
this.
Definition at line 50 of file IntegrateAndFireTransform.hpp.
References KernelTransform::setWeight().
setSharpness()
IntegrateAndFireTransform& IntegrateAndFireTransform::setSharpness (double value = 1)
Sets a fixed common sharpness for this network.
Parameters
value The sharpness value of all , NAN to unconstrain the value.
Returns
this.
Definition at line 62 of file IntegrateAndFireTransform.hpp.
References KernelTransform::setWeight().
Referenced by IntegrateAndFireTransform().
setWeight()
bool IntegrateAndFireTransform::setWeight (unsigned int n, unsigned int d, double w) virtual
Sets one weight value.
This routine is to be overloaded if the weights are bounded (e.g. if positive). A typical implementation writes, e.g.:
 bool setWeight(unsigned int n, unsigned int d, double w) {
   // Constraint the weight of idex 0 to be positive
   if (d == 0 && w < 0) {
     setWeight(n, d, 0);
     return false;
   } else
     return setWeight(n, d, d);
 }
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {1, getKernelDimension()}.
w The weight value.
Returns
True if the value is inside the bounds, false if the value has been bounded, i.e. is equal to the bound or outside the bound.
Reimplemented from KernelTransform.
Definition at line 70 of file IntegrateAndFireTransform.hpp.
References KernelTransform::setWeight().
getKernelDimension()
unsigned int IntegrateAndFireTransform::getKernelDimension (unsigned int n) const virtual
Returns the recurrent kernel dimension.
The method is to be overwritten to implement a given transform.
Parameters
n The state unit index in {0, N{.
Returns
the state unit recurrent kernel dimension.
Reimplemented from KernelTransform.
Definition at line 79 of file IntegrateAndFireTransform.hpp.
References Input::getN(), and Transform::input.
getKernelValue()
double IntegrateAndFireTransform::getKernelValue (unsigned int n, unsigned int d, double t) const virtual
Returns the recurrent kernel value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The time index in {0, T{.
Returns
The corresponding kernel value .
Reimplemented from KernelTransform.
Definition at line 83 of file IntegrateAndFireTransform.hpp.
References Input::get(), Input::getN(), and Transform::input.
getKernelDerivative()
double IntegrateAndFireTransform::getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const virtual
Returns the recurrent kernel derivative with respect to a recurrent state value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The state time index in {0, T{.
n_ The recurrent unit index in {0, N{.
t_ The recurrent time index in {t-R, t{.
Returns
Returns 0.0 if does not depend on , else .
Reimplemented from KernelTransform.
Definition at line 100 of file IntegrateAndFireTransform.hpp.
mnemosyne brainybot (version of 2017-06-05 at 15:36:53)