Mnemonas'semiware: network::ObservableCriterion Class Reference
network::ObservableCriterion Class Reference
Defines a discrete-time recurrent input/output kernel transform estimator.
#include <ObservableCriterion.hpp>
Classes
class Observable
Defines an observable over an input.
Public Member Functions
ObservableCriterion (KernelTransform &transform, const Input &input, std::vector< Observable * > observables, const double *lambdas=NULL, bool reinject=false)
Resets the criterion for a given statistics.
ObservableCriterion (KernelTransform &transform, std::vector< Observable * > observables, const double *values, const double *lambdas=NULL, bool reinject=false)
Resets the estimator for a given statistics.
double rho () const
Defines the estimator criterion.
double drho (unsigned int n, double t) const
Defines the estimator criterion derivative.
virtual void update ()
Updates the best previous estimated value.
virtual double get (unsigned int n, double t) const
Gets the best previous estimated value.
virtual unsigned int getN0 () const
Gets the best previous estimated value number of units.
double getObservableExpectedValue (unsigned int k) const
Gets an observable expected value.
Public Member Functions inherited from network::TransformCriterion
TransformCriterion (RecurrentTransform &transform)
Resets the estimator for a given kernel transform.
virtual double rho (unsigned int n, double t) const
Defines the estimator criterion.
Static Public Member Functions
static Observable * getObservable (String name,...)
Gets a predefined observable.
static std::vector< Observable *> getObservables (String name,...)
Gets a predefined observable array.
static void deleteObservables (std::vector< Observable * > &observables)
Deletes a predefined observable array.
Additional Inherited Members
Protected Attributes inherited from network::TransformCriterion
RecurrentTransform & transform
Detailed Description
Defines a discrete-time recurrent input/output kernel transform estimator.
Definition at line 3 of file ObservableCriterion.hpp.
Constructor & Destructor Documentation
ObservableCriterion() [1/2]
network::ObservableCriterion::ObservableCriterion (KernelTransform & transform, const Input & input, std::vector< Observable * > observables, const double * lambdas = NULL, bool reinject = false)
Resets the criterion for a given statistics.
Parameters
transform The kernel transform to estimate.
input The input to consider as a reference.
observables The observables to take into account. They must be deleted after the ObservableCriterion yuse.
lambdas The observables weighted parameters, if any.
reinject If true defined desired values constrained by the observable.
Definition at line 61 of file ObservableCriterion.cpp.
References network::ObservableCriterion::Observable::getValue().
ObservableCriterion() [2/2]
network::ObservableCriterion::ObservableCriterion (KernelTransform & transform, std::vector< Observable * > observables, const double * values, const double * lambdas = NULL, bool reinject = false)
Resets the estimator for a given statistics.
Parameters
transform The kernel transform to estimate.
observables The observables to take into account. They must be deleted after the ObservableCriterion use.
values The observables values.
lambdas The observables weighted parameters, if any.
reinject If true defined desired values constrained by the observable.
Definition at line 38 of file ObservableCriterion.cpp.
References network::Input::T.
Member Function Documentation
rho()
double network::ObservableCriterion::rho () const virtual
Defines the estimator criterion.
The method is to be overwritten to implement a global estimator.
The default implementation simply returns , running:
double r = 0;
transform.reset(true);
for(unsigned int t = 0; t < transform.T; t++)
  for(int n =  transform.N - 1; 0 <= n; n--)
     r += rho(n, t, transform.get(n, t));
return r / (transform.N *  transform.T);
Returns
The criterion value to mnimize.
Reimplemented from network::TransformCriterion.
Definition at line 75 of file ObservableCriterion.cpp.
References network::RecurrentTransform::get(), network::ObservableCriterion::Observable::getValue(), network::Input::N, network::RecurrentTransform::reset(), network::Input::T, and network::TransformCriterion::transform.
drho()
double network::ObservableCriterion::drho (unsigned int n, double t) const virtual
Defines the estimator criterion derivative.
The method is to be overwritten to implement a given estimator.
Parameters
n The input unit index.
t The value time.
Returns
The value derivative .
Reimplemented from network::TransformCriterion.
Definition at line 92 of file ObservableCriterion.cpp.
References network::ObservableCriterion::Observable::getValue().
update()
void network::ObservableCriterion::update () virtual
Updates the best previous estimated value.
This routine is called after backward tuning, and weight adjustment.
Reimplemented from network::TransformCriterion.
Definition at line 114 of file ObservableCriterion.cpp.
References network::RecurrentTransform::get(), network::ObservableCriterion::Observable::getValue(), network::ObservableCriterion::Observable::getValueDerivative(), network::Input::N, solver::projsolve(), network::RecurrentTransform::reset(), network::ObservableCriterion::Observable::reset(), network::RecurrentTransform::set(), network::Input::T, network::TransformCriterion::transform, and network::TransformCriterion::update().
get()
double network::ObservableCriterion::get (unsigned int n, double t) const virtual
Gets the best previous estimated value.
The method is to be overwritten if output values can be provided.
Parameters
n The input unit index in {0,N{.
t The value time.
Returns
The best previous estimated value or NAN if undefined.
Reimplemented from network::TransformCriterion.
Definition at line 106 of file ObservableCriterion.cpp.
References network::Input::N, and network::TransformCriterion::transform.
getN0()
unsigned int network::ObservableCriterion::getN0 () const virtual
Gets the best previous estimated value number of units.
Returns
The number of units for which a best previous estimated value is defined.
Reimplemented from network::TransformCriterion.
Definition at line 110 of file ObservableCriterion.cpp.
getObservableExpectedValue()
double network::ObservableCriterion::getObservableExpectedValue (unsigned int k) const
Gets an observable expected value.
Parameters
k The observable index.
Definition at line 101 of file ObservableCriterion.cpp.
References assume().
getObservable()
network::ObservableCriterion::Observable * network::ObservableCriterion::getObservable (String name, ...) static
Gets a predefined observable.
Parameters
name : The predefined observable name.
mean : The input mean of a given channel .
Parameter: The unit index n.
icorr : The input inter-correlation between two channels .
Parameters: The unit index n and the unit index m.
acorr : The input auto-correlation of a given channel .
Parameters: The unit index n and the delay tau (as unsigned int), with tau = 0, simply returns the 2nd order momentum, tau values above 16 are numericaly unrealistic.
Returns
The corresponding observable, to be deleted after use.
Definition at line 169 of file ObservableCriterion.cpp.
References assume(), and s_printf().
Referenced by getObservables().
getObservables()
std::vector< network::ObservableCriterion::Observable *> network::ObservableCriterion::getObservables (String name, ...) static
Gets a predefined observable array.
Parameters
name : The predefined observable name.
mean : The mean for each channel .
Parameter: The number of channels N, values above 32 are numericaly unrealistic.
icorr : The mean and inter-correlation between two channels .
Parameter: The number of channels N, values above 8 are numericaly unrealistic.
acorr : The mean and auto-correlation for each channel .
Parameter: The number of channels N, and the maximal delay tau (as unsigned int), with tau = 0, simply implements 1st and 2nd order momenta, N * tau values above 32 are numericaly unrealistic..
Returns
The corresponding observables array, each observable are to be deleted with deleteObservables().
Definition at line 255 of file ObservableCriterion.cpp.
References assume(), and getObservable().
deleteObservables()
void network::ObservableCriterion::deleteObservables (std::vector< Observable * > & observables) static
Deletes a predefined observable array.
Parameters
observables The observable array to delete.
Definition at line 296 of file ObservableCriterion.cpp.
The documentation for this class was generated from the following files:
src/network/ObservableCriterion.hpp
src/network/ObservableCriterion.cpp
mnemosyne brainybot (version of 2018-02-23 at 15:42:54)