Mnemonas'semiware: network::RecurrentTransform Class Reference
network::RecurrentTransform Class Reference
Defines a discrete-time recurrent input/output transform.
#include <RecurrentTransform.hpp>
Public Member Functions
RecurrentTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
RecurrentTransform & reset (bool buffered=false, double upsilon=0)
Resets the transform buffering.
unsigned int getR () const
Gets the maximal recurrent range.
double get (unsigned int n, double t) const
Returns the input value.
void set (unsigned int n, double t, double value)
Sets an input value of the recurrent equation.
virtual double getValue (unsigned int n, double t) const
Implements the discrete-time recurrent equation.
virtual double getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const
Implements the discrete-time recurrent equation derivative.
virtual bool isConnected (unsigned int n, double t, unsigned int n_, double t_) const
Checks if two units are connected.
double getValueDerivativeApproximation (unsigned int n, double t, unsigned int n_, double t_, double epsilon=1e-3) const
Calculates the numerical approximate value derivative.
Histogram getLyapunovExponent (unsigned int W=10, unsigned int K=10, double d0=1e-6)
Estimates the Lyapunov exponent.
std::string asString () const
Returns the transform parameters as a JSON string.
double getSpectralRadius ()
Gets the recurrent network spectral radius.
Public Member Functions inherited from network::Transform
Transform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
virtual void setInput (const Input &input)
Sets the transform input.
Public Member Functions inherited from network::Input
Input (unsigned int N, double T)
Resets the input dimensions.
Protected Attributes
unsigned int R
unsigned int L
Additional Inherited Members
Public Attributes inherited from network::Transform
const Input *const input
Gets the transform input.
Public Attributes inherited from network::Input
const unsigned int N
Gets the number of input units.
const double T
Gets the maximal time range.
Protected Member Functions inherited from network::Input
virtual void setN (unsigned int N)
Sets the number of input units.
virtual void setT (double T)
Sets the maximal time range.
Detailed Description
Defines a discrete-time recurrent input/output transform.
Definition at line 3 of file RecurrentTransform.hpp.
Constructor & Destructor Documentation
RecurrentTransform()
network::RecurrentTransform::RecurrentTransform (unsigned int N, unsigned int R, const Input & input)
Resets the transform for the given parameters.
Parameters
N The number of output units, defined unit indexes stand in {0, N{.
R The maximal recurrent time range, at a current time t, defined times stand in [t+0, t+R[.
input The transform input.
Definition at line 3 of file RecurrentTransform.cpp.
References network::Transform::input, L, R, reset(), and network::Transform::setInput().
Member Function Documentation
reset()
network::RecurrentTransform & network::RecurrentTransform::reset (bool buffered = false, double upsilon = 0)
Resets the transform buffering.
The current time is reset to 0.
Parameters
buffered If true all input.T are buffered, else only R+1 are buffered.
upsilon Standard-deviation of the initial conditions normal random values.
Returns
this.
Definition at line 18 of file RecurrentTransform.cpp.
References assume(), L, network::Input::N, R, and network::Input::T.
Referenced by getSpectralRadius(), RecurrentTransform(), network::TransformCriterion::rho(), network::ObservableCriterion::rho(), network::ObservableCriterion::update(), and network::TransformCriterion::update().
getR()
unsigned int network::RecurrentTransform::getR () const
Gets the maximal recurrent range.
Definition at line 33 of file RecurrentTransform.hpp.
References asString(), getLyapunovExponent(), getSpectralRadius(), getValue(), getValueDerivative(), getValueDerivativeApproximation(), isConnected(), and R.
Referenced by network::TransformCriterion::update().
get()
double network::RecurrentTransform::get (unsigned int n, double t) const virtual
Returns the input value.
The method is to be overwritten to implement a given input.
Parameters
n The input unit index.
t The value time.
Returns
The input value if defined, else raises a fatal error.
Reimplemented from network::Input.
Definition at line 46 of file RecurrentTransform.cpp.
References assume(), getValue(), L, and network::Input::N.
Referenced by network::SupervisedCriterion::drho(), network::SupervisedCriterion::rho(), network::ObservableCriterion::rho(), network::KernelEstimator::run(), network::ObservableCriterion::update(), and network::TransformCriterion::update().
set()
void network::RecurrentTransform::set (unsigned int n, double t, double value)
Sets an input value of the recurrent equation.
Parameters
n The input unit index.
t The value time.
value The enforced input value.
Definition at line 73 of file RecurrentTransform.cpp.
References assume(), L, and network::Input::N.
Referenced by network::ObservableCriterion::update(), network::TransformCriterion::update(), and network::KernelEstimator::updateReadout().
getValue()
double network::RecurrentTransform::getValue (unsigned int n, double t) const virtual
Implements the discrete-time recurrent equation.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Returns
The input value if defined, else raises a fatal error.
It calculates ,
Reimplemented in network::KernelTransform.
Definition at line 31 of file RecurrentTransform.cpp.
References assume().
Referenced by get(), getR(), and getValueDerivativeApproximation().
getValueDerivative()
double network::RecurrentTransform::getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const virtual
Implements the discrete-time recurrent equation derivative.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Parameters
n_ The afferent input unit index denominator.
t_ The value time denominator.
Returns
The input value derivate if defined, 0 in the abscence of dependence, else raises a fatal error.
If the recurrent equation writes , this method returns: ,
Reimplemented in network::KernelTransform.
Definition at line 36 of file RecurrentTransform.cpp.
References assume().
Referenced by getR(), getSpectralRadius(), getValueDerivativeApproximation(), and network::TransformCriterion::update().
isConnected()
bool network::RecurrentTransform::isConnected (unsigned int n, double t, unsigned int n_, double t_) const virtual
Checks if two units are connected.
The method is to be overwritten to implement sparse connected networks.
Parameters
n The efferent input unit index.
t The efferent input unit current time.
n_ The afferent input unit index denominator.
t_ The afferent input unit current time.
Returns
False if the unit of index n_ never connects to the unit of index n, for the given times, true if the connection is to be checked via getValueDerivative()
Reimplemented in network::IntegrateAndFireTransform, network::LinearNonLinearTransform, network::SparseNonLinearTransform, network::SoftMaxTransform, and network::LinearTransform.
Definition at line 41 of file RecurrentTransform.cpp.
References assume().
Referenced by getR(), and network::KernelEstimator::run().
getValueDerivativeApproximation()
double network::RecurrentTransform::getValueDerivativeApproximation (unsigned int n, double t, unsigned int n_, double t_, double epsilon = 1e-3) const
Calculates the numerical approximate value derivative.
This is only used for debugging purpose to check the coherence between getValue() and getValureDerivative().
Parameters
n The input unit index.
t The value time.
n_ The input unit index denominator.
t_ The value time denominator.
epsilon The finite difference epsilon.
Returns
The input value derivate approximation:
Definition at line 79 of file RecurrentTransform.cpp.
References assume(), network::KernelTransform::getKernelDerivative(), network::KernelTransform::getKernelDimension(), network::KernelTransform::getKernelValue(), getValue(), network::KernelTransform::getValue(), getValueDerivative(), L, and network::Input::N.
Referenced by getR().
getLyapunovExponent()
Histogram network::RecurrentTransform::getLyapunovExponent (unsigned int W = 10, unsigned int K = 10, double d0 = 1e-6)
Estimates the Lyapunov exponent.
Performs M simulations until t = T - W, adds a perturation and estimates the trajectory divergence.
Parameters
W The Lyapunov exponent estimation window.
K The number of iterations.
d0 The perturbation amplitude.
Returns
The estimated statistic of .
Definition at line 114 of file RecurrentTransform.cpp.
References Histogram::add(), assume(), network::BufferedInput::get(), network::Input::N, network::Input::T, and Density::uniform().
Referenced by getR().
asString()
std::string network::RecurrentTransform::asString () const
Returns the transform parameters as a JSON string.
Definition at line 157 of file RecurrentTransform.cpp.
References L, network::Input::N, R, s_printf(), and network::Input::T.
Referenced by network::KernelTransform::asString(), and getR().
getSpectralRadius()
double network::RecurrentTransform::getSpectralRadius ()
Gets the recurrent network spectral radius.
Computes the system Jacobian between t = R+1 and t = R, applying the power method.
Definition at line 142 of file RecurrentTransform.cpp.
References solver::getSpectralRadius(), getValueDerivative(), network::Input::N, R, and reset().
Referenced by getR().
Member Data Documentation
R
unsigned int network::RecurrentTransform::R protected
Definition at line 11 of file RecurrentTransform.hpp.
Referenced by asString(), getR(), getSpectralRadius(), RecurrentTransform(), reset(), and network::KernelTransform::resetWeights().
L
unsigned int network::RecurrentTransform::L protected
Definition at line 11 of file RecurrentTransform.hpp.
Referenced by asString(), get(), getValueDerivativeApproximation(), RecurrentTransform(), reset(), and set().
The documentation for this class was generated from the following files:
src/network/RecurrentTransform.hpp
src/network/RecurrentTransform.cpp
mnemosyne brainybot (version of 2018-03-29 at 18:20:28)