BrainyBot'semiware: Struct::Iterator Class Reference
Struct::Iterator Class Reference
Defines an iterator over the struct named fields.
#include <Struct.hpp>
Public Member Functions
Iterator (const Struct &value)
Constructs an iterator over the struct named fields.
String getName () const
Returns the current name if any, else the result is undefined.
Struct & getValue () const
Returns the current value if any, else the result is undefined.
int getIndex () const
Returns the current name index, starting from 0 up to getCount()-1.
bool next ()
Returns true if there is another element, enumerating a new element at each call.
Detailed Description
Defines an iterator over the struct named fields.
It is used in a construct of the form:
for(Struct::Iterator i(values); i.next();) { String name = i.getName(); Struct &value = i.getValue(); ../.. }.
It does not iterate over the indexed values, which is realized using a construct of the form:
for(int i = 0; i < values.getLength(); i++) { Struct &value = values[i]; ../.. }.
Definition at line 207 of file Struct.hpp.
Constructor & Destructor Documentation
Iterator()
Struct::Iterator::Iterator (const Struct & value)
Constructs an iterator over the struct named fields.
Parameters
value The logical-structure to iterate on.
Definition at line 216 of file Struct.hpp.
Member Function Documentation
getName()
String Struct::Iterator::getName () const
Returns the current name if any, else the result is undefined.
Definition at line 220 of file Struct.hpp.
Referenced by getValue().
getValue()
Struct& Struct::Iterator::getValue () const
Returns the current value if any, else the result is undefined.
Definition at line 225 of file Struct.hpp.
References getName().
getIndex()
int Struct::Iterator::getIndex () const
Returns the current name index, starting from 0 up to getCount()-1.
Definition at line 230 of file Struct.hpp.
next()
bool Struct::Iterator::next ()
Returns true if there is another element, enumerating a new element at each call.
Definition at line 235 of file Struct.hpp.
References Struct::equals().
Referenced by Struct::asString().
mnemosyne brainybot (version of 2017-06-05 at 15:48:38)