Mnemonas'semiware: KernelTransform Class Reference
KernelTransform Class Reference
Defines a discrete-time recurrent input/output kernel transform.
#include <KernelTransform.hpp>
Public Member Functions
KernelTransform (const KernelTransform &transform)
KernelTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
virtual ~KernelTransform ()
virtual unsigned int getKernelDimension (unsigned int n) const
Returns the recurrent kernel dimension.
virtual double getKernelValue (unsigned int n, unsigned int d, double t) const
Returns the recurrent kernel value.
virtual double getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const
Returns the recurrent kernel derivative with respect to a recurrent state value.
unsigned int getWeightCount () const
Returns the total number of weights.
double getWeight (unsigned int n, unsigned int d) const
Gets one weight .
virtual bool setWeight (unsigned int n, unsigned int d, double w)
Sets one weight value.
KernelTransform & setWeightsRandom (double mean=0.0, double sigma=0.0, bool add=false, String mode="normal", int seed=-1)
Sets random or constant weights values.
double getValue (unsigned int n, double t) const
Implements the discrete-time recurrent equation.
double getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const
Implements the discrete-time recurrent equation derivative.
std::string asString () const
Returns the weight values as a JSON string.
Public Member Functions inherited from RecurrentTransform
RecurrentTransform (const RecurrentTransform &transform)
RecurrentTransform (unsigned int N, unsigned int R, const Input &input)
Resets the transform for the given parameters.
virtual ~RecurrentTransform ()
RecurrentTransform & reset (bool buffered=false)
Resets the transform buffering.
unsigned int getR () const
Gets the maximal recuurent range.
double get (unsigned int n, double t) const
Returns the input value.
Public Member Functions inherited from Transform
Transform (unsigned int N, const Input &input)
Resets the transform for the given parameters.
const Input & getInput ()
Gets the transform input.
Public Member Functions inherited from Input
Input (unsigned int N, double T)
Resets the input dimensions.
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
Additional Inherited Members
Protected Attributes inherited from RecurrentTransform
unsigned int R
unsigned int L
Protected Attributes inherited from Transform
const Input & input
Protected Attributes inherited from Input
unsigned int N
double T
Detailed Description
Defines a discrete-time recurrent input/output kernel transform.
A recurrent transform of the form for and : with:
nodes of value indexed by ,
with a maximal state recurrent range of , (i.e., taking into account recurrent value up to time-steps in the past),
and initial condition ;
of these nodes are output;
input indexed by ,
with a maximal input recurrent range of , ,
and initial condition ;
The node structure is defined by predefined kernels for each node;
The node parameters are static adjustable weights .
Definition at line 15 of file KernelTransform.hpp.
Constructor & Destructor Documentation
KernelTransform() [1/2]
KernelTransform::KernelTransform (const KernelTransform & transform)
Definition at line 4 of file KernelTransform.cpp.
KernelTransform() [2/2]
KernelTransform::KernelTransform (unsigned int N, unsigned int R, const Input & input)
Resets the transform for the given parameters.
Parameters
N The number of input units, defined unit indexes stand in {0, N{.
R The maximal recurrent time range, at a current time t, defined times stand in [t+0, t+R[.
input The transform input.
Definition at line 8 of file KernelTransform.cpp.
References getKernelDimension(), and Input::N.
~KernelTransform()
KernelTransform::~KernelTransform () virtual
Definition at line 21 of file KernelTransform.cpp.
Member Function Documentation
getKernelDimension()
virtual unsigned int KernelTransform::getKernelDimension (unsigned int n) const virtual
Returns the recurrent kernel dimension.
The method is to be overwritten to implement a given transform.
Parameters
n The state unit index in {0, N{.
Returns
the state unit recurrent kernel dimension.
Reimplemented in IntegrateAndFireTransform, LinearNonLinearTransform, SoftMaxTransform, and LinearTransform.
Definition at line 42 of file KernelTransform.hpp.
References assume().
Referenced by asString(), getValue(), getValueDerivative(), getWeight(), KernelEstimator::KernelEstimator(), KernelTransform(), setWeight(), setWeightsRandom(), and KernelEstimator::~KernelEstimator().
getKernelValue()
virtual double KernelTransform::getKernelValue (unsigned int n, unsigned int d, double t) const virtual
Returns the recurrent kernel value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The time index in {0, T{.
Returns
The corresponding kernel value .
Reimplemented in IntegrateAndFireTransform, LinearNonLinearTransform, SoftMaxTransform, and LinearTransform.
Definition at line 56 of file KernelTransform.hpp.
References assume().
Referenced by getValue(), and KernelEstimator::~KernelEstimator().
getKernelDerivative()
virtual double KernelTransform::getKernelDerivative (unsigned int n, unsigned int d, double t, unsigned int n_, double t_) const virtual
Returns the recurrent kernel derivative with respect to a recurrent state value.
The method is to be overwritten to implement a given transform.
The method uses input.get() and get() to get the related input or state values.
The method has not to be protected against illegal-argument, since invoked by a safe method.
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {0, getKernelDimension(n)}.
t The state time index in {0, T{.
n_ The recurrent unit index in {0, N{.
t_ The recurrent time index in {t-R, t{.
Returns
Returns 0.0 if does not depend on , else .
Reimplemented in IntegrateAndFireTransform, LinearNonLinearTransform, SoftMaxTransform, and LinearTransform.
Definition at line 72 of file KernelTransform.hpp.
References assume().
Referenced by getValueDerivative(), and KernelEstimator::~KernelEstimator().
getWeightCount()
unsigned int KernelTransform::getWeightCount () const
Returns the total number of weights.
Returns
>_n getKernelDimension(n)
Definition at line 80 of file KernelTransform.hpp.
Referenced by KernelEstimator::~KernelEstimator().
getWeight()
double KernelTransform::getWeight (unsigned int n, unsigned int d) const
Gets one weight .
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {1, getKernelDimension()}.
Returns
The weight value.
Definition at line 89 of file KernelTransform.hpp.
References getKernelDimension().
Referenced by asString(), getValue(), getValueDerivative(), setWeightsRandom(), and KernelEstimator::~KernelEstimator().
setWeight()
virtual bool KernelTransform::setWeight (unsigned int n, unsigned int d, double w) virtual
Sets one weight value.
This routine is to be overloaded if the weights are bounded (e.g. if positive). A typical implementation writes, e.g.:
 bool setWeight(unsigned int n, unsigned int d, double w) {
   // Constraint the weight of idex 0 to be positive
   if (d == 0 && w < 0) {
     setWeight(n, d, 0);
     return false;
   } else
     return setWeight(n, d, d);
 }
Parameters
n The state unit index in {0, N{.
d The recurrent kernel index in {1, getKernelDimension()}.
w The weight value.
Returns
True if the value is inside the bounds, false if the value has been bounded, i.e. is equal to the bound or outside the bound.
Reimplemented in IntegrateAndFireTransform, LinearNonLinearTransform, and SoftMaxTransform.
Definition at line 109 of file KernelTransform.hpp.
References asString(), assume(), getKernelDimension(), getValue(), getValueDerivative(), and setWeightsRandom().
Referenced by LinearNonLinearTransform::setLeak(), IntegrateAndFireTransform::setLeak(), SoftMaxTransform::setOffset(), LinearNonLinearTransform::setOffset(), IntegrateAndFireTransform::setSharpness(), SoftMaxTransform::setWeight(), LinearNonLinearTransform::setWeight(), IntegrateAndFireTransform::setWeight(), and setWeightsRandom().
setWeightsRandom()
network::KernelTransform & KernelTransform::setWeightsRandom (double mean = 0.0, double sigma = 0.0, bool add = false, String mode = "normal", int seed = -1)
Sets random or constant weights values.
Weights are drawn from either a uniform or a normal distribution.
If sigma = 0, it sets or adds to the weights a fixed value.
The uniform distribution stands in the interval.
Parameters
mean The distribution mean.
sigma The distribution standard-deviation.
add If true adds the random noise to existing values, else replaces values by the noise.
mode Either "uniform" or "normal" distribution.
seed If seed == -1 changes randomly the seed, taking the system time. The initial seed is 0, at the beginning of the program.
Returns
this.
Definition at line 26 of file KernelTransform.cpp.
References random::gaussian(), getKernelDimension(), getWeight(), Input::N, random::setSeed(), setWeight(), and random::uniform().
Referenced by setWeight().
getValue()
double KernelTransform::getValue (unsigned int n, double t) const virtual
Implements the discrete-time recurrent equation.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Returns
The input value if defined, else raises a fatal error.
It calculates ,
Reimplemented from RecurrentTransform.
Definition at line 49 of file KernelTransform.cpp.
References getKernelDimension(), getKernelValue(), and getWeight().
Referenced by setWeight().
getValueDerivative()
double KernelTransform::getValueDerivative (unsigned int n, double t, unsigned int n_, double t_) const virtual
Implements the discrete-time recurrent equation derivative.
The method is to be overwritten to implement a given transform.
Parameters
n The input unit index.
t The value time.
Recurrent values at time t', t - R <= t' < t can be called.
Parameters
n_ The input unit index denominator.
t_ The value time denominator.
Returns
The input value derivate if defined, 0 in the abscence of dependence, else raises a fatal error.
If the recurrent equation writes , this method returns: ,
Reimplemented from RecurrentTransform.
Definition at line 56 of file KernelTransform.cpp.
References getKernelDerivative(), getKernelDimension(), and getWeight().
Referenced by setWeight().
asString()
std::string KernelTransform::asString () const
Returns the weight values as a JSON string.
Definition at line 38 of file KernelTransform.cpp.
References getKernelDimension(), getWeight(), Input::N, and s_printf().
Referenced by setWeight().
mnemosyne brainybot (version of 2017-06-05 at 15:53:04)