Mnemonas'semiware: network::KernelObservableEstimator::Observable Class Reference
network::KernelObservableEstimator::Observable Class Reference
Defines an observable over an input.
#include <KernelObservableEstimator.hpp>
Public Member Functions
Observable (String name)
Constructs an observable of the given name.
std::string asString () const
Gets the observable name and value.
Observable & reset (const Input &input)
Resets the observable for a given input.
double getValue () const
Gets the observable value expectation, given the measures.
double getValueDerivative (unsigned int n, double t) const
Gets the local observable derivative.
Protected Member Functions
virtual double doValue ()
Calculates and returns the observable value expectation, given the measures.
virtual double doValueDerivative (unsigned int n, double t)
Calculates and returns the observable derivative.
Protected Attributes
const Input * input
This is used to implement the getValueDerivative().
Detailed Description
Defines an observable over an input.
By contract:
Observable must implement an implicit or explicit copy constructor.
The doValue() and doValueDerivative() methods implements a particular observable.
Definition at line 10 of file KernelObservableEstimator.hpp.
Constructor & Destructor Documentation
Observable()
network::KernelObservableEstimator::Observable::Observable (String name)
Constructs an observable of the given name.
Definition at line 4 of file KernelObservableEstimator.cpp.
Member Function Documentation
asString()
std::string network::KernelObservableEstimator::Observable::asString () const
Gets the observable name and value.
Definition at line 14 of file KernelObservableEstimator.cpp.
References s_printf().
reset()
network::KernelObservableEstimator::Observable & network::KernelObservableEstimator::Observable::reset (const Input & input)
Resets the observable for a given input.
This reset() method must be called prior to the getValue() or getValueDerivative() method.
Parameters
input The input to observe in the input temporal range.
Returns
this;
Definition at line 8 of file KernelObservableEstimator.cpp.
References doValue(), and input.
getValue()
double network::KernelObservableEstimator::Observable::getValue () const
Gets the observable value expectation, given the measures.
Definition at line 18 of file KernelObservableEstimator.cpp.
References assume(), and input.
Referenced by network::KernelObservableEstimator::drho(), network::KernelObservableEstimator::KernelObservableEstimator(), and network::KernelObservableEstimator::rho().
getValueDerivative()
double network::KernelObservableEstimator::Observable::getValueDerivative (unsigned int n, double t) const
Gets the local observable derivative.
Parameters
n The unit index.
t The time index.
Definition at line 23 of file KernelObservableEstimator.cpp.
References assume(), doValueDerivative(), and input.
doValue()
double network::KernelObservableEstimator::Observable::doValue () protected virtual
Calculates and returns the observable value expectation, given the measures.
Typical implementation writes :
  reset_the_calculation();
 for(unsigned int t = 0; t < input->getT(); t++)
   add_new_values(t);
 return finalize_the_calculation();
Definition at line 28 of file KernelObservableEstimator.cpp.
References assume().
Referenced by reset().
doValueDerivative()
double network::KernelObservableEstimator::Observable::doValueDerivative (unsigned int n, double t) protected virtual
Calculates and returns the observable derivative.
Typical implementation uses input->get(n, t) to calculate the local observable derivative.
Parameters
n The unit index.
t The time index.
Definition at line 33 of file KernelObservableEstimator.cpp.
References assume().
Referenced by getValueDerivative().
Member Data Documentation
input
const Input* network::KernelObservableEstimator::Observable::input protected
This is used to implement the getValueDerivative().
Definition at line 15 of file KernelObservableEstimator.hpp.
Referenced by getValue(), getValueDerivative(), and reset().
The documentation for this class was generated from the following files:
src/network/KernelObservableEstimator.hpp
src/network/KernelObservableEstimator.cpp
mnemosyne brainybot (version of 2017-11-12 at 17:57:54)