Mnemonas'semiware: Histogram Class Reference
Histogram Class Reference
Defines an 1D statistics on a set of scalar values.
#include <Histogram.hpp>
Public Member Functions
Histogram (unsigned int samples=0, double min=NAN, double max=NAN)
Defines an histogram for a given observation.
void clear ()
Clears all added values.
void add (double value)
Adds a value to the statistics.
double get (String value, double v=NAN) const
Gets a statistical value.
double p (double x) const
Returns the probability for the given value.
double draw () const
Draws a sample from the present statistics.
double getDivergence (const Density &density, bool inverse=false) const
Gets the Kullback-Leibler divergence between this empirical distribution and another probality density.
const Density & getDensityModel (String model="automatic") const
Gets a theoretical density with the same 1st and 2nd order parameters as this one.
std::string asString (String what="", bool oneline=false) const
Returns all statistical values as a JSON string.
void plot (String file, String model="", bool show=false)
Plots the histogram in a file.
Static Public Member Functions
static void plot (String file, const std::vector< Histogram > &histograms, double x0=0, double x1=1, bool show=false)
Plots histograms mean and standard deviations as a curve.
static void plot (String file, const std::map< std::string, Histogram > &histograms, bool show=false)
Plots histograms as statistical boxes.
Static Public Member Functions inherited from Density
static void setSeed (int seed=-1)
Generates the seed of the pseudo random generator.
static double uniform (double min=0, double max=1)
Generates a uniform random or pseudo random value.
static int uniform (int min, int max)
Generates an integer uniform random or pseudo random value.
static double gaussian (double mean=0, double stdev=1)
Gets a Gaussian random value.
static double getGaussianBias (double bias, double stdev=1)
Gets the Gaussian mean correspondign to a given bias.
static double gamma (unsigned int degree=1, double rate=1)
Gets a Gamma distribution random value.
static bool * booleans (unsigned int size, unsigned int count)
Gets an array of random true values, adjusting the random draw to get an exact number of true value.
Detailed Description
Defines an 1D statistics on a set of scalar values.
Definition at line 13 of file Histogram.hpp.
Constructor & Destructor Documentation
Histogram()
Histogram::Histogram (unsigned int samples = 0, double min = NAN, double max = NAN)
Defines an histogram for a given observation.
Parameters
samples The histogram size (if 0 there is no histogram, only momenta calculation).
min The minimal expected value.
max The maximal expected value.
Definition at line 44 of file Histogram.cpp.
References assume(), and clear().
Member Function Documentation
clear()
void Histogram::clear ()
Clears all added values.
Definition at line 78 of file Histogram.cpp.
Referenced by Histogram().
add()
void Histogram::add (double value)
Adds a value to the statistics.
Definition at line 87 of file Histogram.cpp.
References assume().
Referenced by CurveFit::getHistogram(), network::BufferedInput::getHistogram(), network::RecurrentTransform::getLyapunovExponent(), and network::KernelExperimentalEstimator::KernelExperimentalEstimator().
get()
double Histogram::get (String value, double v = NAN) const
Gets a statistical value.
Parameters
value : As a function of the sample momenta:
"count" : the number of observed values.
"min" : the observed minimal value.
"max" : the observed maximal value.
"mean" : the mean value.
"stdev" : the standard-deviation . (2nd order).
Returns an unbiased estimator of the theoretical standard-deviation E[(x-m)^2]^(1/2) (Any standard-deviation lower than DBL_EPSILON (1e-15) is set to 0).
"skew" : the skewness (3rd order).
Returns an estimator of the theoretical skewness skewness E[(x - m)^3 / stdev^3], given by n / ((n-1)(n-2)) >_i (x_i-m)^3/s^3 (Skewness is zero for symmetric distributions).
"kurt" : the kurtosis (4th order).
An estimator of the theoretical kurtosis kurtosis E[(x - m)^4 / stdev^4] - 3, given by n (n+1) / ((n-1)(n-2)(n-3)) >_i (x_i-m)^4/s^4 - 3 * (n-1)^2/((n-2)(n-3)) (Kurtosis is equal to 0 for the Gaussian distribution).
"gamma-degree" : the degree of a Gamma distribution, with the same mean and variance as the empirical distribution.
Returns the degree d >= 1 or 0 if undefined, assuming that the probability distribution has the form p(t) = (t / tau)^(d - 1) exp(-t / tau) / (tau d!) e.g., d = 1 for a Poisson distribution.
"gamma-rate" : the rate of a Gamma distribution, with the same mean and variance as the empirical distribution.
Returns the rate tau >= 1 or 0 if undefined, assuming a Gamma distribution as above.
"uniform-entropy" : the entropy of a uniform distribution with the same mean and variance.
"gaussian-entropy" : the entropy of a Gaussian distribution with the same mean and variance. As a function of the histogram:
"hsize" : the histogram sampling size.
"density" : the observed probability for value v. It returns the value of Histogram::p().
"mode" : the mode value, i.e. the most frequent value.
"quantile" : The median corresponds to the quantile for v = 0.5. The quartiles to the quantiles for v = 0.25 and 0.75.
"entropy" : The distribution entropy, in bits, i.e. using .
We use the approximation: , where is the probability of the -th box of size .
"uniform-divergence" : The Kullback-Leibler divergence between the empirical distribution and a uniform distribution having the same mean and variance. If v < 0 computes the inverse divergence.
"gaussian-divergence" : The Kullback-Leibler divergence between the empirical distribution and a Gaussian distribution having the same mean and variance. If v < 0 computes the inverse divergence.
"gamma-divergence" : The Kullback-Leibler divergence between the empirical distribution and a Gamma distribution having the same mean and variance. If v < 0 computes the inverse divergence.
"best-model" Estimates the best model comparing divergences:
1 : "gaussian",
2 : "gamma",
0 : "uniform" as a fallback option.
v An optional additional parameter depending of the defined value.
Definition at line 100 of file Histogram.cpp.
References assume(), Density::gamma(), Density::gaussian(), getDensityModel(), getDivergence(), p(), and Density::uniform().
p()
double Histogram::p (double x) const virtual
Returns the probability for the given value.
Parameters
x The input value.
Returns
A value in [0,1].
Reimplemented from Density.
Definition at line 79 of file Histogram.hpp.
References asString(), draw(), getDensityModel(), getDivergence(), and plot().
Referenced by get(), getDensityModel(), and getDivergence().
draw()
double Histogram::draw () const
Draws a sample from the present statistics.
Definition at line 261 of file Histogram.cpp.
References assume(), and Density::uniform().
Referenced by p().
getDivergence()
double Histogram::getDivergence (const Density & density, bool inverse = false) const
Gets the Kullback-Leibler divergence between this empirical distribution and another probality density.
The Kullback–Leibler divergence d(p||q) = >_w p ln(p/q), where p is the empirical distribution and q the model distribution corresponds to the average number of bits difference when coding p with q.
Parameters
density The other distribution density.
inverse
If false p is this distribution, empirical, and density is the q model distribution.
If true q is this distribution, the model, and density is the pempirical distribution.
Returns
The Kullback-Leibler divergence in bits.
Definition at line 246 of file Histogram.cpp.
References assume(), Density::p(), and p().
Referenced by get(), and p().
getDensityModel()
const Density & Histogram::getDensityModel (String model = "automatic") const
Gets a theoretical density with the same 1st and 2nd order parameters as this one.
Parameters
model Either uniform, gaussian, gamma or automatic (i.e. automatically choose the best model among the others).
Definition at line 267 of file Histogram.cpp.
References assume(), and p().
Referenced by get(), p(), and plot().
asString()
std::string Histogram::asString (String what = "", bool oneline = false) const
Returns all statistical values as a JSON string.
Parameters
what The list of value to return, by default all values are returned.
oneline If true returns the result a 1D line, else returns a 2D format.
Definition at line 325 of file Histogram.cpp.
References s_printf().
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), and p().
plot() [1/3]
void Histogram::plot (String file, String model = "", bool show = false)
Plots the histogram in a file.
Parameters
file The plot file name, a gnuplot display data, script and image files are generated, with extensions .dat, .gnuplot.sh and .png.
model If not empty, also draw the corresponding model, either uniform, gaussian, gamma or automatic (i.e. automatically choose the best model among the others).
show If true performs on the fly display.
Definition at line 362 of file Histogram.cpp.
References assume(), getDensityModel(), gnuplot(), s_printf(), and s_save().
Referenced by p().
plot() [2/3]
void Histogram::plot (String file, const std::vector< Histogram > & histograms, double x0 = 0, double x1 = 1, bool show = false) static
Plots histograms mean and standard deviations as a curve.
Parameters
file The plot file name, a gnuplot display data, script and image files are generated, with extensions .dat, .gnuplot.sh and .png.
histograms An array of histograms.
x0 The abcissa of histograms[0].
x1 The abcissa of histograms[histograms.size()-1].
show If true performs on the fly display.
Definition at line 377 of file Histogram.cpp.
References gnuplot(), s_printf(), and s_save().
plot() [3/3]
void Histogram::plot (String file, const std::map< std::string, Histogram > & histograms, bool show = false) static
Plots histograms as statistical boxes.
Parameters
file The plot file name, a gnuplot display data, script and image files are generated, with extensions .dat, .gnuplot.sh and .png.
histograms An array of histograms.
show If true performs on the fly display.
Definition at line 389 of file Histogram.cpp.
References gnuplot(), s_printf(), and s_save().
The documentation for this class was generated from the following files:
src/util/Histogram.hpp
src/util/Histogram.cpp
mnemosyne brainybot (version of 2018-02-25 at 11:28:53)