Mnemonas'semiware: BufferedInput Class Reference
BufferedInput Class Reference
Defines a static buffered input of a calculation network.
#include <BufferedInput.hpp>
Public Member Functions
BufferedInput (const BufferedInput &input)
BufferedInput (const double *values, unsigned int N, unsigned int T)
Resets the input with static values.
BufferedInput (unsigned int N)
Resets the input with static variable time length values.
void add (const double *value)
Adds a value if (and only if) this is a variable time length buffer.
BufferedInput (const Input &input, double f(const Input &input, unsigned int n, unsigned int t), unsigned int N0=0)
Resets the input from another input with a predefined function.
BufferedInput (const Input &input, unsigned int N0=0)
BufferedInput (double f(unsigned int n, unsigned int t), unsigned int N, unsigned int T)
Resets the input from a predefined function.
BufferedInput (String file, String format="binary-unit-time")
Resets the input with values loaded from a file.
BufferedInput (String name, unsigned int N, unsigned int T,...)
Resets the input with predefined values.
BufferedInput (const Input &input, String name,...)
Resets the input applying a predefined transformation on another input.
virtual ~BufferedInput ()
double get (unsigned int n, double t) const
Returns the input value.
void save (String file, String format="binary-unit-time", bool show=false) const
Saves the recorded values.
const Histogram getHistogram (String what="") const
Returns some value statistics.
Public Member Functions inherited from Input
Input (unsigned int N, double T)
Resets the input dimensions.
virtual ~Input ()
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
Additional Inherited Members
Protected Attributes inherited from Input
unsigned int N
double T
Detailed Description
Defines a static buffered input of a calculation network.
Definition at line 2 of file BufferedInput.hpp.
Constructor & Destructor Documentation
BufferedInput() [1/9]
BufferedInput::BufferedInput (const BufferedInput & input)
Definition at line 8 of file BufferedInput.cpp.
References Input::getN(), Input::getT(), Input::N, and Input::T.
BufferedInput() [2/9]
BufferedInput::BufferedInput (const double * values, unsigned int N, unsigned int T)
Resets the input with static values.
Parameters
values A double[T][N] buffer with the input values, stored a T sequences of N values.
The values are not copied, the buffer must thus be available during the whole object life.
N The number of input units.
T The maximal input time.
Definition at line 18 of file BufferedInput.cpp.
BufferedInput() [3/9]
BufferedInput::BufferedInput (unsigned int N)
Resets the input with static variable time length values.
Values are added in sequence using the add() method.
Parameters
N The number of input units.
Definition at line 19 of file BufferedInput.cpp.
BufferedInput() [4/9]
BufferedInput::BufferedInput (const Input & input, double fconst Input &input, unsigned int n, unsigned int t, unsigned int N0 = 0)
Resets the input from another input with a predefined function.
All input values are called once in sequence during object construction.
Parameters
input The input to buffer.
N0 If 0 < N0 considers only the 1st N0 units.
f A function applied on the each value, this.get(n, t) = f(input, n, t), default simply uses input.get(n, t).
Definition at line 20 of file BufferedInput.cpp.
References Input::N, and Input::T.
BufferedInput() [5/9]
BufferedInput::BufferedInput (const Input & input, unsigned int N0 = 0)
Definition at line 32 of file BufferedInput.cpp.
BufferedInput() [6/9]
BufferedInput::BufferedInput (double funsigned int n, unsigned int t, unsigned int N, unsigned int T)
Resets the input from a predefined function.
All input values are called once in sequence during object construction.
Parameters
f A function applied on the each value, this.get(n, t) = f(input, n, t), default simply uses input.get(n, t).
N The number of input units.
T The maximal input time.
Definition at line 26 of file BufferedInput.cpp.
References Input::N, and Input::T.
BufferedInput() [7/9]
BufferedInput::BufferedInput (String file, String format = "binary-unit-time")
Resets the input with values loaded from a file.
Parameters
file The file name, a .dat extension is added to this name.
format
"binary-unit-time" : ascii integer value header, then unit's value at a given time in sequence, as 64-bits double floating point values:
N T\nget(0, 0) get(1, 0) get(N-1, 0) get(0, 1) get(1, 1) .. get(N-1, 1)
Definition at line 33 of file BufferedInput.cpp.
References assume(), Input::N, and Input::T.
BufferedInput() [8/9]
BufferedInput::BufferedInput (String name, unsigned int N, unsigned int T, ...)
Resets the input with predefined values.
Parameters
name The sequence name.
"normal: A 0 mean and 1 standard-deviation pseudo-random normal value sequence.
Parameter: A seed::unsigned int specifying if the sequence is reproducible (using same seed value at each call) or not.
"sierpinski": The Sierpinski sequence, i.e. the lower bits binary decomposition (with values) of the Pascal triangle read from left to right and form top to down in sequence.
Parameter: None.
"zerone": Generates a random binary sequence of a given period.
Parameter: The binary sequence period.
"ramp": Generates ramps of period T/(n+1), i.e., .
Parameter: None.
"mean" : A reproducible pseudo-random normal value sequence, with a given mean.
Parameter: A mean::double value. The standard-deviation is mean / 10.
"icorr": A reproducible pseudo-random normal value sequence, with inter-correlation between each pair of unit.
Parameter: A icorr::double inter-correlation value.
"acorr": A reproducible pseudo-random normal value sequence, with auto-correlation for each unit.
Parameter: A acorr::double auto-correlation value.
N The number of input units.
T The maximal input time.
Definition at line 46 of file BufferedInput.cpp.
References assume(), random::gaussian(), Input::N, random::setSeed(), Input::T, and random::uniform().
BufferedInput() [9/9]
BufferedInput::BufferedInput (const Input & input, String name, ...)
Resets the input applying a predefined transformation on another input.
Parameters
input The input to buffer.
name The tranformation name.
"affine: Performs an affine transform output(n, t) = offset + gain * input(n, t).
Parameters: The offset::double and the gain::double
"noise": Adds some noise to the input drawn from a normal distribution.
Parameters: The probability to add noise to a given value noiseProbability::double and the standard deviation of the normal added noise noiseStandardDeviation::double
Definition at line 125 of file BufferedInput.cpp.
References assume(), random::gaussian(), Input::get(), Input::N, Input::T, and random::uniform().
~BufferedInput()
BufferedInput::~BufferedInput () virtual
Definition at line 147 of file BufferedInput.cpp.
Member Function Documentation
add()
void BufferedInput::add (const double * value)
Adds a value if (and only if) this is a variable time length buffer.
The time-length is incremented at each step.
Parameters
value A double[N] array with the current time value.
Definition at line 166 of file BufferedInput.cpp.
References assume(), Input::N, and Input::T.
get()
double BufferedInput::get (unsigned int n, double t) const virtual
Returns the input value.
The method is to be overwritten to implement a given input.
Parameters
n The input unit index.
t The value time.
Returns
The input value if defined, else raises a fatal error.
Reimplemented from Input.
Definition at line 154 of file BufferedInput.cpp.
References assume(), Input::N, and Input::T.
save()
void BufferedInput::save (String file, String format = "binary-unit-time", bool show = false) const
Saves the recorded values.
Parameters
file The data file name, a .dat extension is added to this name.
"stdout" : printf the result, in "ascii-unit-time"
format
"binary-unit-time" : as defined for BufferedInput::load()
"ascii-unit-time" : each line stores unit's value at a given time, in sequence, in ascii:
get(0, 0) get(1, 0) .. get(N-1, 0)\nget(0, 1) get(1, 1) .. get(N-1, 1)
"gnuplot" : each line stores a value with indexes, in ascii,
n t get(n, t)
"gnuimg" : stores the data as a float image, each line stores the n-th unt time sequence
get(n, 0) get(n, 1) .. get(n, T-1)
For "gnuplot" and "gnuimg" a gnuplot display script and image is generated, with extensions .gnuplot.sh and .png.
Definition at line 173 of file BufferedInput.cpp.
References assume(), gnuplot(), Input::N, s_printf(), s_save_mkdir(), and Input::T.
Referenced by KernelEstimator::run().
getHistogram()
const Histogram BufferedInput::getHistogram (String what = "") const
Returns some value statistics.
Parameters
what The list of unit index to consider, by default all values are taken into account.
Returns
The given statistics.
Definition at line 228 of file BufferedInput.cpp.
References Histogram::add(), Input::N, s_printf(), and Input::T.
mnemosyne brainybot (version of 2017-10-15 at 10:00:56)