Mnemonas'semiware: solver Class Reference
solver Class Reference
This factory encapsulates equation solvers.
#include <solver.hpp>
Static Public Member Functions
static double linsolve (unsigned int M, unsigned int N, const double *A, bool symmetric, const double *b, double *x, const double *x0=NULL)
Solves a linear system of equations.
static double minimize (double f(double x), double xmin, double xmax, double xeps=NAN, unsigned int imax=0)
Minimizes a 1D function in a given interval.
static double minimize (unsigned int N, double f(const double *x), double d_f(const double *x, unsigned int n), double *x, const double *x0=NULL, double epsilon=1e-6, unsigned int maxIterations=0)
Minimizes a multi-dimensinal function using a 2nd order diagonal and 1st gradient method.
static double projsolve (unsigned int N, unsigned int M, double c(const double *x, unsigned int m), double d_c(const double *x, unsigned int m, unsigned int n), double *x, const double *x0=NULL, double epsilon=1e-6, unsigned int maxIterations=0)
Projects a point onto a manifold defined by implicit equation.
static double getSpectralRadius (const double *A, unsigned int N, double epsilon=1e-6, unsigned int maxIterations=100)
Minimizes a lost with constraints using augmented Lagrangian method.
static std::string asString (const double *A, unsigned int M, unsigned int N=1, bool symmetric=false, String format="%8.1g")
Returns a matrix or vector as a string to dump.
Detailed Description
This factory encapsulates equation solvers.
Definition at line 10 of file solver.hpp.
Member Function Documentation
linsolve()
double solver::linsolve (unsigned int M, unsigned int N, const double * A, bool symmetric, const double * b, double * x, const double * x0 = NULL) static
Solves a linear system of equations.
It uses a SVD decomposition in order to calculates the pseudo-inverse of the system, i.e.
The computational cost is .
Parameters
M The number of equations.
N The number of unknows.
A Either
a double[M*N] non-symmetric input buffer matrix, A(i, j) == A[i + j * N].
a double[N*(N+1)/2] diagonal and lower triangle input buffer of a symmetric matrix, A(i, j) == A[j + i*(i+1)/2], j <= i.
Parameters
symmetric Specifies if the previous parameter is symmetric or not.
b A double[M] input buffer.
x A double[N] output buffer.
x0 A double[N] input buffer. If NULL considers the zero vector. We may have x0 == x.
Returns
The estimation error | b - A x |
Definition at line 15 of file solver.cpp.
Referenced by network::KernelExperimentalEstimator::KernelExperimentalEstimator(), projsolve(), network::KernelDistributedEstimator::run(), and network::KernelEstimator::updateReadout().
minimize() [1/2]
double solver::minimize (double fdouble x, double xmin, double xmax, double xeps = NAN, unsigned int imax = 0) static
Minimizes a 1D function in a given interval.
Parameters
f The function to minimize.
xmin The search lower bound.
xmax The search upper bound.
xeps The required precision. Default is xeps = 1e-6 (xmax - xmin).
imax Maximal number of iterations. Unbounded if 0.
Returns
The best minimal solution.
Definition at line 92 of file solver.cpp.
References assume().
Referenced by CurveFit::add(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), network::KernelDistributedEstimator::run(), and network::KernelEstimator::updateReadout().
minimize() [2/2]
double solver::minimize (unsigned int N, double fconst double *x, double d_fconst double *x, unsigned int n, double * x, const double * x0 = NULL, double epsilon = 1e-6, unsigned int maxIterations = 0) static
Minimizes a multi-dimensinal function using a 2nd order diagonal and 1st gradient method.
Parameters
N The number of unknows.
f The function to minimize.
d_f The $n$-th component of the function gradient to minimize.
x A double[N] output buffer.
x0 A double[N] input buffer. If NULL considers the zero vector. We may have x0 == x.
epsilon The threshold under which two x[n] values are indistinguishable.
maxIterations The maximal number of iteration. The 0 value corresponds to unbounded interation.
Returns
The minimal function value
Definition at line 216 of file solver.cpp.
projsolve()
double solver::projsolve (unsigned int N, unsigned int M, double cconst double *x, unsigned int m, double d_cconst double *x, unsigned int m, unsigned int n, double * x, const double * x0 = NULL, double epsilon = 1e-6, unsigned int maxIterations = 0) static
Projects a point onto a manifold defined by implicit equation.
Parameters
N The number of unknows.
M The number of equations, the manifold is defined by M equations.
c The constraint m-th equation value, .
d_c The constraint m-th equation, n-th component derivative value, .
x A double[N] output buffer.
x0 A double[N] input buffer. If NULL considers the zero vector. We may have x0 == x.
epsilon The threshold under which two x[n] values are indistinguishable.
maxIterations The maximal number of iteration. The 0 value corresponds to unbounded interation.
Returns
The estimation error | c(x) |2
Definition at line 348 of file solver.cpp.
References linsolve().
Referenced by network::ObservableCriterion::update().
getSpectralRadius()
double solver::getSpectralRadius (const double * A, unsigned int N, double epsilon = 1e-6, unsigned int maxIterations = 100) static
Minimizes a lost with constraints using augmented Lagrangian method.
Parameters
N The number of unknows.
M The number of equations, the manifold is defined by M equations.
c The loss value, .
l_c The loss n-th component derivative value, .
c The constraint m-th equation value, .
d_c The constraint m-th equation, n-th component derivative value, .
x A double[N] output buffer.
x0 A double[N] input buffer. If NULL considers the zero vector. We may have x0 == x.
epsilon The threshold under which two x[n] values are indistinguishable.
maxIterations The maximal number of iteration. The 0 value corresponds to unbounded interation.
Returns
The final loss error l(x)
static double projminize(unsigned int N, unsigned int M, double l(const double *x), double d_l(const double *x, unsigned int n), double c(const double *x, unsigned int m), double d_c(const double *x, unsigned int m, unsigned int n), double *x, const double *x0 = NULL, double epsilon = 1e-6, unsigned int maxIterations = 0); Gets the spectral radius of a squared matrix.
Parameters
A The matrix buffer double[N * N] buffer storing A(i, j) == A[i + j * N].
N The number of rows and columns.
epsilon The threshold under which two values are indistinguishable.
maxIterations The maximal number of iteration. The 0 value corresponds to unbounded interation.
Returns
The highest eigen-value of the matrix applying the power-method.
Definition at line 412 of file solver.cpp.
References Density::gaussian().
Referenced by network::RecurrentTransform::getSpectralRadius().
asString()
std::string solver::asString (const double * A, unsigned int M, unsigned int N = 1, bool symmetric = false, String format = "%8.1g") static
Returns a matrix or vector as a string to dump.
Parameters
A The matrix buffer double[M * N] buffer storing A(i, j) == A[i + j * N].
M The number of rows.
N The number of columns.
symmetric If the matrix is symmetric.
format The printf format.
Definition at line 447 of file solver.cpp.
References s_printf().
The documentation for this class was generated from the following files:
src/util/solver.hpp
src/util/solver.cpp
mnemosyne brainybot (version of 2018-06-18 at 08:27:55)