BrainyBot'semiware: ExponentialDecayFit Class Reference
ExponentialDecayFit Class Reference
Fits an exponential decay model on a time series.
#include <ExponentialDecayFit.hpp>
Public Member Functions
ExponentialDecayFit (const ExponentialDecayFit &fit)
ExponentialDecayFit (unsigned int window=10)
Constructs an exponential decay interpolator.
void clear ()
Clears the estomation.
double add (double c)
Adds a value in sequence.
double getCount () const
Gets the number of samples.
double getDecay () const
Gets the decay or NAN if undefined.
double getBias () const
Gets the bias or NAN if undefined.
double getMinimalValue () const
Gets the minimlal value.
double getEstimationTime (double c) const
Gets a future value estimation time.
std::string asString () const
Returns the parameters as a JSON string.
void show (String file, bool show=false) const
Plots the observed and modeled exponential decay in a file.
Detailed Description
Fits an exponential decay model on a time series.
The model is of the form and, in the least-square sense:
The time decay is fitted on .
The bias is fitted on .
The least-square problem for writes: for an exponential window of width where is the fraction of data average within this window (typically 90%) and the bias is estimated as: , while to plot the model we also estimate: ,
Definition at line 12 of file ExponentialDecayFit.hpp.
Constructor & Destructor Documentation
ExponentialDecayFit() [1/2]
ExponentialDecayFit::ExponentialDecayFit (const ExponentialDecayFit & fit)
Definition at line 6 of file ExponentialDecayFit.cpp.
ExponentialDecayFit() [2/2]
ExponentialDecayFit::ExponentialDecayFit (unsigned int window = 10)
Constructs an exponential decay interpolator.
Parameters
window The sampling window containing 90% of the least-square average.
Definition at line 10 of file ExponentialDecayFit.cpp.
References clear().
Member Function Documentation
clear()
void ExponentialDecayFit::clear ()
Clears the estomation.
Definition at line 14 of file ExponentialDecayFit.cpp.
Referenced by ExponentialDecayFit(), and KernelEstimator::run().
add()
double ExponentialDecayFit::add (double c)
Adds a value in sequence.
Parameters
c The value to add in sequence, i.e., at time 0, 1, 2, ...
Returns
The estimation decay stability in number of samples.
Definition at line 19 of file ExponentialDecayFit.cpp.
References getDecay().
Referenced by KernelEstimator::run().
getCount()
double ExponentialDecayFit::getCount () const
Gets the number of samples.
Definition at line 32 of file ExponentialDecayFit.hpp.
References getBias(), and getDecay().
Referenced by asString().
getDecay()
double ExponentialDecayFit::getDecay () const
Gets the decay or NAN if undefined.
Definition at line 37 of file ExponentialDecayFit.cpp.
Referenced by add(), asString(), getBias(), getCount(), getEstimationTime(), and show().
getBias()
double ExponentialDecayFit::getBias () const
Gets the bias or NAN if undefined.
Definition at line 41 of file ExponentialDecayFit.cpp.
References getDecay().
Referenced by asString(), getCount(), getEstimationTime(), and show().
getMinimalValue()
double ExponentialDecayFit::getMinimalValue () const
Gets the minimlal value.
Definition at line 41 of file ExponentialDecayFit.hpp.
References asString(), getEstimationTime(), and show().
getEstimationTime()
double ExponentialDecayFit::getEstimationTime (double c) const
Gets a future value estimation time.
Parameters
c The targeted value.
Returns
The estimation time in number of sample. Returns NAN if below the bias, 0 if already attained.
Definition at line 56 of file ExponentialDecayFit.cpp.
References getBias(), and getDecay().
Referenced by getMinimalValue().
asString()
std::string ExponentialDecayFit::asString () const
Returns the parameters as a JSON string.
Definition at line 62 of file ExponentialDecayFit.cpp.
References getBias(), getCount(), getDecay(), and s_printf().
Referenced by getMinimalValue(), KernelEstimator::run(), and KernelEstimator::~KernelEstimator().
show()
void ExponentialDecayFit::show (String file, bool show = false) const
Plots the observed and modeled exponential decay in a file.
Parameters
file The file name, a gnuplot display data, script and image files are generated, with extensions .dat, .gnuplot.sh and .png.
show If true performs on the fly display.
Definition at line 66 of file ExponentialDecayFit.cpp.
References getBias(), getDecay(), gnuplot(), s_printf(), and s_save().
Referenced by getMinimalValue(), and KernelEstimator::run().
mnemosyne brainybot (version of 2017-06-05 at 15:42:21)