Mnemonas'semiware: Input Class Reference
Input Class Reference
Defines the input of a calculation network.
#include <Input.hpp>
Public Member Functions
Input (unsigned int N, double T)
Resets the input dimensions.
virtual ~Input ()
unsigned int getN () const
Gets the number of input units.
double getT () const
Gets the maximal time range.
virtual double get (unsigned int n, double t) const
Returns the input value.
Protected Attributes
unsigned int N
double T
Detailed Description
Defines the input of a calculation network.
Definition at line 2 of file Input.hpp.
Constructor & Destructor Documentation
Input()
Input::Input (unsigned int N, double T)
Resets the input dimensions.
Parameters
N The number of input units, defined unit indexes stand in {0, N{.
T The maximal time range, defined times stand in [0, T[.
Definition at line 3 of file Input.cpp.
~Input()
virtual Input::~Input () virtual
Definition at line 12 of file Input.hpp.
Member Function Documentation
getN()
unsigned int Input::getN () const
Gets the number of input units.
Definition at line 14 of file Input.hpp.
References N.
Referenced by BufferedInput::BufferedInput(), KernelSupervisedEstimator::drho(), KernelSupervisedEstimator::get(), LinearTransform::getKernelDerivative(), LinearTransform::getKernelDimension(), SoftMaxTransform::getKernelDimension(), SparseNonLinearTransform::getKernelDimension(), LinearNonLinearTransform::getKernelDimension(), IntegrateAndFireTransform::getKernelDimension(), LinearTransform::getKernelValue(), SoftMaxTransform::getKernelValue(), SparseNonLinearTransform::getKernelValue(), LinearNonLinearTransform::getKernelValue(), IntegrateAndFireTransform::getKernelValue(), KernelSupervisedEstimator::rho(), KernelObservableEstimator::rho(), LinearTransform::setWeights(), SoftMaxTransform::setWeights(), LinearNonLinearTransform::setWeights(), IntegrateAndFireTransform::setWeights(), and KernelSupervisedEstimator::update().
getT()
double Input::getT () const
Gets the maximal time range.
Definition at line 19 of file Input.hpp.
References T.
Referenced by BufferedInput::BufferedInput(), KernelObservableEstimator::KernelObservableEstimator(), RecurrentTransform::reset(), KernelObservableEstimator::rho(), and KernelSupervisedEstimator::update().
get()
double Input::get (unsigned int n, double t) const virtual
Returns the input value.
The method is to be overwritten to implement a given input.
Parameters
n The input unit index.
t The value time.
Returns
The input value if defined, else raises a fatal error.
Reimplemented in BufferedInput, and RecurrentTransform.
Definition at line 4 of file Input.cpp.
References assume().
Referenced by BufferedInput::BufferedInput(), KernelSupervisedEstimator::drho(), KernelSupervisedEstimator::get(), LinearTransform::getKernelValue(), SoftMaxTransform::getKernelValue(), SparseNonLinearTransform::getKernelValue(), LinearNonLinearTransform::getKernelValue(), IntegrateAndFireTransform::getKernelValue(), KernelSupervisedEstimator::rho(), and KernelSupervisedEstimator::update().
Member Data Documentation
N
unsigned int Input::N protected
Definition at line 4 of file Input.hpp.
Referenced by BufferedInput::add(), KernelTransform::asString(), BufferedInput::BufferedInput(), RecurrentTransform::get(), BufferedInput::get(), BufferedInput::getHistogram(), LinearTransform::getKernelDerivative(), LinearTransform::getKernelValue(), getN(), RecurrentTransform::getValueDerivativeApproximation(), KernelTransform::getWeight(), RecurrentTransform::reset(), KernelTransform::resetWeights(), BufferedInput::save(), RecurrentTransform::set(), LinearTransform::setOffset(), KernelTransform::setWeight(), and KernelTransform::setWeightsRandom().
T
double Input::T protected
Definition at line 5 of file Input.hpp.
Referenced by BufferedInput::add(), BufferedInput::BufferedInput(), BufferedInput::get(), BufferedInput::getHistogram(), getT(), and BufferedInput::save().
mnemosyne brainybot (version of 2017-10-15 at 10:00:56)