Mnemonas'semiware: src/util/gnuplot.h File Reference
gnuplot.h File Reference
Functions
void gnuplot (String file, String plot, bool show=false)
Generates a gnuplot display script.
Function Documentation
gnuplot()
void gnuplot (String file, String plot, bool show = false)
Generates a gnuplot display script.
Generates a script to display gnuplot commands.
Parameters
file The related data file name (without extension). By contract,
the file basename is used as the plot title;
the file name is used to generate a .gnuplot.sh display script.
the file name is used to generate a .png image of the plot.
the data is stored in a file of extension .dat.
plot The gnuplot display commands.
The $title variable contains the plot title "plot-title" parameter. See: gnuplot set commands.
show If true performs on the fly display.
Definition at line 5 of file gnuplot.c.
References s_save().
Referenced by Histogram::plot(), network::BufferedInput::save(), and CurveFit::show().
mnemosyne brainybot (version of 2018-04-15 at 15:48:49)