Mnemonas'semiware: src/util/s_printf.h File Reference
s_printf.h File Reference
Functions
std::string s_printf (String header,...)
Returns a string formated a-la printf.
Function Documentation
s_printf()
std::string s_printf (String header, ...)
Returns a string formated a-la printf.
Parameters
header Print header. A string or a "format" a-la printf with the subsequent arguments. Formatted strings have 100K bytes maximal size.
Tip: If a spurious error occurs, it is a good idea to test the a-la printf construct via a printf in order the compiler checks the data types.
Returns
The formatted string.
Definition at line 8 of file s_printf.c.
References assume().
Referenced by network::Observable::asString(), CurveFit::asString(), solver::asString(), network::RecurrentTransform::asString(), Histogram::asString(), network::KernelTransform::asString(), network::BufferedInput::getHistogram(), network::ObservableCriterion::getObservable(), network::KernelExperimentalEstimator::KernelExperimentalEstimator(), Histogram::plot(), network::KernelExperimentalEstimator::run(), network::BufferedInput::save(), network::SparseNonLinearTransform::setConnections(), and CurveFit::show().
mnemosyne brainybot (version of 2018-06-18 at 08:27:55)