BrainyBot'semiware: src/inc/s_printf.c File Reference
s_printf.c File Reference
Functions
std::string s_printf (std::string header,...)
Returns a string formated a-la printf.
Function Documentation
s_printf()
std::string s_printf (std::string header, ...)
Returns a string formated a-la printf.
Parameters
header Print header. A string or a "format" a-la printf with the subsequent arguments. Formatted strings have 100K bytes maximal size.
Tip: If a spurious error occurs, it is a good idea to test the a-la printf construct via a printf in order the compiler checks the data types.
Returns
The formatted string.
Definition at line 10 of file s_printf.c.
References assume().
Referenced by ExponentialDecayFit::asString(), Histogram::asString(), KernelTransform::asString(), BufferedInput::getHistogram(), Histogram::plot(), reverse_engineering(), KernelEstimator::run(), BufferedInput::save(), sequence_generation(), ExponentialDecayFit::show(), and KernelEstimator::~KernelEstimator().
mnemosyne brainybot (version of 2017-06-05 at 15:36:53)