BrainyBot'semiware: src/inc/s_regex.c File Reference
s_regex.c File Reference
Functions
std::string s_regex_replace (String string, String regex, String output)
Regex replace function.
bool s_regex_match (String string, String regex)
Regex match function.
Variables
static std::map< unsigned int, std::string > s_regex_error_messages
Function Documentation
s_regex_replace()
std::string s_regex_replace (String string, String regex, String output)
Regex replace function.
Parameters
string The input string.
regex The regular-expression to match.
output The output pattern.
Returns
The string replacement if any, else the original string.
Definition at line 21 of file s_regex.c.
References assume(), and s_regex_error_messages.
Referenced by s_regex_test().
s_regex_match()
bool s_regex_match (String string, String regex)
Regex match function.
Parameters
string The input string.
regex The regular-expression to match.
Returns
True if the string match the regex, false otherwise.
Definition at line 35 of file s_regex.c.
References assume(), and s_regex_error_messages.
Referenced by s_regex_test().
Variable Documentation
s_regex_error_messages
std::map< unsigned int, std::string > s_regex_error_messages static
Initial value:
= {
  { std::regex_constants::error_collate, "The expression contained an invalid collating element name." },
  { std::regex_constants::error_ctype, "The expression contained an invalid character class name." },
  { std::regex_constants::error_escape, "The expression contained an invalid escaped character, or a trailing escape." },
  { std::regex_constants::error_backref, "The expression contained an invalid back reference." },
  { std::regex_constants::error_brack, "The expression contained mismatched brackets ([ and ])." },
  { std::regex_constants::error_paren, "The expression contained mismatched parentheses (( and ))." },
  { std::regex_constants::error_brace, "The expression contained mismatched braces ({ and })." },
  { std::regex_constants::error_badbrace, "The expression contained an invalid range between braces ({ and })." },
  { std::regex_constants::error_range, "The expression contained an invalid character range." },
  { std::regex_constants::error_space, "The memory to convert the expression into a finite state machine overflows." },
  { std::regex_constants::error_badrepeat, "The expression contained a repeat specifier (one of *?+{) that was not preceded by a valid regular expression." },
  { std::regex_constants::error_complexity, "The complexity of an attempted match against a regular expression exceeded a pre-set level." },
  { std::regex_constants::error_stack, "The memory to determine whether the regular expression could match the specified character sequence overflows." }
}
Definition at line 5 of file s_regex.c.
Referenced by s_regex_match(), and s_regex_replace().
mnemosyne brainybot (version of 2017-06-05 at 15:36:53)