Mnemonas'semiware: src/util/s_save.c File Reference
s_save.c File Reference
Functions
void s_save_mkdir (String file)
Creates the directory in order to save in a file.
void s_save (String file, String string)
Saves a string in a file.
Function Documentation
s_save_mkdir()
void s_save_mkdir (String file)
Creates the directory in order to save in a file.
Parameters
file The file name.
Definition at line 9 of file s_save.c.
Referenced by s_save(), and network::BufferedInput::save().
s_save()
void s_save (String file, String string)
Saves a string in a file.
Parameters
file The file name.
string The string to save.
Definition at line 13 of file s_save.c.
References assume(), and s_save_mkdir().
Referenced by gnuplot(), Histogram::plot(), network::KernelExperimentalEstimator::run(), Struct::save(), and CurveFit::show().
mnemosyne brainybot (version of 2018-02-25 at 11:28:53)