BrainyBot'semiware: src/inc/Struct_test.h File Reference
Struct_test.h File Reference
Functions
void Struct_test ()
Struct functional and non regression test.
Function Documentation
Struct_test()
void Struct_test ()
Struct functional and non regression test.
Definition at line 5 of file Struct_test.h.
References Struct::add(), assume(), Struct::del(), Struct::load(), Struct::reset(), and Struct::set().
Referenced by test().
mnemosyne brainybot (version of 2017-06-05 at 15:42:21)